apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/part-of: games
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: minecraft
  ports:
    - port: 25565
      targetPort: java
      protocol: TCP
      name: java
    - port: 19132
      targetPort: bedrock
      protocol: UDP
      name: bedrock
