apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-share
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  volumeName: media-share
  storageClassName: ""
