---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secret
  namespace: open-webui
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgAfGI9/yFoHmM9bF/QgsqEhJCt4zqN9I3LGuWdRt6NnJcvEvibLqE0FXT3eJ87uOjyipZid/iEYue/ErU62WsWrs/HPlb9MDmo3K/7MDPsXChQf9LT9RfFdwo82JGMUdX3zLbCZNbivuoNG35KCnbWir7O7Ibtt5urTuv5g6Ej22YP6xZRRQ7WKFbe5MWrqo+WEa2lU6w2Hx1T2udVREKoeitz3yXibViRwfxRCZuOOQJ24vXpjKRScuCqWiv26W71/no80ztOUAsIdGfU0cyyETJ1juLlwWWTAoDh7M487YvtBQMmu8gaas2Sa2VsCN7acsTKwAUWqzISr71CPuoKE/tMJhSHNyNhRGAUTQoxcYnSnOwilRqVdw6Cd39NJ4lf7UnX/586U5duUH/xzs9RKgO3PPeDLfyBdMw8vQVS54GUBUcSlIEG3YHSb84b/EGt4Y/lf4IU4gHtNGZMAm5f00s0mOd0cbpMvGZd7yMiv6W5gbolFwKdCg0Ng3PQ/biLTnHUDbSsgQvQRxMSFYFC8TDS8MSa5FZLXLcXUxEXqVF3DvVRQRnhv1oRWwtpYusIYe31DBfZx4Gn+6awPyPdIbk/ZxxZr+Qwi1Ir8A51sXxO+M2Zb2wRj/uKbvVy7+yBzkE4ZXZqbuz0ohNAVkQBwkr82wXvNOQ5qcklvkRzwmQi55cvEoC9VZ8DoBUQunWkb8f2htaCyFImb0mn+CuXyUu3R3nA4EKh2DHlZeGyW+8LXxOHYQJMfgbvylZUNp0IdpbwtDLV94hxKyGD0uXax
  template:
    metadata:
      name: open-webui-secret
      namespace: open-webui
