---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: b2-cnpg-credentials
  namespace: pocket-id
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgA1UkbETeUbyVYbkT7mBQLUdky+PFbP//Gy3UHKHty9ffcWLseiidgX1eB8QZgrfg9PZ8tZJ+Sm+LYtEFWfWlClm7iZvaQZOwT9ovA2URq0ux9YyG1QR434rOpebbl2dHT8smCpBVFLHjUw0GVTCWqT/6zU8a2OL79ElwQMYD68BvKLOfeHiIlzIegDhjkwz2Wo2otwLNkfI615bNiZX7CbFZd39vH2bsy9IFIEGZRRgDS5y2jXbnLDwKCBXDRiHkCkib6YqSKwZ+b+XhX0+mVBDMgG9XXu7HIfINdIDHwabZEE0Gfxogf/eEJSHdkaBe7QAaKF7MrQVIlk+Bcm/mxiRWlCWpcGosO3u+2VDOnH0SRzILfQISgT7SJmB8oMrUjQiwReURZVqePOgupf2EliH1isE7toXX7v5zVlWkmLMzDgCP1awMPqCI41JjgZN4ISksspMmsb1wM9bMT9vC7joxUP0wwX/s5fQrcrL8eVWf54h+k0kMP8/nQOur36W1RZWP8He3kO7ZCU33yWA4+QwuREcae0aLs7SVq8ikwUiCd5EJv3zHLOKO98+b+jpkxqL0fZINswbx9NWxE7O8DYdLSi5qYg0GFsCGe61+qFTW/5AdOQmm2VXund+tnilLjTnKcLklC0XXc3QYm1GaVQw4iZGk/3Qszh76O9/xBcWibPo37sq188oTA+psXK2gfu5wDIc98DkR5m/S2vcBTxXh4p8RVtCD/T
    AWS_SECRET_ACCESS_KEY: AgCE6akqnOPJNFgzh5eaTh2Bqg96TrZ5yvo3pZQ5SynOeIR+oBsOm4SP0eeLIDZ8UqZL6/N5SJmeaSVSCv1EUsJA/niUzvJz8dQqPJ0DnNsbZRiSCPz7K/flGak373QJAC4CAGYhOjdfMiQvxoahpBFZ7Lld/vjvBGFOBVQiDFdt6kzZBtQs29Z7Z9RkVwwwPN5z0ypca5mBcxLvVimdqdjXyIcecGVdMiDOKTNikXgl0AdYCqj0TJiHp3Bg1oAzcujN6tBWFDrNHXSzB1JIh3hh9LMlfLYBqHe6c82+0JoSfBPA+MLEuxHcy7imHbIRfIQS+4+OYUY7QluoKWAXhlNNbhrHYsD6JuCBYj9bWVulDF/a/mCAc++bZOyMnyqSIZfs/nsUKUkRA+fjuoSlj5pzNBrxaC5Hy3LVlrGLvOrS7261eSCbxPfOB9G07+e8PUi8lRZA5QJuDv1nAtUe5lZ84efw4iVm8jLH8pRt3ZR5inPqqk9Ph3zStOcD0/nY0VWohaojBGPVDpQNz2rku3Eua7WBhINXr+kAF78v2ZXD5MLTxdjuQD9oV2OHp4ejiDUaWQlm/vyBTEqErgtb7IDEYwvpRCAvV5v6g5CY6ogjuEQBhJN2Ed/C8BODPXkVBazKep3S5P5d77pM9b/HbfIO87GNZsomaU/F+vMGpbkn9ZWeVF1X0599FniKP29zBbet9RKgnvNtzPe6fRFc/BWzWdtY1c4/C3l7Fk4ht67i
  template:
    metadata:
      name: b2-cnpg-credentials
      namespace: pocket-id
