apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pocket-id

resources:
- namespace.yaml
- runtime-sealed-secret.yaml
- b2-sealed-secret.yaml
- rustfs-sealed-secret.yaml
- database.yaml
- database-scheduled-backup.yaml
- podmonitor.yaml
- deployment.yaml
- svc.yaml
