apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pocket-id-postgresql
  namespace: pocket-id
  labels:
    app.kubernetes.io/name: postgresql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      cnpg.io/cluster: pocket-id-postgresql
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - pocket-id
