---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-credentials
  namespace: pocket-id
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBUk2ZuwXBK3QthSoiS3cwM1URvHigy4t+D99zU/l9GBa2K0tGeHVqjkPQDKmMG2MNIhqEEOjP0DWK3WPzmsaRy0uSQ3MeXyVXBzbQEJ8MOL/UrhelPgz/Pk0ktruErSQzEdmD1WuhvdHe+o9ggit1Wfp3RbvyF2mzz5MCqO2HpW2EeT1c3R1HwQYX2aQ8YQNye1/vU03dFQMU24T8Tw5Z6YYtuf+o+ENEnzRfz2o2AkdoMGu2/+J9/J4QhkDQLLFlAjfNU6/d77050zRkJDkFUe2DXfA5LKc3a/KUJOAU45VYIYnFE+OB/iSs1CejqQDj4Lmukvnw3bvgkGqTDt76eSMDky74HwCQJR1JkgCCzriJuSt5GUJL1IzYcdRwxD3zKGbTitkVQPu876D+vza7hXiSFXkzSQsz54ub5aayUub1VwRlyC6ehAL02zauG7kjpGB03yfZ950bAjIe/LlJ1bhtciCsvAfL8o1Nfr9ZhnRDa7b4rpipXH6fF/7uRvCCXRynEmIz6sN/ZGXm38dg88kIEr6BsqytUvT1FUmpqu0AsJQNAR04H3eXLcSl4fId6YEJkdqCtwKUlKfiEO/eTHyPLQAzDpybMQA839sQBz392x/XuLchQ5p+/jXG21xgnNDP+zc7E6Tic0+CyJdjJ2Nn28W9D38eFV4+zeNcSay2Zw28HfTVRHEvPJybGeICGtZgWjCH0TsImCWSksQFs1b849Q==
    AWS_SECRET_ACCESS_KEY: AgCg2K8CVaefVnDK42wo29XHJl5CMj5ODooNGcO2tb0rPUJVcOlXLhQ5Hd+7GnDCFvpQ3z2h3yXmL9kfDH66Q7GDCFk93fgKvQoFo6m+nd0Hgppe/rOF1pvILo7Xr5F2HSeUEVUZuPmI02hKiszGSLx9cqzNc3HhZ9ATrYNOXWJxzN5idLlyoFLsdNZsJGVCRaIAma5oyvkxwu3D14gZNAIv6m30K052l9qg5KA38bNO006wRv0elE4KeJv4pNcekU7ojzo/lPaYqKGhHldcFMFSNT58KdWd7diny8smZbTJLPgtxCHKC3oJG574ie7+YumVWZYIguBOAYosNkWhew2SZ/TcLiKKfeRuFtV4Uv0qikqFXdw/elBUikC0GgyvbyRU4iINP2IYbB5oNGe4jLqWnl8twKGsk4LyDvTdJfVozu0H1x22bI7p4940GmGLXcCHliNqDfqH7agE7RqWSsDh478k3dexqg3XMWiWl+FVN7oQAFsyNTUKldUznrusgSovezURNH/3JcKIf/WTFyXbe0cBsrXa9vlse6i5r5b+ntzO//hGGvGclnNU3HpF35GkKcV+G3jKPWPmNns/b9hgKQkbWpatUjmBy/VmYzzVb6sbwl4RfbcU8tT9z4JDjp2x9KFDzxpXCosU8pwqI0zEPxfck9Sb4JrdXAevjzqQQ4QD89ZUkfqH1qcMjz96D4u/TwtTDGhWwogf5mGlt+Mz2y0oeN9sf+8htmW3zTqVs2SfDM9Dn/Ci
  template:
    metadata:
      name: rustfs-credentials
      namespace: pocket-id
