---
services:
  app:
    image: docker.io/rustfs/rustfs:1.0.0-alpha.82@sha256:eadee1b524ec05cbc1fe08426a95e589bc70e70cd15a4591edf176cabde238a6
    container_name: rustfs_app_1
    user: "${PUID}:${PGID}"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 9000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      - RUSTFS_SERVER_DOMAINS=${RUSTFS_HOSTNAME}
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_ACCESS_KEY=${RUSTFS_ACCESS_KEY} # Generate your own access key with `openssl rand -hex 16`
      - RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY} # Generate your own secret key with `openssl rand -hex 32`
    volumes:
      - ${APP_DATA_DIR}/rustfs/data:/data:rw
      - ${APP_DATA_DIR}/rustfs/logs:/logs:rw
    ports:
      - 9540:9000
    restart: unless-stopped
