[[stack]]
name = "rustfs"
description = "Stack RustFS"
deploy = true

[stack.config]
server_id = "ds920plus"
linked_repo = "homelab"
run_directory = "compose/ds920plus/prod/rustfs"
auto_pull = true
send_alerts = true

compose_cmd_wrapper_include = ["config", "pull", "up"]
compose_cmd_wrapper = """
[[INFISICAL_RUN]] \
  --projectId='[[INFISICAL_PROJECT_ID]]' \
  --env=prod \
  --path=/compose/ds920plus/s3/rustfs \
  --command '[[COMPOSE_COMMAND]]'"""