apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opencloud

resources:
- namespace.yaml
- service-account.yaml
- nfs-pv.yaml
- nfs-pvc.yaml
- pvc.yaml
- csp-configmap.yaml
- deployment.yaml
- service.yaml
- collabora.yaml
- tika.yaml
- http-route.yaml
- network-policy.yaml
- sealed-secret.yaml
