apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: opencloud
  namespace: opencloud
  labels:
    app.kubernetes.io/name: opencloud
    app.kubernetes.io/part-of: opencloud
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: opencloud
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gateway
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: newt
      ports:
        - protocol: TCP
          port: 9200
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: tika
      ports:
        - protocol: TCP
          port: 9998
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: collabora
  namespace: opencloud
  labels:
    app.kubernetes.io/name: collabora
    app.kubernetes.io/part-of: opencloud
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: collabora
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: newt
      ports:
        - protocol: TCP
          port: 9980
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tika
  namespace: opencloud
  labels:
    app.kubernetes.io/name: tika
    app.kubernetes.io/part-of: opencloud
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: tika
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: opencloud
      ports:
        - protocol: TCP
          port: 9998
  egress: []
