---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opencloud-admin
  namespace: opencloud
spec:
  encryptedData:
    IDM_ADMIN_PASSWORD: AgA+NNYf9Rw13ZFHCzLDbke0RgWmUQcEP7WU84GuCA3ivmpNDJlc9tnj+5BZzwJEhHZubrfptnOvPfCMumgAe26gjmtJEzDJH33le5rrgRYw7Bg1ZUdp9CgD4KG1GTsdCvr/6oamIELi4z2p4VfPkzCfCaR7AR9AaM9jp1PdrQ5SVvAXNU3p+fe0cdlZVdQhX2fOU0Z/85V7A6Ru2kJzxQ9JYu52w3xS2ked1yfVYerepdQGc3VuLZJ+2bz5F/Vxz6FsqIh+hjQydl0hVHVgmFwTGEcqX0V+XEa0ZNnWrmZgmGZf8UQI2NUBhVzmXsqiqlDERth045R9ILClSsfyT9EDjDVM19HIu2V6krLS//INlRYJAab0kLq5D3HIdrAar0hYHdcm8Rs7C5aLUjEgIUL+IuEKA2Me2oYigWkE9KnG2lHRj93+xH2T8lAiwSIrXSoq8yS6I4zu1bu3XuTApgSZpoIWHak4Aed42JyTMbUkyvi256g8UG5pKudN7xw/WHoUw6/kO6hO9FsqXuYmnEXk49CjMBjoeAYhnMuR+HVS+wCieMZMQlQMiXjDH0R9vIz0vieIOP2/Rv7f6GeR80rQUoDU7ttYISR1H4cquLTUCbSbLFrtjZep1BUCyiJpi3AR/B5SVax6x4OO752/Vaxq0Vc8/kgNCnDqSfOmXalMzEV2JBGKET1B5zB2vWkNMRonZplzhsfQlw==
  template:
    metadata:
      name: opencloud-admin
      namespace: opencloud
