apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  namespace: opencloud
  labels:
    app.kubernetes.io/name: tika
    app.kubernetes.io/component: content-extractor
    app.kubernetes.io/part-of: opencloud
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: tika
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tika
        app.kubernetes.io/component: content-extractor
        app.kubernetes.io/part-of: opencloud
    spec:
      serviceAccountName: opencloud
      automountServiceAccountToken: false
      hostIPC: false
      hostNetwork: false
      hostPID: false
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 35002
        runAsGroup: 35002
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: tika
          image: docker.io/apache/tika:3.3.1.0@sha256:90b7fa1dc018434075fce9e1d9b88b1e3d0ea6979d0cf86e116c79a8073ae973
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError
          ports:
            - name: http
              containerPort: 9998
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          startupProbe:
            httpGet:
              path: /tika
              port: http
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /tika
              port: http
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /tika
              port: http
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tika
  namespace: opencloud
  labels:
    app.kubernetes.io/name: tika
    app.kubernetes.io/component: content-extractor
    app.kubernetes.io/part-of: opencloud
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tika
  ports:
    - name: http
      appProtocol: http
      port: 9998
      targetPort: http
      protocol: TCP
