name: komodo

services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17-0.107.0@sha256:2386795ec2aa7ae559304361979f1dc5708d383ee9020ae63dadc2940dfe58f7
    container_name: komodo_postgres_1
    labels:
      komodo.skip:
    environment:
      POSTGRES_USER: ${KOMODO_DB_USERNAME}
      POSTGRES_PASSWORD: ${KOMODO_DB_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - ${APP_DATA_DIR}/komodo/data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2.7.0@sha256:5706414241eb84f0515512c37b46db0f1b1eac9e5ceb7e4c2523211c184b1985
    container_name: komodo_ferretdb_1
    user: "${PUID}:${PGID}"
    labels:
      komodo.skip:
    depends_on:
      - postgres
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://${KOMODO_DB_USERNAME}:${KOMODO_DB_PASSWORD}@komodo_postgres_1:5432/postgres
    volumes:
      - ${APP_DATA_DIR}/komodo/data/ferretdb:/state
    restart: unless-stopped

  core:
    image: ghcr.io/moghtech/komodo-core:2.3.3@sha256:bca73d0eee143066228fb9b80c38a5a2726e573ad2758f7aa92b5c91a8aef1c7
    container_name: komodo_core_1
    init: true
    depends_on:
      - ferretdb
    ports:
      - 9120:9120
    environment:
      TZ: ${TZ}
      KOMODO_DATABASE_ADDRESS: komodo_ferretdb_1:27017
      KOMODO_DATABASE_USERNAME: ${KOMODO_DB_USERNAME}
      KOMODO_DATABASE_PASSWORD: ${KOMODO_DB_PASSWORD}
      KOMODO_FIRST_SERVER_NAME: ds920plus
      KOMODO_PERIPHERY_PUBLIC_KEY: file:/config/keys/periphery.pub
      KOMODO_JWT_SECRET: ${KOMODO_JWT_SECRET}
      KOMODO_WEBHOOK_SECRET: ${KOMODO_WEBHOOK_SECRET}
    env_file:
      - ${APP_DATA_DIR}/komodo/settings.env
    volumes:
      - ${APP_DATA_DIR}/komodo/data/core:/backups
      - ${APP_DATA_DIR}/komodo/data/keys:/config/keys
    labels:
      - komodo.skip=
      # Public Resource Configuration
      - pangolin.public-resources.komodo.name=komodo
      - pangolin.public-resources.komodo.full-domain=${KOMODO_HOSTNAME}
      - pangolin.public-resources.komodo.protocol=http
      # Auth: SSO
      - pangolin.public-resources.komodo.auth.sso-enabled=true
      # Target Configuration - Override to Host Hairpin
      - pangolin.public-resources.komodo.targets[0].method=http
      - pangolin.public-resources.komodo.targets[0].hostname=127.0.0.1
      - pangolin.public-resources.komodo.targets[0].port=9120
      # Health Check Configuration
      - pangolin.public-resources.komodo.targets[0].healthcheck.enabled=true
      - pangolin.public-resources.komodo.targets[0].healthcheck.hostname=127.0.0.1
      - pangolin.public-resources.komodo.targets[0].healthcheck.port=9120
      - pangolin.public-resources.komodo.targets[0].healthcheck.path=/
    restart: unless-stopped

  periphery:
    build: .
    container_name: komodo_periphery_1
    init: true
    environment:
      TZ: ${TZ}
      PERIPHERY_ROOT_DIRECTORY: /etc/komodo
      PERIPHERY_CORE_ADDRESS: ws://komodo_core_1:9120
      PERIPHERY_CONNECT_AS: ds920plus
      PERIPHERY_CORE_PUBLIC_KEY: file:/config/keys/core.pub
      PERIPHERY_DISABLE_TERMINALS: false
      PERIPHERY_DISABLE_CONTAINER_TERMINALS: false
      PERIPHERY_DEFAULT_TERMINAL_COMMAND: sh
      PERIPHERY_INCLUDE_DISK_MOUNTS: /etc/hostname
      PERIPHERY_LOGGING_PRETTY: false
      PERIPHERY_PRETTY_STARTUP_CONFIG: false
      PERIPHERY_CORE_TLS_INSECURE_SKIP_VERIFY: true
      DOCKER_API_VERSION: 1.43
    volumes:
      - ${APP_DATA_DIR}/komodo/data/periphery/config:/etc/komodo
      - ${APP_DATA_DIR}/komodo/data/keys:/config/keys
      - /proc:/proc
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
