# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# yamllint disable-file
# prettier-ignore-start
# eslint-disable
---
version: 1
metadata:
  name: Apps - Gramps Web
entries:
  - id: gramps_web_provider
    model: authentik_providers_oauth2.oauth2provider
    identifiers:
      name: eudald.gr/gramps-web
    attrs:
      authorization_flow:
        !Find [
          authentik_flows.flow,
          [slug, "default-provider-authorization-implicit-consent"],
        ]
      signing_key:
        !Find [
          authentik_crypto.certificatekeypair,
          [name, "authentik Self-signed Certificate"],
        ]
      invalidation_flow:
        !Find [
          authentik_flows.flow,
          [slug, "default-provider-invalidation-flow"],
        ]
      client_type: confidential
      grant_types:
        - authorization_code
        - refresh_token
      redirect_uris:
        - url: https://gramps.eudald.gr/api/oidc/callback/custom
          matching_mode: strict
          redirect_uri_type: authorization
      client_id: !Env GRAMPSWEB_CLIENT_ID
      client_secret: !Env GRAMPSWEB_CLIENT_SECRET
      access_code_validity: minutes=1
      access_token_validity: hours=1
      refresh_token_validity: days=30
      sub_mode: hashed_user_id
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, "openid"]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, "profile"]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, "email"]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, "groups"]]

  - id: gramps_web_application
    model: authentik_core.application
    identifiers:
      slug: gramps-web
    attrs:
      name: Gramps Web
      group: Web
      meta_description: Genealogy
      provider: !KeyOf gramps_web_provider
      policy_engine_mode: any

  - id: gramps_web_owners_policy_binding
    model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf gramps_web_application
      group: !Find [authentik_core.group, [name, "Gramps Owners"]]
    attrs:
      order: 1

  - id: gramps_web_members_policy_binding
    model: authentik_policies.policybinding
    identifiers:
      target: !KeyOf gramps_web_application
      group: !Find [authentik_core.group, [name, "Gramps Members"]]
    attrs:
      order: 2
