# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# yamllint disable-file
# prettier-ignore-start
# eslint-disable
---
version: 1
metadata:
  name: Brands
entries:
  - model: authentik_brands.brand
    identifiers:
      domain: eudald.gr
    attrs:
      branding_title: Homelab
