# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
# yamllint disable-file
# prettier-ignore-start
# eslint-disable
---
version: 1
metadata:
  name: Groups - Applications
entries:
  - id: argocd-admins
    model: authentik_core.group
    identifiers:
      name: ArgoCD Admins
    attrs:
      name: ArgoCD Admins
  - id: argocd-viewers
    model: authentik_core.group
    identifiers:
      name: ArgoCD Viewers
    attrs:
      name: ArgoCD Viewers
  - id: grafana-admins
    model: authentik_core.group
    identifiers:
      name: Grafana Admins
    attrs:
      name: Grafana Admins
  - id: grafana-users
    model: authentik_core.group
    identifiers:
      name: Grafana Users
    attrs:
      name: Grafana Users
  - id: kubectl-users
    model: authentik_core.group
    identifiers:
      name: Kubectl Users
    attrs:
      name: Kubectl Users
