apiVersion: v1
kind: ServiceAccount
metadata:
  name: jellyfin
  namespace: arr
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: applications
    app.kubernetes.io/managed-by: argocd
