apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omada

resources:
- namespace.yaml
- certificate.yaml

helmCharts:
- name: omada-controller-helm
  repo: oci://registry-1.docker.io/mbentley
  version: 1.4.0
  releaseName: omada-controller
  namespace: omada
  valuesFile: values.yaml

generatorOptions:
  disableNameSuffixHash: true

patches:
- path: patch-service-https.yaml
