apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: omada-discovery
  namespace: omada
spec:
  parentRefs:
    - name: tls-passthrough
      namespace: gateway
      sectionName: omada-discovery
  rules:
    - backendRefs:
        - name: omada-controller
          port: 29810
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: omada-management
  namespace: omada
spec:
  parentRefs:
    - name: tls-passthrough
      namespace: gateway
      sectionName: omada-management
  rules:
    - backendRefs:
        - name: omada-controller
          port: 19810
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: omada-app-discovery
  namespace: omada
spec:
  parentRefs:
    - name: tls-passthrough
      namespace: gateway
      sectionName: omada-app-discovery
  rules:
    - backendRefs:
        - name: omada-controller
          port: 27001
