image:
  pullPolicy: IfNotPresent

config:
  rootless: true
  timezone: Europe/Madrid
  showServerLogs: true
  showMongoDBLogs: false

service:
  type: ClusterIP
  annotations:
    external-dns.alpha.kubernetes.io/hostname: omada.k8s.eudald.gr
    external-dns.alpha.kubernetes.io/target: "10.1.20.113"
    external-dns.alpha.kubernetes.io/ttl: "300"

persistence:
  data:
    enabled: true
    storageClassName: proxmox-csi
    size: 1Gi
  logs:
    enabled: true
    storageClassName: proxmox-csi
    storageClass: proxmox-csi
    size: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 750m
    memory: 2Gi

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

startupProbe:
  httpGet:
    path: /login
    port: manage-https
    scheme: HTTPS
  failureThreshold: 60
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /login
    port: manage-https
    scheme: HTTPS
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /login
    port: manage-https
    scheme: HTTPS
  initialDelaySeconds: 120
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 3
