---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: newt-credentials
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/network/newt
      recursive: false
  targets:
    - name: newt-credentials
      namespace: network
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          PANGOLIN_ENDPOINT: "{{ .PANGOLIN_ENDPOINT.Value }}"
          NEWT_ID: "{{ .NEWT_ID.Value }}"
          NEWT_SECRET: "{{ .NEWT_SECRET.Value }}"