---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: kopiur-repository
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/kopiur
      recursive: false
  targets:
    - name: kopiur-repository-secret
      namespace: kopiur-system
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD.Value }}"
          AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID.Value }}"
          AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY.Value }}"