#!/bin/sh

: "${MAINBOARD:="lenovo"}"
: "${MODEL:="m920q"}"
: "${PLATFORM:="cnl"}"
: "${COREBOOT_SDK_VERSION:="latest"}"
: "${COREBOOT_DISTRO:="coreboot"}"
: "${COREBOOT_TAG:="25.03"}"
: "${COREBOOT_ROOT_DIR:="/home/coreboot"}"
: "${COREBOOT_BUILD_DIR:="$COREBOOT_ROOT_DIR/cb_build"}"
: "${COREBOOT_OUTPUT_DIR:="$COREBOOT_ROOT_DIR/out"}"
: "${COREBOOT_CONFIG_DIR:="$COREBOOT_ROOT_DIR/conf"}"
: "${COREBOOT_CONFIG:="auto"}"
: "${COREBOOT_STOCK_BIOS_DIR:="$COREBOOT_ROOT_DIR/stock_bios"}"
: "${COREBOOT_STOCK_BIOS_ROM:="stock_bios.rom"}"

usage()
{
    cat << EOF
usage: ${0##*/} [options ...]
       -d, --debug                     enable debug mode
       -h, --help                      show this help

EOF
}

prepare_environment()
{
    while [ "$1" ]; do case "$1" in
        -m | --model)
            MODEL="${2:?}"; shift 2
        ;;
        -v | --coreboot-version)
            COREBOOT_TAG="${2:?}";   shift 2
        ;;
        -s | --coreboot-sdk-version)
            COREBOOT_SDK_VERSION="${2:?}"; shift 2
        ;;
        -d | --debug)
            _DEBUG=1; shift 1
        ;;
        -h | --help)
            usage; exit 0
        ;;
        *)
            printf "invalid option: %s\n\n" "$1"
            usage; exit 1
        ;;
    esac; done

    # false positive
    # shellcheck disable=2015
    [ "$_DEBUG" = 1 ] && set -x || :
}

make_coreboot()
{
    docker run --rm -it \
        --user "$(id -u):$(id -g)" \
        -v "$PWD/$MODEL:$COREBOOT_CONFIG_DIR:ro" \
        -v "$PWD/$MODEL/build:$COREBOOT_BUILD_DIR" \
        -v "$PWD/$MODEL/stock_bios:$COREBOOT_STOCK_BIOS_DIR:ro" \
        -v "$PWD/$MODEL/out:$COREBOOT_ROOT_DIR/out" \
        -e _DEBUG="${_DEBUG:-0}" \
        -e MAINBOARD="$MAINBOARD" \
        -e MODEL="$MODEL" \
        -e PLATFORM="$PLATFORM" \
        -e COREBOOT_DISTRO="$COREBOOT_DISTRO" \
        -e COREBOOT_TAG="$COREBOOT_TAG" \
        -e COREBOOT_BUILD_DIR="$COREBOOT_BUILD_DIR" \
        -e COREBOOT_STOCK_BIOS_DIR="$COREBOOT_STOCK_BIOS_DIR" \
        -e COREBOOT_STOCK_BIOS_ROM="$COREBOOT_STOCK_BIOS_ROM" \
        -e COREBOOT_OUTPUT_DIR="$COREBOOT_OUTPUT_DIR" \
        -e COREBOOT_CONFIG_DIR="$COREBOOT_CONFIG_DIR" \
        -e COREBOOT_CONFIG="$COREBOOT_CONFIG" \
        docker.io/coreboot/coreboot-sdk:"$COREBOOT_SDK_VERSION" \
        /home/coreboot/conf/make
}

# int main()
{
    # enable exit on error and disable globbing
    set -ef

    prepare_environment "$@"
    make_coreboot
}