[[procedure]]
name = "Backup Core Database"
description = "Triggers the Core database backup at the scheduled time."
tags = ["system"]

[procedure.config]
schedule_format = "English"
schedule = "Every day at 01:00"
schedule_enabled = true
schedule_alert = false
failure_alert = true

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "BackupCoreDatabase", execution.params = {}, enabled = true },
]

[[procedure]]
name = "Global Auto Update"
description = "Pulls and auto updates Stacks and Deployments using 'poll_for_updates' or 'auto_update'."
tags = ["system"]

[procedure.config]
schedule_format = "English"
schedule = "Every day at 03:00"
schedule_enabled = true
schedule_alert = false
failure_alert = true

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "GlobalAutoUpdate", execution.params.skip_auto_update = false, enabled = true },
]

[[procedure]]
name = "Auto Sync Main"
description = "Runs the main Komodo Resource Sync every 5 minutes."
tags = ["system"]

[procedure.config]
schedule_format = "English"
schedule = "Every 5 minutes"
schedule_enabled = true
schedule_timezone = "Europe/Madrid"
schedule_alert = false
failure_alert = true
webhook_enabled = true

[[procedure.config.stage]]
name = "Pull stack repo"
enabled = true
executions = [
  { execution.type = "PullRepo", execution.params.repo = "homelab", enabled = true },
]

[[procedure.config.stage]]
name = "Destroy removed GitOps stacks"
enabled = true
executions = [
  { execution.type = "RunAction", execution.params.action = "destroy-removed-gitops-stacks", enabled = true },
]

[[procedure.config.stage]]
name = "Sync main"
enabled = true
executions = [
  { execution.type = "RunSync", execution.params.sync = "main", enabled = true },
]

[[procedure.config.stage]]
name = "Deploy changed GitOps stacks"
enabled = true
executions = [
  { execution.type = "RunAction", execution.params.action = "deploy-changed-gitops-stacks", enabled = true },
]
