[[repo]]
name = "homelab-host01"
description = "Repositori principal del homelab"
tags = ["homelab", "github", "host01"]

[repo.config]
server_id = "host01"
git_provider = "github.com"
repo = "eudaldgr/homelab"
branch = "main"
