[[resource_sync]]
name = "main"

[resource_sync.config]
git_provider = "github.com"
git_account = "eudaldgr"
repo = "eudaldgr/homelab"

resource_path = [
  "komodo/builders.toml",
  "komodo/repos.toml",
  "komodo/servers.toml",
  
  # ds920plus specific
  #"compose/ds920plus/prod/adguard/stack.toml",
  #"compose/ds920plus/prod/adguard-sync/stack.toml",
  "compose/ds920plus/prod/bitcoind-core/stack.toml",
  "compose/ds920plus/prod/fulcrum/stack.toml",
  "compose/ds920plus/prod/newt/stack.toml",
  #"compose/ds920plus/prod/rustfs/stack.toml",
]