[[resource_sync]]
name = "main"

[resource_sync.config]
git_provider = "github.com"
git_account = "eudaldgr"
repo = "eudaldgr/homelab"

resource_path = [
  "komodo/builders.toml",
  "komodo/repos.toml",
  "komodo/servers.toml",
  
  # host01 specific
  "compose/host01/prod/newt/stack.toml",
  
  # host02 specific
  "compose/host02/prod/newt/stack.toml",
  
  # ds920plus specific
  # "compose/ds920plus/prod/adguard/stack.toml",
  # "compose/ds920plus/prod/bitcoind-core/stack.toml",
  "compose/ds920plus/prod/newt/stack.toml",
]