public-resources:
  vaultwarden:
    name: vaultwarden
    protocol: http
    full-domain: bitwarden.eudald.gr
    auth:
      sso-enabled: false
    rules:
      - action: deny
        match: path
        value: /admin
      - action: deny
        match: path
        value: /admin/*
    targets:
      - hostname: vaultwarden.vaultwarden.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: vaultwarden.vaultwarden.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /alive
          method: GET
