public-resources:
  flux-webhook:
    name: flux webhook
    protocol: http
    full-domain: flux-webhook.eudald.gr
    auth:
      sso-enabled: false
    targets:
      - hostname: webhook-receiver.flux-system.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: webhook-receiver.flux-system.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET
          status: 404

  radarr:
    name: radarr
    protocol: http
    full-domain: radarr.eudald.gr
    auth:
      sso-enabled: true
    rules:
      - action: allow
        match: path
        value: /api/*
    targets:
      - hostname: radarr.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: radarr.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  sonarr:
    name: sonarr
    protocol: http
    full-domain: sonarr.eudald.gr
    auth:
      sso-enabled: true
    rules:
      - action: allow
        match: path
        value: /api/*
    targets:
      - hostname: sonarr.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: sonarr.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  lidarr:
    name: lidarr
    protocol: http
    full-domain: lidarr.eudald.gr
    auth:
      sso-enabled: true
    rules:
      - action: allow
        match: path
        value: /api/*
    targets:
      - hostname: lidarr.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: lidarr.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  prowlarr:
    name: prowlarr
    protocol: http
    full-domain: prowlarr.eudald.gr
    auth:
      sso-enabled: true
    targets:
      - hostname: prowlarr.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: prowlarr.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  qbittorrent:
    name: qbittorrent
    protocol: http
    full-domain: torrent.eudald.gr
    auth:
      sso-enabled: true
    targets:
      - hostname: qbittorrent.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: qbittorrent.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  seerr:
    name: seerr
    protocol: http
    full-domain: seerr.eudald.gr
    targets:
      - hostname: seerr.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: seerr.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  tautulli:
    name: tautulli
    protocol: http
    full-domain: tautulli.eudald.gr
    rules:
      - action: allow
        match: path
        value: /api/*
    targets:
      - hostname: tautulli.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: tautulli.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  plex:
    name: plex
    protocol: http
    full-domain: plex.eudald.gr
    targets:
      - hostname: plex.media.svc.cluster.local
        port: 32400
        method: http
        healthcheck:
          hostname: plex.media.svc.cluster.local
          port: 32400
          mode: http
          scheme: http
          path: /identity
          method: GET

  bentopdf:
    name: bentopdf
    protocol: http
    full-domain: pdf.eudald.gr
    targets:
      - hostname: bentopdf.utilities.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: bentopdf.utilities.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  searxng:
    name: searxng
    protocol: http
    full-domain: searx.eudald.gr
    targets:
      - method: http
        hostname: searxng.utilities.svc.cluster.local
        port: 80
        healthcheck:
          enabled: true
          hostname: searxng.utilities.svc.cluster.local
          port: 80
          path: /healthz
          headers:
            - name: X-Real-IP
              value: 127.0.0.1

  vaultwarden:
    name: vaultwarden
    protocol: http
    full-domain: bitwarden.eudald.gr
    auth:
      sso-enabled: false
    rules:
      - action: deny
        match: path
        value: /admin
      - action: deny
        match: path
        value: /admin/*
    targets:
      - hostname: vaultwarden.vaultwarden.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: vaultwarden.vaultwarden.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /alive
          method: GET

  it-tools:
    name: it tools
    protocol: http
    full-domain: tools.eudald.gr
    targets:
      - hostname: it-tools.utilities.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: it-tools.utilities.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  kromgo:
    name: kromgo
    protocol: http
    full-domain: kromgo.eudald.gr
    targets:
      - hostname: kromgo.o11y.svc.cluster.local
        port: 8080
        method: http
        healthcheck:
          hostname: kromgo.o11y.svc.cluster.local
          port: 8080
          mode: http
          scheme: http
          path: /readyz
          method: GET
