---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalPushSecret
metadata:
  name: eudald-gr-tls
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 1m
  updatePolicy: Replace
  deletionPolicy: None
  destination:
    projectSlug: homelab
    environmentSlug: prod
    secretsPath: /kubernetes/certificates/eudald-gr
  push:
    secret:
      secretName: eudald-gr-tls
      secretNamespace: network
      template:
        includeAllSecrets: false
        data:
          TLS_CRT: '{{ (index . "tls.crt").Value }}'
          TLS_KEY: '{{ (index . "tls.key").Value }}'
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical-system
