---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: seerr
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/seerr
      recursive: false
  targets:
    - name: seerr-secret
      namespace: media
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          API_KEY: "{{ .SEERR_API_KEY.Value }}"