---
- name: Install k3s servers
  ansible.builtin.command: |
    /usr/bin/k3s-install server
  args:
    creates: /etc/systemd/system/k3s.service
  changed_when: false
  when: inventory_hostname in groups['servers']
  tags: k3s

- name: Install k3s agents
  ansible.builtin.command: |
    /usr/bin/k3s-install agent
  args:
    creates: /etc/systemd/system/k3s-agent.service
  changed_when: false
  when: (inventory_hostname in groups['agents']) or (inventory_hostname in groups['longhorns'])
  tags: k3s

- name: Disable k3s service to avoid auto-start
  ansible.builtin.systemd_service:
    name: k3s
    enabled: false
    state: stopped
  when: inventory_hostname in groups['servers']
  tags: k3s

- name: Disable k3s service to avoid auto-start
  ansible.builtin.systemd_service:
    name: k3s-agent
    enabled: false
    state: stopped
  when: (inventory_hostname in groups['agents']) or (inventory_hostname in groups['longhorns'])
  tags: k3s
