---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: configarr
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/radarr
      recursive: false
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/sonarr
      recursive: false
  targets:
    - name: configarr-secret
      namespace: media
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          RADARR_API_KEY: "{{ .RADARR_API_KEY.Value }}"
          SONARR_API_KEY: "{{ .SONARR_API_KEY.Value }}"