---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: searxng
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/utilities/searxng
      recursive: false
  targets:
    - name: searxng-secret
      namespace: utilities
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          SEARXNG_SECRET: "{{ .SEARXNG_SECRET.Value }}"