apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-peer
  namespace: arr
  annotations:
    lbipam.cilium.io/ips: "10.1.20.156,10.1.42.156"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: qbittorrent
  ports:
    - name: bittorrent-tcp
      port: 65211
      targetPort: bittorrent-tcp
      protocol: TCP
    - name: bittorrent-udp
      port: 65211
      targetPort: bittorrent-udp
      protocol: UDP