---
- name: Install SELinux policies for cilium cilium_selinux.te
  ansible.builtin.copy:
    src: cilium_selinux.te
    dest: /tmp/cilium_selinux.te
    owner: root
    group: root
    mode: "0644"
  tags: selinux

- name: Compile SELinux module for cilium
  ansible.builtin.command:
    cmd: checkmodule -M -m -o /tmp/cilium_selinux.mod /tmp/cilium_selinux.te
  changed_when: true
  tags: selinux

- name: Package SELinux module for cilium
  ansible.builtin.command:
    cmd: semodule_package -o /tmp/cilium_selinux.pp -m /tmp/cilium_selinux.mod
  changed_when: true
  tags: selinux

- name: Install SELinux module for cilium
  ansible.builtin.command:
    cmd: semodule -i /tmp/cilium_selinux.pp
  changed_when: true
  become: true
  tags: selinux

- name: Install Cilium
  when: inventory_hostname == groups['servers'][0]
  tags: cilium
  block:
    # - name: Install helm chart
    #   kubernetes.core.helm:
    #     name: cilium
    #     chart_ref: cilium
    #     chart_repo_url: "{{ cilium_repo_url }}"
    #     chart_version: "{{ cilium_version }}"
    #     release_namespace: "{{ cilium_namespace }}"
    #     values: "{{ cilium_values }}"

    - name: Create temporary Cilium values file
      ansible.builtin.copy:
        content: "{{ cilium_values | to_nice_yaml }}"
        dest: /tmp/cilium-values.yaml
        owner: root
        group: root
        mode: "0644"

    - name: Install helm chart
      ansible.builtin.command:
        cmd: >
          helm upgrade --install cilium cilium
          --repo {{ cilium_repo_url }}
          --version {{ cilium_version }}
          --namespace {{ cilium_namespace }}
          --values /tmp/cilium-values.yaml
          --kubeconfig {{ kubeconfig_path }}
      changed_when: true

    - name: Wait for Cilium CRDs # noqa: var-naming
      kubernetes.core.k8s_info:
        kind: CustomResourceDefinition
        name: "{{ item }}"
      loop:
        - ciliuml2announcementpolicies.cilium.io
        - ciliumloadbalancerippools.cilium.io
      register: crd
      until: crd.resources is defined and crd.resources | length > 0
      retries: 10
      delay: 10

    - name: Apply Cilium resources
      kubernetes.core.k8s:
        template: "{{ item }}"
      loop:
        - ciliuml2announcementpolicy.yaml
        - ciliumloadbalancerippool.yaml
