---
working_dir: ./compose/hetzner
auto_discovery:
  enabled: true
  depth: 1
  delete: true
external_secrets:
  CADDY_ACME_EMAIL: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/vps/towonel/TOWONEL_ACME_EMAIL
  TOWONEL_INVITE_HASH_KEY: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/vps/towonel/TOWONEL_INVITE_HASH_KEY
force_recreate: false
reconciliation:
  enabled: true
  interval: 3600
