---
- name: Ensure periphery_keys volume exists
  containers.podman.podman_volume:
    name: periphery_keys
    state: present

- name: Get periphery_keys mountpoint # noqa: jinja[spacing]
  ansible.builtin.command: "podman volume inspect periphery_keys --format {{'{{.Mountpoint}}'}}"
  register: periphery_keys_mp_cmd
  changed_when: false

- name: Wait for periphery.pub to exist
  ansible.builtin.wait_for:
    path: "{{ periphery_keys_mp_cmd.stdout }}/periphery.pub"
    timeout: 120

- name: Read periphery.pub
  ansible.builtin.slurp:
    src: "{{ periphery_keys_mp_cmd.stdout }}/periphery.pub"
  register: periphery_pub_slurp

- name: Save periphery public key as a fact
  ansible.builtin.set_fact:
    komodo_periphery_public_key: "{{ periphery_pub_slurp.content | b64decode }}"
    cacheable: true
