---
- name: Block storage setup on hosts with media=true
  when: hostvars[inventory_hostname].media | default(false) | bool
  tags: nfs
  block:
    - name: Ensure media directory exists
      ansible.builtin.file:
        path: "{{ media_data_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Mount NFS share
      ansible.builtin.mount:
        src: "{{ media_host }}:{{ media_path }}"
        path: "{{ media_data_dir }}"
        fstype: nfs
        opts: "{{ mount_options }}"
        state: mounted
      when: media_host is defined
        and media_path is defined

    - name: Allow containers to use NFS (SELinux)
      ansible.posix.seboolean:
        name: virt_use_nfs
        state: true
        persistent: true
      tags: selinux
