---
name: towonel-agent
services:
  app:
    image: codeberg.org/towonel/towonel-agent:1.13.0@sha256:03b08ff62f8bb5f659635d371a0682129028fb10deaf7f8df8d1aca8497ad6c8
    container_name: towonel_agent_1
    environment:
      RUST_LOG: info
      TOWONEL_INVITE_TOKEN: ${TOWONEL_INVITE_TOKEN}
      TOWONEL_AGENT_HEALTH_LISTEN_ADDR: 127.0.0.1:19090
      TOWONEL_AGENT_SERVICES: |
        [
          {"hostname":"calendar.eudald.gr","origin":"127.0.0.1:20003","proxy_protocol":"none"},
          {"hostname":"contacts.eudald.gr","origin":"127.0.0.1:25556","proxy_protocol":"none"},
          {"hostname":"drive.eudald.gr","origin":"127.0.0.1:10003","proxy_protocol":"none"},
          {"hostname":"photos.eudald.gr","origin":"127.0.0.1:5443","proxy_protocol":"none"}
        ]
      TOWONEL_AGENT_TCP_SERVICES: |
        [
          {"name":"synology-drive-client","origin":"127.0.0.1:6690","listen_port":6690,"proxy_protocol":"none"}
        ]
    network_mode: host
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
