# cloud-config
hostname: ${hostname}
timezone: ${timezone}

# Create users
users:
  - name: ${ciuser}
    groups: [sudo, systemd-journal, users]
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_authorized_keys}

power_state:
  mode: reboot
  timeout: 30
  condition: true
