[[stack]]
name = "newt-ds920plus"
description = "Stack Newt"
deploy = true

[stack.config]
server_id = "ds920plus"
linked_repo = "homelab"
run_directory = "compose/ds920plus/prod/newt"
auto_pull = true
send_alerts = true

compose_cmd_wrapper = """
/opt/sops exec-env compose.env '[[COMPOSE_COMMAND]]'"""