---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: tautulli
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/tautulli
      recursive: false
  targets:
    - name: tautulli-secret
      namespace: media
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY.Value }}"