public-resources:
  sso:
    name: sso
    protocol: http
    full-domain: sso.eudald.gr
    auth:
      sso-enabled: false
    targets:
      - hostname: authentik-server.auth.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: authentik-server.auth.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /-/health/ready/
          method: GET

  argocd:
    name: argocd
    protocol: http
    full-domain: argocd.eudald.gr
    auth:
      sso-enabled: true
    targets:
      - hostname: argocd-server.argocd.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: argocd-server.argocd.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /healthz
          method: GET

  radarr:
    name: radarr
    protocol: http
    full-domain: radarr.eudald.gr
    auth:
      sso-enabled: true
    rules:
      - action: allow
        match: path
        value: /api/*
    targets:
      - hostname: radarr.arr.svc.cluster.local
        port: 7878
        method: http
        healthcheck:
          hostname: radarr.arr.svc.cluster.local
          port: 7878
          mode: http
          scheme: http
          path: /
          method: GET

  sonarr:
    name: sonarr
    protocol: http
    full-domain: sonarr.eudald.gr
    auth:
      sso-enabled: true
    rules:
      - action: allow
        match: path
        value: /api/*
    targets:
      - hostname: sonarr.arr.svc.cluster.local
        port: 8989
        method: http
        healthcheck:
          hostname: sonarr.arr.svc.cluster.local
          port: 8989
          mode: http
          scheme: http
          path: /
          method: GET

  lidarr:
    name: lidarr
    protocol: http
    full-domain: lidarr.eudald.gr
    auth:
      sso-enabled: true
    rules:
      - action: allow
        match: path
        value: /api/*
    targets:
      - hostname: lidarr.arr.svc.cluster.local
        port: 8686
        method: http
        healthcheck:
          hostname: lidarr.arr.svc.cluster.local
          port: 8686
          mode: http
          scheme: http
          path: /
          method: GET

  prowlarr:
    name: prowlarr
    protocol: http
    full-domain: prowlarr.eudald.gr
    auth:
      sso-enabled: true
    targets:
      - hostname: prowlarr.arr.svc.cluster.local
        port: 9696
        method: http
        healthcheck:
          hostname: prowlarr.arr.svc.cluster.local
          port: 9696
          mode: http
          scheme: http
          path: /
          method: GET

  qbittorrent:
    name: qbittorrent
    protocol: http
    full-domain: torrent.eudald.gr
    auth:
      sso-enabled: true
    targets:
      - hostname: qbittorrent.arr.svc.cluster.local
        port: 8080
        method: http
        healthcheck:
          hostname: qbittorrent.arr.svc.cluster.local
          port: 8080
          mode: http
          scheme: http
          path: /
          method: GET

  seerr:
    name: seerr
    protocol: http
    full-domain: seerr.eudald.gr
    targets:
      - hostname: seerr.arr.svc.cluster.local
        port: 5055
        method: http
        healthcheck:
          hostname: seerr.arr.svc.cluster.local
          port: 5055
          mode: http
          scheme: http
          path: /
          method: GET

  tautulli:
    name: tautulli
    protocol: http
    full-domain: tautulli.eudald.gr
    rules:
      - action: allow
        match: path
        value: /api/*
    targets:
      - hostname: tautulli.arr.svc.cluster.local
        port: 8181
        method: http
        healthcheck:
          hostname: tautulli.arr.svc.cluster.local
          port: 8181
          mode: http
          scheme: http
          path: /
          method: GET

  plex:
    name: plex
    protocol: http
    full-domain: plex.eudald.gr
    targets:
      - hostname: plex.arr.svc.cluster.local
        port: 32400
        method: http
        healthcheck:
          hostname: plex.arr.svc.cluster.local
          port: 32400
          mode: http
          scheme: http
          path: /identity
          method: GET

  jellyfin:
    name: jellyfin
    protocol: http
    full-domain: jellyfin.eudald.gr
    targets:
      - hostname: jellyfin.arr.svc.cluster.local
        port: 8096
        method: http
        healthcheck:
          hostname: jellyfin.arr.svc.cluster.local
          port: 8096
          mode: http
          scheme: http
          path: /health
          method: GET

  bentopdf:
    name: bentopdf
    protocol: http
    full-domain: pdf.eudald.gr
    targets:
      - hostname: bentopdf.bentopdf.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: bentopdf.bentopdf.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  searxng:
    name: searxng
    protocol: http
    full-domain: searx.eudald.gr
    targets:
      - method: http
        hostname: searxng.searxng.svc.cluster.local
        port: 8080
        healthcheck:
          enabled: true
          hostname: searxng.searxng.svc.cluster.local
          port: 8080
          path: /healthz
          headers:
            - name: X-Real-IP
              value: 127.0.0.1

  memos:
    name: memos
    protocol: http
    full-domain: memos.eudald.gr
    auth:
      sso-enabled: true
    rules:
      - action: allow
        match: path
        value: /api/*
      - action: allow
        match: path
        value: /assets/*
      - action: allow
        match: path
        value: /explore*
      - action: allow
        match: path
        value: /memos.api.v1.*
      - action: allow
        match: path
        value: /auth/callback*
      - action: allow
        match: path
        value: /auth
      - action: allow
        match: path
        value: /site.webmanifest
      - action: allow
        match: path
        value: /logo.webp
      - action: allow
        match: path
        value: /full-logo.webp
      - action: allow
        match: path
        value: /android-chrome-192x192.png
    targets:
      - hostname: memos.memos.svc.cluster.local
        port: 5230
        method: http
        healthcheck:
          hostname: memos.memos.svc.cluster.local
          port: 5230
          mode: http
          scheme: http
          path: /
          method: GET

  it-tools:
    name: it tools
    protocol: http
    full-domain: tools.eudald.gr
    targets:
      - hostname: it-tools.it-tools.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: it-tools.it-tools.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  kromgo:
    name: kromgo
    protocol: http
    full-domain: badges.eudald.gr
    targets:
      - hostname: kromgo.kromgo.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: kromgo.kromgo.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /readyz
          method: GET

  minecraft-java:
    name: minecraft java
    mode: tcp
    proxy-port: 25565
    targets:
      - hostname: minecraft.minecraft.svc.cluster.local
        port: 25565

  minecraft-bedrock:
    name: minecraft bedrock
    mode: udp
    proxy-port: 19132
    targets:
      - hostname: minecraft.minecraft.svc.cluster.local
        port: 19132
