public-resources:
  flux-webhook:
    name: flux webhook
    protocol: http
    full-domain: flux-webhook.eudald.gr
    auth:
      sso-enabled: false
    targets:
      - hostname: webhook-receiver.flux-system.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: webhook-receiver.flux-system.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET
          status: 404

  radarr:
    name: radarr
    protocol: http
    full-domain: radarr.eudald.gr
    auth:
      sso-enabled: true
    rules:
      - action: allow
        match: path
        value: /api/*
    targets:
      - hostname: radarr.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: radarr.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  sonarr:
    name: sonarr
    protocol: http
    full-domain: sonarr.eudald.gr
    auth:
      sso-enabled: true
    rules:
      - action: allow
        match: path
        value: /api/*
    targets:
      - hostname: sonarr.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: sonarr.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  lidarr:
    name: lidarr
    protocol: http
    full-domain: lidarr.eudald.gr
    auth:
      sso-enabled: true
    rules:
      - action: allow
        match: path
        value: /api/*
    targets:
      - hostname: lidarr.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: lidarr.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  prowlarr:
    name: prowlarr
    protocol: http
    full-domain: prowlarr.eudald.gr
    auth:
      sso-enabled: true
    targets:
      - hostname: prowlarr.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: prowlarr.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  qbittorrent:
    name: qbittorrent
    protocol: http
    full-domain: torrent.eudald.gr
    auth:
      sso-enabled: true
    targets:
      - hostname: qbittorrent.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: qbittorrent.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  seerr:
    name: seerr
    protocol: http
    full-domain: seerr.eudald.gr
    targets:
      - hostname: seerr.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: seerr.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  tautulli:
    name: tautulli
    protocol: http
    full-domain: tautulli.eudald.gr
    rules:
      - action: allow
        match: path
        value: /api/*
    targets:
      - hostname: tautulli.media.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: tautulli.media.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  plex:
    name: plex
    protocol: http
    full-domain: plex.eudald.gr
    targets:
      - hostname: plex.media.svc.cluster.local
        port: 32400
        method: http
        healthcheck:
          hostname: plex.media.svc.cluster.local
          port: 32400
          mode: http
          scheme: http
          path: /identity
          method: GET

  bentopdf:
    name: bentopdf
    protocol: http
    full-domain: pdf.eudald.gr
    targets:
      - hostname: bentopdf.bentopdf.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: bentopdf.bentopdf.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  searxng:
    name: searxng
    protocol: http
    full-domain: searx.eudald.gr
    targets:
      - method: http
        hostname: searxng.searxng.svc.cluster.local
        port: 8080
        healthcheck:
          enabled: true
          hostname: searxng.searxng.svc.cluster.local
          port: 8080
          path: /healthz
          headers:
            - name: X-Real-IP
              value: 127.0.0.1

  vaultwarden:
    name: vaultwarden
    protocol: http
    full-domain: bitwarden.eudald.gr
    auth:
      sso-enabled: false
    rules:
      - action: deny
        match: path
        value: /admin
      - action: deny
        match: path
        value: /admin/*
    targets:
      - hostname: vaultwarden-0.vaultwarden.vaultwarden.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: vaultwarden-0.vaultwarden.vaultwarden.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /alive
          method: GET

  memos:
    name: memos
    protocol: http
    full-domain: memos.eudald.gr
    auth:
      sso-enabled: true
    rules:
      - action: allow
        match: path
        value: /api/*
      - action: allow
        match: path
        value: /assets/*
      - action: allow
        match: path
        value: /explore*
      - action: allow
        match: path
        value: /memos.api.v1.*
      - action: allow
        match: path
        value: /auth/callback*
      - action: allow
        match: path
        value: /auth
      - action: allow
        match: path
        value: /site.webmanifest
      - action: allow
        match: path
        value: /logo.webp
      - action: allow
        match: path
        value: /full-logo.webp
      - action: allow
        match: path
        value: /android-chrome-192x192.png
    targets:
      - hostname: memos.memos.svc.cluster.local
        port: 5230
        method: http
        healthcheck:
          hostname: memos.memos.svc.cluster.local
          port: 5230
          mode: http
          scheme: http
          path: /
          method: GET

  it-tools:
    name: it tools
    protocol: http
    full-domain: tools.eudald.gr
    targets:
      - hostname: it-tools.it-tools.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: it-tools.it-tools.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /
          method: GET

  kromgo:
    name: kromgo
    protocol: http
    full-domain: kromgo.eudald.gr
    targets:
      - hostname: kromgo.o11y.svc.cluster.local
        port: 80
        method: http
        healthcheck:
          hostname: kromgo.o11y.svc.cluster.local
          port: 80
          mode: http
          scheme: http
          path: /readyz
          method: GET

  minecraft-java:
    name: minecraft java
    mode: tcp
    proxy-port: 25565
    targets:
      - hostname: minecraft.minecraft.svc.cluster.local
        port: 25565

  minecraft-bedrock:
    name: minecraft bedrock
    mode: udp
    proxy-port: 19132
    targets:
      - hostname: minecraft.minecraft.svc.cluster.local
        port: 19132
