apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-cache
  namespace: llama-cpp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-csi
  resources:
    requests:
      storage: 20Gi
