---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: cloudflare-dns
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/cloudflare
      recursive: false
  targets:
    - name: cloudflare-dns-secret
      namespace: network
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          CF_API_TOKEN: "{{ .CLOUDFLARE_DNS_TOKEN.Value }}"
          CF_ZONE_ID: "{{ .CLOUDFLARE_ZONE_ID.Value }}"
