secret_pangolin_domain: ENC[AES256_GCM,data:Zb9MnUPURO/0h3VG35xtYBEm,iv:HmKdKx+AUx2nvzFj/4iyyMXff1h42xvxCiK6fTslin8=,tag:CP6RChhKra/R2/Sad1nhUQ==,type:str]
secret_base_domains:
  - ENC[AES256_GCM,data:gi5x+Q4kpS9l,iv:uJGD2nWEAY4w4SBkYuJistDn7vbX3mzkEZ2mTUxPZXg=,tag:gQxgORD4vh3JthvlJdp/+w==,type:str]
secret_pangolin_email: ENC[AES256_GCM,data:v4ZzMw==,iv:1Cdq6wGB/L1BkHqkstvAxObkIQYWHrOxGuLq8GfdXXI=,tag:OmPwz/qSK+B3FMc0uqCG+Q==,type:bool]
secret_pangolin_smtp_host: ENC[AES256_GCM,data:ri2zysQ2LU3HMmsJYKvdgA==,iv:de6yGigf2nYp76Hly25wCiAUfOGNoy3ZVGo5oibnNxM=,tag:NrnFD/cWy8D2uzkxPP7brg==,type:str]
secret_pangolin_smtp_port: ENC[AES256_GCM,data:vg74,iv:pVPnCSRz2ZL2W1WNBDQkZxahJguwMGsArrMXantlBsI=,tag:Mm5bw/R0hgb+eu1jHTwBcw==,type:int]
secret_pangolin_smtp_user: ENC[AES256_GCM,data:vp/fPzhh+On4LGC31J9G+A==,iv:3aSUDY7W3iouA/GECfmKw/xisLPxhDzPNm2RvwF8eG4=,tag:Z7MtQ6f4Q3F3i+7Fi8pJAA==,type:str]
secret_pangolin_smtp_pass: ENC[AES256_GCM,data:kFJvjPlfbUH2iWesll0+hiAo1MGfvGjyuLjMDQjbcilq5YOBer69+H3gse2f8E97Vg3lzPRT2BolUdTNe6DUAA==,iv:NkcR/NchAMmA3UhwlPjck83jla769R6tzFW8D++YGH4=,tag:Fgq1791+sw8II5Y6e44NqQ==,type:str]
secret_pangolin_smtp_secure: ENC[AES256_GCM,data:q0Dxvg==,iv:4erff6kLj39O+xMdGXh/klmeE/Wjq/oUso7ChNERyO4=,tag:mIjTKnDgKVHdGGOxz0Iwtg==,type:bool]
secret_pangolin_smtp_no_reply_email: ENC[AES256_GCM,data:cCtjCdnWM2+6+OL7zi1fkvE=,iv:GYsdosxLennGH397Agt5fLwSGt8A3ojdUhFjDBZ+A4M=,tag:F3464YVsS5SCk7GIN9wo+A==,type:str]
secret_pangolin_traefik_letsencrypt_mail: ENC[AES256_GCM,data:2QXU1PwySKmh3pnC,iv:/Bhw9YyRTQ1XR1MMbQTO2hfNc0i4bWYvJZqERj/L57o=,tag:SHeIFeLrsXc9EnJr5/OICw==,type:str]
secret_pangolin_server_secret: ENC[AES256_GCM,data:auMHU+EKQDVqe9r8iyW6qDfb5/yHmfkR81WHi18mtNvbobufW76cQVifincyUaAVaz5EWY2qkgezpBNld+6pnw==,iv:hs+XnJhRlrx0BkzvlwxVa+inJwIpWC7ii4JRDIq9xnw=,tag:V1YFzhpgK6mMdcF3Ozpj2w==,type:str]
secret_pangolin_crowdsec_lapi_key: ENC[AES256_GCM,data:k6FvxxLGV8NaCSFbKdQCs+V6ELJiZ+VeSQ==,iv:+I0LsQrhBCOqvceos71to/jfMaDvdG42XXPhMS9U3Mw=,tag:oaiGy0f4ZJbonrojVrub1A==,type:str]
sops:
  age:
    - recipient: age1yfrq96mwj6ah0szswj9a8vg8jmyzwl5g6w5u8fh23yg85saxyunss056hg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaFhibExVTUJ2SWZNUTEy
        UkxTV2t5TUpKU3JPUmx3SytGc3U2RU1Hbnc4ClpNbzRsOUdUaVhPNXJFS0lleEoy
        TWJrNmRBRW9VZkhKeExKM3k3dXhhM2cKLS0tIEZwSGt6SFdaL1JaaDI1aEowMFpa
        eHZoMFBoZnZUd0NaRGpMKzNBNVZUYm8Km7DUpgoEgNNpwJ+9r5Wi5qisAjtD9jFe
        5HFiYwxZsiamwadJGHpkjS+ZU9mOrgmuuYq3Ls75WD+SUGVCM094PQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age175lfmhlkmu8qu07dkxsau62v4vfdczejr66xvf9peg733rrth44shlz5zq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRnNEVEVWQlg0NjkvUGlH
        eDEyajYyeEpyMEF6dDMrRlArRzF5b3RreUZrCmlVSndJNzlTcjNSWnpWWmd0R3Uv
        d1ZGL1NsWVYyN01zcjRleUZvVGNjS3cKLS0tIGc4OVhnL0toYXYrRktIa1lLcXIr
        dy9oSWFncWJwSkxFc2FWV2VCY2pubkkKwtZJyzp0eJPTm/W3iOGNnqKPugIaTBux
        8eLHOJKiqVT95LrzPWLFpvZt9yqlegciA8o1AA4AlfTRT7sgMRYRog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T16:00:54Z"
  mac: ENC[AES256_GCM,data:RY+1oL4erYO2tB6j+E8eycRq3SoWYR0ZdL3dNuB6EmmQ7AzGOJsJ6Xez1Y/jX6sWOB+SHVRmTmTrT4apstStRoSH4d21Yhf9TGGz5vYwkZpJuGEfMAX9InCrFaL6H+krEQ12m4PS1oxgERpEAYD0cT5ar/yx85cyGitnIZLnZNs=,iv:UezP95JoyeQsdRY0adJ1HK/HPvlCYWUr/EUWTr0duBM=,tag:uobT0mBjUTxeAeQ8GRNJ/w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
