secret_pangolin_domain: ENC[AES256_GCM,data:b7VEBfHUtNN1aeBvLFyN1LlD,iv:10FZfKiM/KrLzTNeKaUTkrg1S3YQnA2acUGIJ2tepeE=,tag:ExBcSx/Ok9LL9AUeCDxCQg==,type:str]
secret_base_domains:
  - ENC[AES256_GCM,data:4gopgM0nMypB,iv:D+/tYTOudHCp8aGFmTs7yQX8cOTAkcCLaeMntjnEii8=,tag:HWOJce++wyeJ6QIEzzVwIA==,type:str]
secret_pangolin_email: ENC[AES256_GCM,data:dpFceQ==,iv:2RYC/EJq6rzDahDfbIaE1MkneC2fA6XZkCJ/Pu9hS7I=,tag:uLyKwkOvEnxtGpdNXTCyiQ==,type:bool]
secret_pangolin_smtp_host: ENC[AES256_GCM,data:nJcwhTpwhYoI7Wlo3ThDPg==,iv:NnGWLxipkhUSxftjUX0UuXaGJsU04kiuKHUFjNk+tWY=,tag:mld3dlv2JTxUjfGI4hwIQw==,type:str]
secret_pangolin_smtp_port: ENC[AES256_GCM,data:lxBV,iv:ObsP2jXgDr8Sn9ZYTS48576Z3klzS8IVAOmalO9DxE4=,tag:GZcWn9S/rdojlNyWPDaojw==,type:int]
secret_pangolin_smtp_user: ENC[AES256_GCM,data:Z1M0bZKawN1ezXls8TNCIg==,iv:WXCEUPeVQJkLjSqUJjodhCHkxpZZIb+wsoI3hEkJH6Q=,tag:QuIm9Un1PbLaWoelOTy7mQ==,type:str]
secret_pangolin_smtp_pass: ENC[AES256_GCM,data:dTo3AM1TH+5C1zSV0MoVMhztMlTJUD4p3bzZ4nssHDC3FjLBpCiU/rI1la2B9eEJKxSLUwOGZ2TMajM8yrcLjg==,iv:sLKCYL/1H7sdejlifAT03BMErdQk3OzNEQU4ZipirB8=,tag:ftmZt/bwc5nh/2MOUyeQvQ==,type:str]
secret_pangolin_smtp_secure: ENC[AES256_GCM,data:EAnfAw==,iv:Q8pQHoChgyu6n9qUC00hkIgS2BNXRzTV3LOrM8jF7ck=,tag:4KkgDi7tV3WMl5wKBD9diQ==,type:bool]
secret_pangolin_smtp_no_reply_email: ENC[AES256_GCM,data:IA0iT+0iRms/mJ/nuVXwH8o=,iv:iV7J4RZKxBwCz9D8jno7ZcO+w3sIp/mYyYna2q81cjc=,tag:a4SS2rFMjZLUGJs82zKWoA==,type:str]
secret_pangolin_traefik_letsencrypt_mail: ENC[AES256_GCM,data:Fd4eZochz5/rH8mh,iv:tPi7ob+rvJO+li7y/y5OsU+2KXgkCMkrsCmGEvej5QM=,tag:J9ixBtJvRRnd1h1QsLdK3Q==,type:str]
secret_pangolin_server_secret: ENC[AES256_GCM,data:Zwidn4Afsv1hcap0iDVjKgN/4Bj9hqnpN5WwgaGit+/uqhR6jI/frqYDvDP6ZRIh/79skLAYApOA+OxD3Zp1AQ==,iv:uF7V236J6XDRBm6yihs8qmfo+2tEF4WxjmierhYsRp0=,tag:ErPIAL2FNZKZCZJn/IyKyw==,type:str]
secret_pangolin_crowdsec_lapi_key: ENC[AES256_GCM,data:efjnIAPdGU7MhXDyhhn8lhVtdSkCSRTebw==,iv:xpQg8I9VSMDaeQ+Yiddzp3XIJRMxJjASGI2RNH3DFro=,tag:zvpcm45xAMpfj2TvBAjBZA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUVFyOC8xS3dLa3FaaHdI
        Mng2bHUrUHFOWFBmUE05M0cyWHJkT1JtSWhrCmN6YXFDUVdGOEw3V1JyUUl1L3pq
        clJ5aVFwWHYxZTJFM0pXQXV3RVRGU00KLS0tIGdIYTFzZ1FCSG4xME1wMllsVmtC
        Sm1VV3Y5bFR3azdJM1FraElGMElyekEKdqTo4FPWOIXfabYTl18Bii41KjLtKVgO
        eiMFQEdlWkccLbwG9dj82q76gEyQ+xCCiR4OnN+K4RK4Dw1oaV1BBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yfrq96mwj6ah0szswj9a8vg8jmyzwl5g6w5u8fh23yg85saxyunss056hg
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpb2ltWEhzTFBLVnprYmg4
        N3RVdEhQSUo2REJSREpWTkdsdUV5Ykg5U1hFCnVsVjNsSEQ2cWNiMkU5cHZTMnFM
        UmUrRzJ1bTI0ZThyWEd6eGlQL2cxeGMKLS0tIGMvc2NlSlNUUXd6cUVUaGNqWDhx
        cXR6bWJtYmkyMzlqVlZLWU9CRlZtUVUKH194HTJ7dc1BEY7EKqoKaJ3jxDsKgNAl
        ileCj1q++fBlykvjBkeNrrnFoc+YjI/4/38kEb8wPpY4G2cUs+jcTg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age175lfmhlkmu8qu07dkxsau62v4vfdczejr66xvf9peg733rrth44shlz5zq
  lastmodified: "2026-05-10T20:00:13Z"
  mac: ENC[AES256_GCM,data:PMDzBHJSwtJaza//VVekyX62qc/5qFXxNpATIafRoBcEBHELq15GFs4I0zQekSM+L1EYMySy20bsrP5UCpr529YOvNAuxcyw5Mc4nuuOeB3XQ8JunqLT8Gn5Qwd9PQcegi0C58RX7UC78B2Qr3vHk0rfsoSamHR3KvsL4Dnj27w=,iv:TIQsnuFacicoc16bGXRgSm3EeZ3VuCBKY0NfUY1eFRM=,tag:q9CKPnXKdWldww2Yr9j3Lw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.0
