secret_media_host: ENC[AES256_GCM,data:6mqOpo/MriS8lA==,iv:UIlZhG2Vp/w5/UuuSXotVvS3lIFsiwzNuhy0uQKz754=,tag:Oqmz7rOBZSQhyxGihW2W4A==,type:str]
secret_media_path: ENC[AES256_GCM,data:lLYEkAYvxgg8h+em4g==,iv:5MMZwg2l/gpLpyQT5OnYuWq4YcHM6uP6Gm++8liJeII=,tag:fvtIMAhIz/EQyLXY74IOqQ==,type:str]
secret_komodo_core_1_jwt: ENC[AES256_GCM,data:p8Og/MpiNvJE82rsjqXyk1V2QTgrPhF7ilgDSQFuJmo=,iv:PhueM2P6fYJACsyZMLL+V5FUTFqyFpHbyMXGsiOvkVo=,tag:PzSITzG9q1pBS6IX6VhdDQ==,type:str]
secret_komodo_core_1_webhook_secret: ENC[AES256_GCM,data:M+KiPnb90JJUK1epDPFsR4DrgS1Gh6V3M+6OH91J7R0=,iv:SDrapHG070ooAHBOkFSKNvLu7OUKeRME6EnI5hD6xGA=,tag:eS7MqQnHclztuwtNy2IxOQ==,type:str]
secret_komodo_mongo_1_passwd: ENC[AES256_GCM,data:K94iYSS5VTE4KK3AHQ3uVv7oKNGV2tC1n+KliPQ//Gs=,iv:+4DKGGObVGiYh85OEO11ahmTm4hEVH3p4CxOyArtDjc=,tag:/UKh5EOlOluVHQA4imDn8w==,type:str]
secret_extra_periphery_pub_keys:
  ds920plus: ENC[AES256_GCM,data:bDKurB1g9bLLrEhBaqC2KiKEYwshFg7FLuOKZkApIw3e6mEz27Xh8P6dJ3HDYObXgEqqIMzWgi8W7HbN,iv:k4OgDoguFDiC4/R2BkoTmxNFadbMAktxDi0m2cgpVE8=,tag:sARnfm+Vq420ZZvhMQz/mw==,type:str]
sops:
  age:
    - recipient: age1yfrq96mwj6ah0szswj9a8vg8jmyzwl5g6w5u8fh23yg85saxyunss056hg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRHRmSXZ3K1IrTTFhYm9V
        Mzd2Zjl4S2sxQjEvcDVvZ1ppT05KdHpNRkZzCjQzQzVBVEFkV3ZDOCtnNURpVE13
        Qmc4NTE4aGF1c2VJVGs3Y0Fic1g3dUEKLS0tIFlmS2VMdmh4UDlIQ1NIQ254T3NH
        WDJnTnpXZVRZcDhLY0daYnIyeVV6L3MKQn9AjGyk2S9pWl52FLKeStX3Nkt3cXqY
        c7neDWik29hcUmOrjLInu4F2Z9Xx1cZPi32pp7gsFsLlhTbV0c9apA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1vgqjvj49eftfalvhpefvnr4rnrqa4cl28lye4pcsw2638jg0hywqg6l0je
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UHZteC9IMEVsanZLQmhJ
        N1IwSWV0Q3ZjcXA4N0NIMHdUakI3eWhCYlJvCjFRaEE5M0RmZDl0WFFjbzIyZDNq
        RTlVRUN5b2U3cElVUWxEWjB0d2hsaVEKLS0tIGhPNlZsNXZtclRSYXU1K3NSS0N5
        emlQZTJ0VklIc0FtQ2JFYldmVzQ2WkUKHB6Trhq+bPxJ1m4Vbhnn/Avepo/EikXL
        1G80MBXZ24o+EkKGuiHja8IH/T2PaAntjQwdcnRg8FyS1YNThUfx7g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age175lfmhlkmu8qu07dkxsau62v4vfdczejr66xvf9peg733rrth44shlz5zq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwV2hUOVQ3SnovbFZGZHlp
        ODlod0o5VFpwRmZUS1kxbEhxcTRUc0Q2a2k4ClkyY2hNZzczQS9Edk5GMjZZcGgv
        ZDBIV25mSFozNi9sNi84MGl5Y2VIZk0KLS0tIEpzNVpSSmxMZFRvaVhZbVEzOWNL
        U1RGY05zdHJkWVlQVUc3WUE5Q1FOWXcKWQXEll5TkM0HDQAEJJwehMmQB4LTOmxc
        spDZW9NFnVX/ZS1UbxusNiy9kMtzDefppQnUdkvOX3tbaRAMLiUXpg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T12:45:58Z"
  mac: ENC[AES256_GCM,data:5MyOi1BHIuryAMhIe+LsuR5p3/l1ONSIyrH0PPIRVUXOOSynU0gEqxCDkI9E7qzRCssiwk7iOeR3buq+VDYZAHa54liXgjymuXlwdl7tu5pjxHwZv/WYTYkUmv7IoiJholIoIGrrltw0Upp0DbhH6mbKCXJjnGsLd/eKa0iMkkI=,iv:whTKZl1xHbNLucAbPj3HjxVbfh2cbWXgDxibWiKZxcc=,tag:+Tv5fNTqhzy6YQFssGzyew==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
