[[stack]]
name = "newt-host02"
description = "Stack Newt"
deploy = true
tags = ["host02", "prod"]

[stack.config]
server_id = "host02"
linked_repo = "homelab-host02"
run_directory = "compose/host02/prod/newt"
auto_pull = true
send_alerts = true

compose_cmd_wrapper = """
/opt/sops exec-env compose.env '[[COMPOSE_COMMAND]]'"""