---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ha-mcp-secrets
  namespace: home-assistant
spec:
  encryptedData:
    HOMEASSISTANT_TOKEN: AgClSvRQRqr2IZR9FN+zh5aCZEATTuulxena2sN89tFWFfnNNH0yV+wPkYLloKUC3RVvFE82Wqz5+KrN0CZyjbFGV90fX5Yji7jBwUmgLeU+6oL7YUkfPgJVMy8AlIsrLI43rT8rgtznG3k90klK35d1qTZ3qOJ9lMdGdFTNY38jsDSrOkltFL2Ku1OCX5+BoIBvFrmI4jbKCmTA9F2Wm1Jtvps+brN/gxZY/1qbYxmwm+AwJT4PLagu9AxTG6dI6A2TCOm8INE84wOHYQ+jyGNzX1txLPAm0xs1taCilWkDkrRlIL/9PC0Y3iuQbztZvrTAVHbOoi2FQli0tXexSXf8hfk+VGI+E22az557qlU2AFCYo5Mi9DtVT5K5UmG0BMJQVGA36vGdrwEJt+eq6TRivbWfb0f8J3Mr7HB+y/XKoFGQbQ+wuaPTrNePdKh/2SBfneyi73dTrxOznoZ8KQlkFWbqFNHHy5FPQt8e8gJJio08LTDHncE4b9xny0XMOoDJtMHMTLiGSSWLaLZ2t+zPp83fURWAVqbLhq5sHB0PTQOPPYMmCJraMT5hxggJTmTvj4RkJ/T7FhPaUFfhXUfg4ZTIamf+8vfV+d69aAVqdfZAGyruEaOs0k9MMJNVNOdkeHv5gFSXSnnY8iiz2gnbaCL2qaTHCqbDEk4loDHWOSuf22TLZegFZw4+syReh4WRiLDZDQCUhBOTiOFr+EwtbzOP3gY44wwLoVK0baEroBH72G09xQSjSyv0TTK379L6cgLVtJvhIAVQJ1BP89Y5
  template:
    metadata:
      name: ha-mcp-secrets
      namespace: home-assistant
