---
- name: Assegurar que els directoris necessaris existeixen
  ansible.builtin.file:
    path: "{{ dir_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/containers/systemd
    - /etc/komodo
  loop_control:
    loop_var: dir_path
  tags: podman

- name: Copiar quadlet Komodo Periphery
  ansible.builtin.template:
    src: "{{ role_path }}/templates/komodo_periphery_1.container.j2"
    dest: "/etc/containers/systemd/komodo_periphery_1.container"
    owner: root
    group: root
    mode: "0644"
  register: komodo_periphery_quadlet
  tags: komodo

- name: Copiar fitxers Komodo (network)
  ansible.builtin.copy:
    src: "{{ role_path }}/files/komodo.network"
    dest: "/etc/containers/systemd/komodo.network"
    owner: root
    group: root
    mode: "0644"
  register: komodo_network
  tags: komodo

- name: Copiar politica SELinux per a Komodo Periphery
  ansible.builtin.copy:
    src: "{{ role_path }}/files/komodo_periphery_1.cil"
    dest: "/etc/komodo/komodo_periphery_1.cil"
    owner: root
    group: root
    mode: "0644"
  register: periphery_policy_file
  tags: [komodo, periphery, selinux]

- name: Check periphery SELinux policy installed
  ansible.builtin.command: semodule -l | grep -w komodo_periphery_1
  register: selinux_policy_check
  failed_when: false
  changed_when: false
  tags: [komodo, periphery, selinux]

- name: Install periphery SELinux policy
  ansible.builtin.shell: |
    semodule -i /etc/komodo/komodo_periphery_1.cil /usr/share/udica/templates/*
  args:
    creates: /var/lib/selinux/targeted/active/modules/400/komodo_periphery_1
  when: selinux_policy_check.rc != 0 or periphery_policy_file.changed
  changed_when: true
  tags: [komodo, periphery, selinux]

- name: Reload systemd if komodo config changed
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: komodo_periphery_quadlet.changed
    or komodo_network.changed
  tags: komodo

# - name: Pull images for komodo containers based on configured versions
#   ansible.builtin.shell:
#     cmd: |
#       podman pull $(awk -F'=' '/^Image=/ {print $2}' /etc/containers/systemd/komodo_periphery_1.container)
#   changed_when: false
#   tags: komodo

- name: Include Komodo core key generation tasks
  ansible.builtin.include_tasks: core2periphery.yaml
  tags: [komodo, keys]

- name: Restart Komodo Periphery if needed
  ansible.builtin.systemd_service:
    name: komodo_periphery_1.service
    state: restarted
    enabled: true
  when: komodo_periphery_quadlet.changed
    or komodo_network.changed
    or periphery_policy_file.changed
  tags: komodo

- name: Include Komodo periphery key generation tasks
  ansible.builtin.include_tasks: periphery2core.yaml
  tags: [komodo, keys]
