---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infisical
spec:
  dependsOn:
    - name: infisical-operator
  healthChecks:
    - apiVersion: secrets.infisical.com/v1beta1
      kind: InfisicalConnection
      name: infisical-cloud
      namespace: infisical-system
    - apiVersion: secrets.infisical.com/v1beta1
      kind: InfisicalAuth
      name: infisical
      namespace: infisical-system
    - apiVersion: secrets.infisical.com/v1beta1
      kind: InfisicalStaticSecret
      name: infisical-bootstrap-credentials
      namespace: infisical-system
  healthCheckExprs:
    - apiVersion: secrets.infisical.com/v1beta1
      kind: InfisicalConnection
      failed: status.conditions.exists(e, e.type == 'secrets.infisical.com/IsReady' && e.status == 'False')
      current: status.conditions.exists(e, e.type == 'secrets.infisical.com/IsReady' && e.status == 'True')
    - apiVersion: secrets.infisical.com/v1beta1
      kind: InfisicalAuth
      failed: status.conditions.exists(e, e.type == 'secrets.infisical.com/IsReady' && e.status == 'False')
      current: status.conditions.exists(e, e.type == 'secrets.infisical.com/IsReady' && e.status == 'True')
    - apiVersion: secrets.infisical.com/v1beta1
      kind: InfisicalStaticSecret
      failed: status.conditions.exists(e, e.type == 'secrets.infisical.com/LastReconcileStatus' && e.status == 'False')
      current: status.conditions.exists(e, e.type == 'secrets.infisical.com/LastReconcileStatus' && e.status == 'True')
  interval: 1h
  path: ./kubernetes/apps/infisical-system/infisical/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: infisical-system
  timeout: 5m
  wait: false
