---
services:
  sync:
    image: ghcr.io/bakito/adguardhome-sync:alpine-v0.8.2@sha256:4a7f4195b15c923f0a9338220d693665162aeea3b8d8a85709c84669382629c5
    container_name: adguard_sync_1
    environment:
      - CRON="*/10 * * * *" # run every 10 minutes
      - RUNONSTART=true
      - ORIGIN_URL="${ORIGIN_URL}"
      - ORIGIN_USERNAME="${ORIGIN_USERNAME}"
      - ORIGIN_PASSWORD="${ORIGIN_PASSWORD}"
      - REPLICA1_URL="${REPLICA1_URL}"
      - REPLICA1_AUTOSETUP=true
      - REPLICA1_USERNAME="${REPLICA1_USERNAME}"
      - REPLICA1_PASSWORD="${REPLICA1_PASSWORD}"
      - REPLICA2_URL="${REPLICA2_URL}"
      - REPLICA2_AUTOSETUP=true
      - REPLICA2_USERNAME="${REPLICA2_USERNAME}"
      - REPLICA2_PASSWORD="${REPLICA2_PASSWORD}"
    ports:
      - 8080:8080
    restart: unless-stopped
