---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: github-status-token
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/flux
      recursive: false
  targets:
    - name: github-status-token-secret
      namespace: _
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          token: "{{ .FLUX_GITHUB_TOKEN.Value }}"
