---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: konflate-webhook-token
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/konflate
      recursive: false
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/github-bot
      recursive: false
  targets:
    - name: konflate-webhook-token-secret
      namespace: flux-system
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          KONFLATE_WEBHOOK_SECRET: "{{ .KONFLATE_WEBHOOK_SECRET.Value }}"
          KONFLATE_APP_CLIENT_ID: "{{ .GITHUB_BOT_APP_CLIENT_ID.Value }}"
          KONFLATE_APP_PRIVATE_KEY: "{{ .GITHUB_BOT_APP_PRIVATE_KEY.Value }}"
