apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configarr-etc
  namespace: arr
  labels:
    app: configarr
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configarr-var
  namespace: arr
  labels:
    app: configarr
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
