name: rustfs

services:
  chown:
    image: ghcr.io/vegops/chown:latest
    container_name: rustfs_chown_1
    volumes:
      - ${S3_DATA_DIR}/rustfs:/chown
    command: "-R ${PUID}:${PGID} /chown"

  app:
    image: docker.io/rustfs/rustfs:1.0.0-rc.5@sha256:c36b3efea3d1e503f1a2581abd0e7611e0e5820dd30e1850a52384b3fc52bda4
    container_name: rustfs_app_1
    user: "${PUID}:${PGID}"
    stop_grace_period: 2m
    depends_on:
      chown:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "--silent",
          "--show-error",
          "--max-time",
          "3",
          "http://127.0.0.1:9000/health/ready",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      TZ: ${TZ}
      RUSTFS_SERVER_DOMAINS: ${RUSTFS_HOSTNAME}
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_VOLUMES: /data
      RUSTFS_OBS_LOG_DIRECTORY: /logs
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY} # Generate your own access key with `openssl rand -hex 16`
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY} # Generate your own secret key with `openssl rand -hex 32`
      # RUSTFS_OBS_ENVIRONMENT: development
      # RUSTFS_OBS_LOGGER_LEVEL: debug
      # RUSTFS_OBS_LOG_STDOUT_ENABLED: "true"
      # RUST_BACKTRACE: 1
    volumes:
      - ${S3_DATA_DIR}/rustfs/data:/data
      - ${S3_DATA_DIR}/rustfs/logs:/logs
    ports:
      - 9000:9000
      - 9001:9001
    restart: unless-stopped
