apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nas
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ds920plus.home.eudald.gr
    path: /volume1/k8s/immich
  mountOptions:
    - nfsvers=4.1
    - nconnect=4
    - hard
    - noatime
