apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nas
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: immich-nas
  storageClassName: ""
