---
working_dir: ./compose/cadi
auto_discovery:
  enabled: true
  depth: 1
  delete: true
force_recreate: false
reconciliation:
  enabled: true
  interval: 3600
external_secrets:
  CADDY_ACME_EMAIL: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/vps/cadi/CADDY_ACME_EMAIL
  TOWONEL_INVITE_HASH_KEY: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/vps/cadi/TOWONEL_INVITE_HASH_KEY
  GATUS_PUSHOVER_KEY: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/pushover/PUSHOVER_USER_KEY
  GATUS_PUSHOVER_TOKEN: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/gatus/GATUS_PUSHOVER_TOKEN
  GATUS_REMOTE_STATUS_HOSTNAME: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/gatus/CADI_STATUS_HOSTNAME
  GATUS_REMOTE_HEARTBEAT_TOKEN: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/gatus/CADI_HEARTBEAT_TOKEN
