---
- name: Disable root user
  ansible.builtin.user:
    name: root
    password_lock: true
    state: present
  tags: security

- name: Disable SSH password authentication
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/50-homelab.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      PasswordAuthentication no
    validate: "sshd -t -f %s"
  notify: Restart ssh service
  tags: security

- name: Ensure SELinux is set up
  ansible.builtin.command: |
    transactional-update --non-interactive --continue setup-selinux
  changed_when: false
  tags: selinux

- name: Configure SELinux to enforcing with autorelabel
  ansible.builtin.command: |
    transactional-update --continue run bash -c 'echo "-F" > /etc/selinux/.autorelabel'
  changed_when: false
  tags: selinux

- name: Reboot after SELinux setup
  ansible.builtin.reboot:
    pre_reboot_delay: 10
    reboot_command: "/usr/bin/systemctl reboot"
    test_command: uptime
  tags: reboot
