---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: qui
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/downloads/qui
      recursive: false
  targets:
    - name: qui-secret
      namespace: downloads
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          QUI__SESSION_SECRET: "{{ .QUI_SESSION_SECRET.Value }}"
