---
- name: Enable IPv4 unprivileged port start to 0
  ansible.posix.sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "0"
    state: present
    reload: true
  tags: sysctl

- name: Enable IPv4 ping group range
  ansible.posix.sysctl:
    name: net.ipv4.ping_group_range
    value: "0 2000000"
    state: present
    reload: true
  tags: sysctl

- name: Installing Podman
  community.general.apk:
    name:
      - podman
      - podman-bash-completion
      - podman-compose
      - podman-compose-bash-completion
      - slirp4netns
      - util-linux-login
      - linux-pam
    state: present
    update_cache: true
  tags: packages

- name: "Enable cgroups v2"
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: 'rc_cgroup_mode="unified"'
    state: present
  tags: system

- name: "Enable memory and pids controllers"
  ansible.builtin.lineinfile:
    path: /etc/rc.conf
    line: 'rc_cgroup_controllers="memory pids"'
    state: present
  tags: system

- name: Enable cgroup service
  ansible.builtin.service:
    name: cgroups
    enabled: true
    state: started
  tags: services

# - name: "Create rootless group"
#   ansible.builtin.group:
#     name: rootless

# - name: "Create rootless user"
#   ansible.builtin.user:
#     name: rootless
#     uid: "{{ nfs_map_uid | default(1024) }}"
#     group: users
#     shell: /bin/sh
#     home: /home/rootless
#     system: true
#     state: present
#   tags: user

# - name: Add ansible_user to the rootless group
#   ansible.builtin.user:
#     name: "{{ ansible_user }}"
#     groups: rootless
#     append: true
#     state: present

- name: "Ensure /etc/pam.d/su exists"
  ansible.builtin.file:
    path: "/etc/pam.d/su"
    state: touch
    owner: root
    group: root
    mode: "0644"
  tags: pam

- name: "Copying pam rule for 'su through wheel'"
  ansible.builtin.copy:
    owner: root
    group: root
    mode: "0755"
    src: "{{ role_path }}/files/su"
    dest: /etc/pam.d/su
  tags: pam

- name: "Setting subuid"
  ansible.builtin.copy:
    dest: /etc/subuid
    owner: root
    group: root
    mode: "0644"
    content: |
      {{ ansible_user }}:100000:65536
  tags: user

- name: "Setting subgid"
  ansible.builtin.copy:
    dest: /etc/subgid
    owner: root
    group: root
    mode: "0644"
    content: |
      {{ ansible_user }}:100000:65536
  tags: user

- name: "Enable rootless user on conf.d/podman"
  ansible.builtin.lineinfile:
    path: /etc/conf.d/podman
    line: 'podman_user="{{ ansible_user }}"'
    state: present
  tags: podman

- name: "Copying env vars to profile.d"
  ansible.builtin.copy:
    owner: root
    group: root
    mode: "0644"
    src: "{{ role_path }}/files/rootless.sh"
    dest: /etc/profile.d/rootless-containers.sh
  tags: podman

- name: Create /etc/containers/nodocker
  ansible.builtin.file:
    path: /etc/containers/nodocker
    state: touch
    owner: root
    group: root
    mode: "0644"
  tags: podman

- name: "Enabling podman related services"
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - "cgroups"
    - "podman"
  tags: services
