---
- name: Get UID of {{ rootless_user }}
  ansible.builtin.command:
    argv: ["/usr/bin/id", "-u", "{{ rootless_user }}"]
  register: rootless_uid
  changed_when: false
  tags: user

- name: Crear directori pare per a Pangolin Stack
  ansible.builtin.file:
    path: "{{ app_data_dir }}/pangolin"
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0755"
  tags: pangolin

- name: Crear subdirectoris per a Pangolin Stack
  ansible.builtin.file:
    path: "{{ app_data_dir }}/pangolin/{{ item }}"
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0755"
  with_items:
    - data
    - data/config
    - data/config/db
    - data/config/letsencrypt
    - data/config/logs
    - data/config/traefik
    - data/config/traefik/logs
    - quadlets
  tags: pangolin

- name: Copiar fitxers de configuració de Pangolin Stack
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ app_data_dir }}/pangolin/quadlets/{{ item }}"
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0644"
  with_items:
    - pangolin_app_1.container
    - pangolin_gerbil_1.container
    - pangolin_traefik_1.container
  tags: pangolin

- name: Copiar fitxers de configuració de Pangolin Stack
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ app_data_dir }}/pangolin/quadlets/{{ item }}"
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0644"
  with_items:
    - pangolin_traefik_1.cil
    - pangolin_proxy_1.pod
    - pangolin_traefik_http.socket
    - pangolin_traefik_https.socket
  tags: pangolin

- name: Copiar fitxers de configuració de Pangolin Stack
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item.name }}.j2"
    dest: "{{ app_data_dir }}/pangolin/{{ item.dir }}/{{ item.name }}"
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0644"
  with_items:
    - name: config.yml
      dir: data/config
    - name: traefik_config.yml
      dir: data/config/traefik
    - name: dynamic_config.yml
      dir: data/config/traefik
  tags: pangolin

- name: Assegurar que els directoris necessaris existeixen
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0755"
  with_items:
    - "/home/{{ rootless_user }}/.config/containers/systemd"
    - "/home/{{ rootless_user }}/.config/systemd/user"
  tags: podman

- name: Crear enllaços symlink quadlets de Pangolin Stack
  ansible.builtin.file:
    src: "{{ app_data_dir }}/pangolin/quadlets/{{ item }}"
    dest: "/home/{{ rootless_user }}/.config/containers/systemd/{{ item }}"
    state: link
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0644"
  with_items:
    - pangolin_app_1.container
    - pangolin_gerbil_1.container
    - pangolin_traefik_1.container
    - pangolin_proxy_1.pod
  tags: pangolin

- name: Crear enllaços symlink quadlets de Traefik Sockets
  ansible.builtin.file:
    src: "{{ app_data_dir }}/pangolin/quadlets/{{ item }}"
    dest: "/home/{{ rootless_user }}/.config/systemd/user/{{ item }}"
    state: link
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0644"
  with_items:
    - pangolin_traefik_http.socket
    - pangolin_traefik_https.socket
  tags: pangolin

- name: Check periphery SELinux policy installed
  ansible.builtin.command: |
    semodule -l | grep -w pangolin_traefik_1
  register: selinux_policy_check
  failed_when: false
  changed_when: false
  tags: pangolin, selinux

- name: Install periphery SELinux policy
  ansible.builtin.shell: |
    semodule -i {{ app_data_dir }}/pangolin/quadlets/pangolin_traefik_1.cil /usr/share/udica/templates/base_container.cil
  args:
    creates: /var/lib/selinux/targeted/active/modules/400/pangolin_traefik_1
  when: selinux_policy_check.rc != 0
  tags: pangolin, selinux

- name: Download GeoLite2 Country database
  ansible.builtin.get_url:
    url: https://github.com/GitSquared/node-geolite2-redist/raw/refs/heads/master/redist/GeoLite2-Country.tar.gz
    dest: /tmp/GeoLite2-Country.tar.gz
    mode: "0644"
  tags: pangolin, geolite2

- name: Extract GeoLite2 Country database
  ansible.builtin.unarchive:
    src: /tmp/GeoLite2-Country.tar.gz
    dest: /tmp
    remote_src: true
  tags: pangolin, geolite2

- name: Find extracted GeoLite2 Country database
  ansible.builtin.find:
    paths: /tmp
    patterns: "GeoLite2-Country.mmdb"
    recurse: true
    file_type: file
  register: geolite2_file
  tags: pangolin, geolite2

- name: Move GeoLite2 Country database to Pangolin config directory
  ansible.builtin.copy:
    src: "{{ geolite2_file.files[0].path }}"
    dest: "{{ app_data_dir }}/pangolin/data/config/GeoLite2-Country.mmdb"
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0644"
    remote_src: true
  when: geolite2_file.files | length > 0
  tags: pangolin, geolite2

- name: Clean up GeoLite2 Country database temporary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/GeoLite2-Country.tar.gz
    - "{{ geolite2_file.files[0].path | dirname }}"
  when: geolite2_file.files | length > 0
  tags: pangolin, geolite2

# There's an issue with passta that prevents pulling images
- name: Pull images for pangolin containers based on configured versions
  become: true
  become_method: community.general.machinectl # noqa: schema
  become_user: "{{ rootless_user }}"
  vars:
    ansible_pipelining: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ rootless_uid.stdout | trim }}"
  ansible.builtin.shell:
    cmd: |
      podman pull $(awk -F'=' '/^Image=/ {print $2}' {{ app_data_dir }}/pangolin/quadlets/*.container)
  changed_when: false
  tags: pangolin

- name: Include crowdsec tasks if enabled
  ansible.builtin.include_tasks: crowdsec.yaml
  when: pangolin_crowdsec
  tags: pangolin, crowdsec

- name: Start and enable pangolin containers
  become: true
  become_method: community.general.machinectl # noqa: schema
  become_user: "{{ rootless_user }}"
  vars:
    ansible_pipelining: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ rootless_uid.stdout | trim }}"
  ansible.builtin.systemd_service:
    name: pangolin_proxy_1-pod.service
    state: restarted
    enabled: true
    scope: user
    daemon_reload: true
  changed_when: false
  tags: pangolin

- name: Register pangolin token
  become: true
  become_method: community.general.machinectl # noqa: schema
  become_user: "{{ rootless_user }}"
  vars:
    ansible_pipelining: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ rootless_uid.stdout | trim }}"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      journalctl --user -u pangolin_app_1 -n 300 | \
      awk -F'Token: ' '/Token:/ {print $2}' | \
      tail -n1
  register: pangolin_token_result
  changed_when: false
  retries: 30
  delay: 10
  until: pangolin_token_result.stdout | trim | length > 0
  tags: pangolin

- name: Show pangolin token
  ansible.builtin.debug:
    msg: "Pangolin token: {{ pangolin_token_result.stdout | trim }}"
  tags: pangolin
