secret_pangolin_domain: ENC[AES256_GCM,data:Kw5kwcZ1+tmVL9ZeNXORvJZG,iv:TeGg1p/CaINu/+Fq3u2UZ2XZFro5gjFrWw0LcB+trbs=,tag:HBCnCsztkW7FctYN+wkB4A==,type:str]
secret_base_domains:
  - ENC[AES256_GCM,data:WRdVxdPMkPcY,iv:87lMdXl57WikacG7Bfwu08LWEEXF69mY2JS9ylJDMGk=,tag:BWusqpe/rQbYD1hM24tw+g==,type:str]
secret_pangolin_email: ENC[AES256_GCM,data:OxR3LQ==,iv:rRoH/O+nz+NrDBGtBGS2Ov/Q0MBbjvZImHoWAmrmB6w=,tag:xKHgfZgHPCxuic7edHwEVg==,type:bool]
secret_pangolin_smtp_host: ENC[AES256_GCM,data:+r+6IFyxgiHGnI0XWh99/g==,iv:j/rcLiNmRZcw+k2RIRSa6AygUPhl00G0V8DPVJp990c=,tag:KLsHi88XO12A6uRuJ9Yfjg==,type:str]
secret_pangolin_smtp_port: ENC[AES256_GCM,data:PQNJ,iv:iNZmh8LRsiZQGXeAB+Z1VOCCJIG5SLxlIlzbQQbTrZ8=,tag:f7eHdO5ldix1iASddt4o3Q==,type:int]
secret_pangolin_smtp_user: ENC[AES256_GCM,data:Vi2Rf+ZrrqdjEeN9mQ8skQ==,iv:ZOJiHN45VsxazbcnEM8ODYD8R7Vf0DTVb8cgYNpHN1U=,tag:24pgovJ2lLpfZyaKmnwhcw==,type:str]
secret_pangolin_smtp_pass: ENC[AES256_GCM,data:PfNExGZNAXeyQUAgibbNieKfMzDa+KYazdgDM1zFz/QLFScg7RlYukfPbDeoPZ83f1cvQKYxbU7GIw5pAJJHTQ==,iv:a5uJ5r30a9ZKa0O6UxhvbcGkXNU4pDch0FFoIe5SStE=,tag:yCmwI7Z3hdNd+x+Ml958CQ==,type:str]
secret_pangolin_smtp_secure: ENC[AES256_GCM,data:iLnnHQ==,iv:LAir8pKp7TUDnWmcECQ1tMuzJDOtbz1UexSJG2vSEH8=,tag:dZcpBh5G4TiFM2GRU+AcBA==,type:bool]
secret_pangolin_smtp_no_reply_email: ENC[AES256_GCM,data:rC1yLsB3P1wnX40Ok9CNZPo=,iv:91mknhOSyMexLJbMTTkrii4xPVSzoYw4sWoOrpifQ3c=,tag:W+aAxOWxPV/uEUZxRpNEXA==,type:str]
secret_pangolin_traefik_letsencrypt_mail: ENC[AES256_GCM,data:vsJhCsbcyLi7cRec,iv:iJCW1xrZ6Y1MrOKEGQwfZSn4oneb9l8rl9/pkt6XqAw=,tag:sTAc/wvriVDbIQ+HqCed7Q==,type:str]
secret_pangolin_server_secret: ENC[AES256_GCM,data:tmjyEJSZXIHknL1a2HEeBOvfnyx2NaWBwtLgwvrtQ2q04Bbxdohuxh3kcxla5HbNVxe4EF3vjXUohokU0tmgBw==,iv:Se48zd4MHVw8pL5birHl1LsmROX5m4g2/MTIuqKEysU=,tag:giyUGwYsfyjaAvNcrfGvyQ==,type:str]
secret_pangolin_crowdsec_lapi_key: ENC[AES256_GCM,data:50OQaBfFWPtMvOLN9fRJ08YuIR1Rup6spA==,iv:7XR+gGIRWcCdve5j77MqHYoKXS9eCJx64PsSB3QbcSE=,tag:FQfKJknby1XqXfE5nhFWtg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvL2laR25HQlllN2gyZTdk
        cCtHMDdOcENLS0NYZU5YUUdpb0oxYXl1K3prCkhSMGkyTEQrMmV5V3VVYWpXd2x5
        RXNUOEdVWlo2V1U4RXlsZnJQeWZEV1kKLS0tIHdTQ3NiSWxvOUpCYmVyVXNDQklN
        QzdFTHkyeE9NQkxGNk5jdXVMODEzVzQKqQegZ6WwFAVYIJ8bvAAzoT0Tabu7T5pW
        7WSBQdSTh5TwgSWYpYq3M1m1MgywfFuUhVLr4ZUXD8DpilWvjFgN5w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1yfrq96mwj6ah0szswj9a8vg8jmyzwl5g6w5u8fh23yg85saxyunss056hg
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdFl4UWlYWDJoQXd1MlNM
        eVVSTys5cG1rVFpLRHdEa0NjODdqODF6L3hRClFoK0VWTXFRVWVlU0NRZThWT2Jo
        YUcvUllHbGpmVlZsaGtLNmZXendaS1UKLS0tIFlxNjRobUZRWW5NYW5zSFlwdVd5
        OVlnb2V4U3hEZ1ZYMmlqbVp0R3dCS2MKMHYfw87COPBomV9e4ld3HNSQhzeoRDXx
        iHD7cszo7Iq6zxuwvQP0JioIEsypAB4gZmneIFTNKsQMvq5ZjVggLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age175lfmhlkmu8qu07dkxsau62v4vfdczejr66xvf9peg733rrth44shlz5zq
  lastmodified: "2026-09-15T19:16:19Z"
  mac: ENC[AES256_GCM,data:DlZFEG8dqFTzwhZ8SvX5+oIaVpzEVtq6Gf/KenaR5UVFgjlQvZTJt0U0VSE+DUhkNrRQrN4+cNMcfahKPgEa8WEjm5ZO7dbpjFnEF4nlpj3eho18g8sxGguos8mq8Z5Xe55DyGR71g+0gbsrJVy5hym2MsbPSZ2prHvfzVDzA/Y=,iv:CqMAAWhVc2UTJNgZkpXMaahVpdqmiIjeD6PqS1DvfB8=,tag:co4jsAG7tlchENB9pqQUDQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
