name: sure

x-sure-env: &sure-env
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  SECRET_KEY_BASE: ${APP_SEED}
  SELF_HOSTED: "true"
  RAILS_FORCE_SSL: "false"
  RAILS_ASSUME_SSL: "false"
  DB_HOST: sure_db_1
  DB_PORT: 5432
  REDIS_URL: redis://sure_redis_1:6379/1

x-sure: &sure
  image: ghcr.io/we-promise/sure:0.7.1-hotfix.1@sha256:64fa5951bcd426863759f5f06cf0316522bc5ecb3552bb6894f4101ca8708f6f
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy
  volumes:
    - ${APP_DATA_DIR}/sure/var:/rails/storage
  environment:
    <<: *sure-env
  restart: unless-stopped

services:
  app:
    <<: *sure
    container_name: sure_app_1
    ports:
      - 3064:3000
    labels:
      # Public Resource Configuration
      - pangolin.public-resources.sure.name=sure
      - pangolin.public-resources.sure.full-domain=${SURE_HOSTNAME}
      - pangolin.public-resources.sure.protocol=http
      # Target Configuration - Override to Host Hairpin
      - pangolin.public-resources.radarr.auth.sso-enabled=true
      - pangolin.public-resources.sure.targets[0].method=http
      - pangolin.public-resources.sure.targets[0].hostname=127.0.0.1
      - pangolin.public-resources.sure.targets[0].port=3064
      # Health Check Configuration
      - pangolin.public-resources.sure.targets[0].healthcheck.enabled=true
      - pangolin.public-resources.sure.targets[0].healthcheck.hostname=127.0.0.1
      - pangolin.public-resources.sure.targets[0].healthcheck.port=3064
      - pangolin.public-resources.sure.targets[0].healthcheck.path=/up

  worker:
    <<: *sure
    container_name: sure_worker_1
    command: bundle exec sidekiq

  db:
    image: docker.io/library/postgres:18.4-alpine3.23@sha256:865a3cfdac164ea2608bea36342a9bb5c11e99b5aa8ed9b83b662185e556e178
    container_name: sure_db_1
    volumes:
      - ${APP_DATA_DIR}/sure/postgres:/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/pgdata
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'pg_isready -U "$${POSTGRES_USER}" -h localhost -d "$${POSTGRES_DB}"',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  redis:
    image: docker.io/library/redis:8.8.0-alpine@sha256:09160599abd229764c0fb44cb6be640294e1d360a54b19985ab4843dcf2d90f1
    container_name: sure_redis_1
    volumes:
      - ${APP_DATA_DIR}/sure/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
