---
name: doco-cd
secrets:
  infisical_client_secret:
    file: /volume2/docker/doco-cd/infisical_client_secret
services:
  app:
    image: ghcr.io/kimdre/doco-cd:0.120.1@sha256:8799df51462a1b2058c60e35d1ce19830cc38afebe99494342e819cdaadad545
    container_name: doco-cd
    env_file:
      - /volume2/docker/doco-cd/.env
    environment:
      DEPLOY_CONFIG_BASE_DIR: ./compose/ds920plus/
      HTTP_PORT: 8880
      LOG_LEVEL: info
      POLL_CONFIG: |-
        - url: https://github.com/eudaldgr/homelab.git
          reference: main
          interval: 3600
      SECRET_PROVIDER: infisical
      SECRET_PROVIDER_SITE_URL: https://eu.infisical.com
      SECRET_PROVIDER_CLIENT_SECRET_FILE: /run/secrets/infisical_client_secret
      TZ: Europe/Madrid
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    secrets:
      - infisical_client_secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    restart: unless-stopped
volumes:
  data:
