---
name: doco-cd-updater
services:
  app:
    image: ghcr.io/kimdre/doco-cd:0.120.1@sha256:8799df51462a1b2058c60e35d1ce19830cc38afebe99494342e819cdaadad545
    container_name: doco-cd-updater
    environment:
      DEPLOY_CONFIG_BASE_DIR: ./compose/ds920plus
      HTTP_PORT: 8881
      LOG_LEVEL: info
      POLL_CONFIG: |-
        - url: https://github.com/eudaldgr/homelab.git
          reference: main
          interval: 3600
          target: updater
      SCHEDULER_ENABLED: "false"
      TZ: Europe/Madrid
    healthcheck:
      test:
        - CMD
        - /doco-cd
        - healthcheck
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
      - type: bind
        source: /volume2/docker/doco-cd
        target: /volume2/docker/doco-cd
        read_only: true
        bind:
          create_host_path: false
    restart: unless-stopped
volumes:
  data:
