---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: towonel-agent
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/network/towonel-agent
      recursive: false
  targets:
    - name: towonel-agent-secret
      namespace: network
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          TOWONEL_INVITE_TOKEN: "{{ .TOWONEL_INVITE_TOKEN.Value }}"