---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.authentik.clientID: AgCoikDTnNrtoG5D0eyrPZbjla1Ce3LtK7guSEb6Blis2YGJcfNTXZMlyIyKe581FeeSGdEKOPgWJ3CdykdDibugP7EUKqlsrYqEafrbqe/r72ngYDVxUC9MkrASzAPQDGrHU9/V705vF42/pJSg023AohQwfwDKaFhvMPxjQoQO+Nkj+4YcC0hoO9n0JHEWxv9xu3B4aq9kehsxuErrE02lswYElRQZltuCCnmAso4hhzoysOTn9aM8tO9OOHeWHpUSOrEiD9S2SkWfd50DSDzNbqvm60bl2JDVk+4mRmaol20EALRIYIWcZU7NIRFbfCMaK7G0iUUqV6k5q6tEiAI1UpXtXGJSHIRWYkKbNNG+PFabXo7x6jR0+z7wty+zDzXlR60owUsdI7bAOV5f4tcWlU+c7+kCfNA036jcneApxxTZPzQ8OApbq6hoCsE3KKLUVu0J4HEKfYdVumtdJ5lzcBHnXqmNQdp+TlpOihqTR6jQlqQG0GqvGO9xrg198PgLWrGMwMRNGfkpIgug/NgoXR838JDDZ37IvlHpx5KbbNX6x8JI6ZSUp4OxvHEeKfRJfUikeCtX4nXQi3onI4dccCX/Li2BV3MpIdCp8j1H+hVTy6S4aE85mKCbUq80VUN/Hx6MxMCf0Wp39HCXCKKO8Hr9YwFBWy70xMytkTgigQVQwyXMq2EDZpupdwdPeGeuuWsFXJo=
    oidc.authentik.clientSecret: AgBhG1AZGf31xa/wssxWXz51CLcEr/mnY0v9SoTZTSIB5rYUJMwaJr7Ht8XFhmkODhjoYKirg+NiFptpnmNW6xR2F4e0eR3bigXjB2j59qh7wCNeEL2HOITele1q+16aUh27G0o2CbhH8MGe/b0fko9t1BA4U6gz8sSo6TKqa9kjYxlA5NuuOcwCcC31ZLHmJH4yog4tcPjQeSVpP00QxZWbRHIHNYIppgljgDEjJeGfTCe/IUdbnyYEdFHl+10u7ximRo0XcstHaqF/D5LFr/20PWlpDTfcY+C+uFbgbfa/AXLRtBZ4KqRv5qMTgN2xy1pCs9CWseli6eZcPp4T/ZRT3GTY1VbG5ow+0Yd2r4Ew/B4RYzKOccmDoNbUGG0zG0XVNdzZTLD3zfjXSeXHjF+vHOTFM8vKk+wzf83iJfdU6jY0CR+jp7hHgWKA14prgevMSX88ekrxPTk3R73m1jQALfBFdp0lMnRmUgcRwvJ8jrNp7+/thBWeBSMxtfmI1gBPUWmHq+DILziI2Yj4JWYlB3LM8ilj81cYEqroYo9IOe82DX+RVp0ETh4Pbegk6jtdURf8ZmAmeop+oUFI7/9ktYH6gUlY6qQP+0b/IQYp40zplAu4jfQ2pb/7y8QXd2DQJVE0kDkOJhSNPTITsBvDcXbpKJVhDbbCfm+qsO/mM50T4LIdBAPKWmiPvE5eIFLPQyqgtFym+qYgSNpV02BIy/wlDUI1OWWwguFECSzTjv+tGE9vcgqgnFaq8zP60eg/naF7EMrio36qILyoCZkC
  template:
    metadata:
      name: argocd-oidc-secret
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
