---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.authentik.clientID: AgB2MfyoleednENCHFLNb88s6G1gsXB5BWOP6aMwAja8KV0h6Egw3mZnOv4nHmW8DlRiBQKc87KlnnWduTDQhd5mkM9MQvhdqYMKWg2eiRqfhFDQFAasJ1HAZ+xADmoO5o+NRrDaCQ0A2e9ra8VL5SNhwOnGyKs0RNameurGIIu/aKm30a3MM2Lpj422cUHNdWEvdVrRrnnMFfbz4gDLUTd7DJREBq5O1UgR5lENb0wii+lB7a1kRF9xMCASjNaSuC5NaYOed2WQXqsIbXGBuK8jjElThabdcLXlez1q8xhzf9yot06+A8ayPvdWy6FUN3iAdGobv+XaNwNIkO8JzQViTL/THzMDjHJRIGB6/9EziJrwXvutQYwUanMMskz1VyKFniRhkI+GW3XHz6k1q82Nyqom41Hp3yd8fUe4B45cxb2WltamGf1+L4e7/CB+noGXqQVSYwQgOu8ZOcq2caIoUsF/xX1iftgzqP4slCqLa4wvwZ76nlw5U9MPgsxoD+isS/KrEvTUwfFUiBVRDMnEUYKnx8GH6WI9/Ayic31LC+NBQbfGlzvQvnM+ils1+k9iJ44nxV+Q5SpQc7JoSqyhlNUedGYUvMZ0HwF8nH5sA8Npn9MrjnCL8Rrd4ZE+0v74cxgiEFbmU5UIV8WNbpCmtozYwUwYHjxWrEf5btv8YBc4MtP4kvzIrFqUftms44Jtzpt/sj0=
    oidc.authentik.clientSecret: AgAuvwx6DtfeqQdbp613Yc1EE9v6vBI5g/kpwbf/P6rwSxTJqK6qI70TYq3k5ewzE2t6hSXgO/roN02CKbDeEIS3cf9i/Rv6DJnNvpuFv/b3E2j0iG1slS7CIPhKsUUI6+DSj0rLOKCDQoBB4T8Tlj8kixgtbU+6N/Mti6uAwyQNf3FrANLelNY2RS3ZMK/21YIZQquBHs8oMzavMjCFKeELy1JwuILnzzgD+TYu5u5JaMD/bJih+aAwCl1X5x7OaOrYQ+QqlO2rVirqryXNglQuSiN1e+qma0uziUE5JIh7JEM2g2wzZ7vwXKPIuRW9X9Ay3xiE2v+aAEz8VeA0lEOubOMeTVZ1bQQ+TsPX0JH75bfCxo/sxGEW/5EvGtJfw2p8LNG6ZzdHb0cR1msg57lrcPZi6W3zMdpib21E2gQ3h0jX/bo6+s7LSLSEz+k6BQO9cRaf+f+K1mB3KZM9+xLWLaVJPkj170xiL4VsmvCpQE/LCwavZ//+Kq4uR5Ig7Ilph5fLco2uE+570b6Y/RustktKCBouJbop8SRc0CYUp06g9OjkFRgg5pNWQlyO2/iE5NxsZZ2wqaDqovjiiR3ZsA1NK3xUvonxMgTy6qwNXlq7kQ0QsCPSsaK1bVBx20IfZqJ+5TSMmSzRHTs5Y8NI5Movv1gDHNmLoU/U7ia0jFYBlPtXD0k3ppFXGDTuAILYEK5Y5irLGP/I7Wk+9EYqGQ/Huh60CLguh3fw2lnVmoA/SkJlWUBBkMkwOzo2RpWWlVz+Fz9IKEqUU4fq1ntM
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
