---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.authentik.clientID: AgAJyp2/UEmI7QmzngR3EXnl4tCKXxCTbo4L6dnqujXVREiL3/dwSTRTlM+287M3c3N5CM91dy6+vB+Aanj+OLwschzRkBEH2rqia8ppHBUEppsz6R48b08oS9cdDmHNHBT4D2qWOJE5s8ST5ekc8jIO0CYFibw8GDrXFiORQHjCMWdRz/MKmy/V0utGr0B/xAQ1qzpsLN2wiOHoyGOlX3MqKWLUVwXgUdaYlzyoxlNFWM6rCkW3PwRIiKvqTlKBc3OmPzBU6ENDl807WOSaaCZWZmXYrsCa5Q735jSpVjxoDUxJfdU/O4dfCp8OOpCGOcxsB7Cv2gQqKpnpYRKshj62gVAE+5B1DKoRmrsdA+8/rdAaC25FP+gkcOT1F5Ng67vMoF6jieFnR+lpWIem+jWsVjBI8pacixxvBDL/2c7qNwoCLtGKW6tHTTmKaBsywliZE8Vx+cF9Xe1JBjqO5hjcJAc9ytodgpD8QrsL6j5gZfPVYQvIhKjpLpilo4VszixwctN0wU3hqxdZMenrB4Ejih7jG6FAej9G02AbNFahXsmep4p1bx3iLUATHxf9fhi+Tne/Y2gbu8fsMJDPnVE/GG7ypRKr/srxWlhoQL88E3ZWRSWRYK7Mdg2k6mHFR2O3oZPEFan5FdPPl12HQoqekI3zmOpr6cwXxdJyy/3rtqaCEU1edgFEUWC29+ZTSsCwf+avkiR6GAoCGibZIkqEiS0qLagqSe9n+/tSXOgH1AjtmoTNcgJX
    oidc.authentik.clientSecret: AgBqzZq4o6GZlrDgY4QxKpiWHd1W+GtTCbgQurNOmVNC/C+3bB1Fm2PrQ9lG8EOXU7XORWYR4uW77EOKCKTyKsIywqtvhOVqc7fy1XlEu3bS+wJI5VDhGqEuvr8tK+HVk6oa1bd783pnsf/E4PWnwdGCGr4wqivmEYGvKWWNYxFmu8HuRKJbhs2V35i8pHP5t+z2FLmJX5AaqOqiMECydeRjwSmFQXTnhsABapqULYqSxkzog6hioCZN/tqTYf3ockkVBcT2WsN7njPp/2uOjeU8hQMbrwebFRhtiFq7bwb3sdpxSFSzdQlUVoGOb6KOBIznvBcAzI+T8vhYa0WsBGvgrJRyJIWDF2mvx96zkTuzQdxHiK9up7b7u79MVStCffPvwzu9csidc6DIt1u7hodlnI+zGsn8Sbw6Z38hxTcNYpd2vmrrO7TcLiDtaymjcmuZC6azyH+tF9noaAATC7XRb/9aExIc70O2XxEgRj/gNyZXsn51mo3pcFQjqarSfD4nbSR/r6VTq+4H+oP3MKq0lnb4E3ALraOxGe/pmHoTJzAF5TAKJh+NxxX+ZcNl01mzpjt3qJHof46DoyD91nCwxbRLcfdNDf15cobLs2jjRBz2FkWDYvUw52HeXZQckNbawMRQ1Vg/md+UNVhoIa1+lBz31ZG0CwEghiaZGixqQLw+JJ/zyvDDf2zgzA4kKBxQ/OPGPkEGVpeheH0lo1lyYQJ3y+oS3HyRp5daEKnmNmzJ0ka5yTonfPxHa2VjRf20ngX026a2HE1tl3kK/KrZ
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc-secret
      namespace: argocd
