---
- name: Install SELinux policies for intel gpu device plugin
  ansible.builtin.copy:
    src: intel_gpu_selinux.te
    dest: /tmp/intel_gpu_selinux.te
    owner: root
    group: root
    mode: "0644"
  tags:
    - selinux
    - intel_gpu

- name: Compile SELinux module for intel gpu device plugin
  ansible.builtin.command:
    cmd: checkmodule -M -m -o /tmp/intel_gpu_selinux.mod /tmp/intel_gpu_selinux.te
  changed_when: true
  tags:
    - selinux
    - intel_gpu

- name: Package SELinux module for intel gpu device plugin
  ansible.builtin.command:
    cmd: semodule_package -o /tmp/intel_gpu_selinux.pp -m /tmp/intel_gpu_selinux.mod
  changed_when: true
  tags:
    - selinux
    - intel_gpu

- name: Install SELinux module for intel gpu device plugin
  ansible.builtin.command:
    cmd: semodule -i /tmp/intel_gpu_selinux.pp
  changed_when: true
  become: true
  tags:
    - selinux
    - intel_gpu
