name: searxng

services:
  chown:
    image: ghcr.io/vegops/chown:latest
    container_name: searxng_chown_1
    volumes:
      - ${APP_DATA_DIR}/searxng:/chown
    command: "-R 977:977 /chown"

  app:
    image: ghcr.io/searxng/searxng:2026.6.15-cf1410af8@sha256:37a8cc7769c4721b8f252ba935de8f01b7918e58d26b1be18dc87b5330fda65b
    container_name: searxng_app_1
    depends_on:
      chown:
        condition: service_completed_successfully
    user: 977:977
    ports:
      - 5147:8080
    volumes:
      - ${APP_DATA_DIR}/searxng/etc:/etc/searxng:rw
      - cache:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - SEARXNG_SECRET=${SEARXNG_SECRET:-ultrasecretkey}
      - SEARXNG_VALKEY_URL=${SEARXNG_VALKEY_URL:-valkey://valkey:6379/0}
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      # Public Resource Configuration
      - pangolin.public-resources.searxng.name=searxng
      - pangolin.public-resources.searxng.full-domain=${SEARXNG_HOSTNAME}
      - pangolin.public-resources.searxng.protocol=http
      # Target Configuration - Override to Host Hairpin
      - pangolin.public-resources.searxng.targets[0].method=http
      - pangolin.public-resources.searxng.targets[0].hostname=127.0.0.1
      - pangolin.public-resources.searxng.targets[0].port=5147
      # Health Check Configuration
      - pangolin.public-resources.searxng.targets[0].healthcheck.enabled=true
      - pangolin.public-resources.searxng.targets[0].healthcheck.hostname=127.0.0.1
      - pangolin.public-resources.searxng.targets[0].healthcheck.port=5147
      - pangolin.public-resources.searxng.targets[0].healthcheck.path=/healthz
      - pangolin.public-resources.searxng.targets[0].healthcheck.headers[0].name=X-Real-IP
      - pangolin.public-resources.searxng.targets[0].healthcheck.headers[0].value=127.0.0.1
    restart: unless-stopped

  valkey:
    image: docker.io/valkey/valkey:9-alpine@sha256:a35428eba9043cc0b79dbe54100f0c92784f2de00ad09b01182bfb1c5c83d1bd
    container_name: searxng_valkey_1
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - valkey:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: unless-stopped

volumes:
  cache:
  valkey:
