---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: homelab-runner
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/actions-runner-system/homelab
      recursive: false
  targets:
    - name: homelab-runner-secret
      namespace: actions-runner-system
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          github_app_id: "{{ .ACTIONS_RUNNER_APP_ID.Value }}"
          github_app_installation_id: "{{ .ACTIONS_RUNNER_INSTALLATION_ID.Value }}"
          github_app_private_key: "{{ .ACTIONS_RUNNER_PRIVATE_KEY.Value }}"
