apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-aio-apache
  namespace: nextcloud
spec:
  template:
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  io.kompose.service: nextcloud-aio-nextcloud
              topologyKey: kubernetes.io/hostname
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nextcloud-aio-apache
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
              add: [NET_BIND_SERVICE]
          volumeMounts:
            - name: nextcloud-aio-nextcloud
              mountPath: /var/www/html
              readOnly: true
