apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-aio-database
  namespace: nextcloud
spec:
  template:
    metadata:
      annotations:
        secret.reloader.stakater.com/reload: nextcloud-secret
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: init-subpath
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
      containers:
        - name: nextcloud-aio-database
          env:
            - name: POSTGRES_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: DATABASE_PASSWORD
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 2Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
