apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-aio-fulltextsearch
  namespace: nextcloud
spec:
  template:
    metadata:
      annotations:
        secret.reloader.stakater.com/reload: nextcloud-secret
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: init-volumes
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
      containers:
        - name: nextcloud-aio-fulltextsearch
          env:
            - name: ELASTIC_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: FULLTEXTSEARCH_PASSWORD
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
