apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-aio-nextcloud
  namespace: nextcloud
spec:
  template:
    metadata:
      annotations:
        secret.reloader.stakater.com/reload: nextcloud-secret
    spec:
      securityContext:
        fsGroup: 33
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: init-volumes
          command:
            - /bin/sh
            - -eu
            - -c
          args:
            - chmod 0770 /nextcloud-aio-nextcloud /nextcloud-aio-nextcloud-trusted-cacerts
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: nextcloud-aio-nextcloud
              mountPath: /nextcloud-aio-nextcloud
              subPath: nextcloud/app
      containers:
        - name: nextcloud-aio-nextcloud
          env:
            - name: ADMIN_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: NEXTCLOUD_ADMIN_PASSWORD
            - name: EUROOFFICE_SECRET
              value: null
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: EUROOFFICE_SECRET
            - name: FULLTEXTSEARCH_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: FULLTEXTSEARCH_PASSWORD
            - name: IMAGINARY_SECRET
              value: null
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: IMAGINARY_SECRET
            - name: POSTGRES_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: DATABASE_PASSWORD
            - name: REDIS_HOST_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secret
                  key: REDIS_PASSWORD
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - name: nextcloud-aio-nextcloud
              mountPath: /var/www/html
              subPath: nextcloud/app
            - name: nextcloud-aio-nextcloud-data
              mountPath: /mnt/ncdata
              subPath: nextcloud/data
