apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-aio-notify-push
  namespace: nextcloud
spec:
  template:
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  io.kompose.service: nextcloud-aio-nextcloud
              topologyKey: kubernetes.io/hostname
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: nextcloud-aio-notify-push
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: nextcloud-aio-nextcloud
              mountPath: /var/www/html
              readOnly: true
