---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: b2-cnpg-credentials
  namespace: auth
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgDNEO05mfDhF0HU3i/y5KNgw2uLN3LucVhsIQbexU2geGOJH+BW0fKvTulxg5Y9Fq/G4/JHyGG8uSxbbs3Vpc1MqtQLtQCIHGyjaxDrC1ndyh8hZHDCkydU9FsdNxvrZVDQVrwWu1FUurysEzd+H+daAAc3EIrJOOfi+A64p+jbpe5thS+rkeap/8Ny7IiuWeGkwrwqu+nr0ktBY8BhhMPO/nFVwxocx3XhqgpZ/ho5baEnaZw0hmYYCTiHvZGXXsqo53fXtSHxsq09o+jsfDk5I1BaFujb2uBut6/LssmQe6GJZdrqnOITsKp7VfCLDHcLnmYAFy5oG/aHb9w2YKp1r7PKrzP1Kn0uF+8RzDXiGO3r/gS/rwBuEsVkdu+O89FAWS2QYFKh1VVg23g7MnJI10mE4+9c/zN8gOARvBf5ivyasW3aIvp4SJgjKHIC+UxILW6jrW06VY2dFai3BedW5AVrGkRRdzHn3EQtFN2ybR5w3j0s9Vne18GR57VwJgBghdnQz9b8vePLHo0z3SQPAPkUwmYTnyqFbgioPyHSpDFBVQu+Qx3y59mYjULs3SljJZKlCInF64EbVHBf442057RgyIIAsXLjfosm9FpfTeERmw21/ZAYnw0CSQP6Wix6kdDtUiMMZtFPIgrC8Bs1+0G0FJ7HfRT4M+NZpcvuVDIa22hiNAd/andpeJpOb2AT59m2f6EIhx6QErlOJgj2F4A6W+5KQGu8
    AWS_SECRET_ACCESS_KEY: AgBSIke7hHdMqmsAehUIhyTsCKcrllrTbRA8vcqoo+XGd0aA0JpyP6+KPVPH2BsPAXf/0bgv5xULfYmpD04pXbC4EJjkyBMRw3GxHvLUsSKwQLSlkbet+4cPCVuLTtEv9OlOot5mlJWMlyqhCx933pBw6LyOoK+0YQyu5GyAPf9qOY8UvosxT6Kbp6utGLygDH6pua9TbpaapIeBoTSmIuwyjcxCaKJ+E37mTNtuNc45m0YaebaYV1DNKsHq21rwMMGlHyzN2KsKfbTB73iA9cwS13jXIu9EyM7Jn6JrjuPBNQ4+ujGKIfRcYIw7fjD4IZ7FSKUTjg7dNuPlaDqE50xEpGOPTkWRnz0jQWzMpvoePxoWTvuNgkXGV6YbK49nT6ZQbkdU44Ld2wQL2sxd3HW7wPmcZEGTqQ2pmd1u0NlNFvbYmncgy8708OD4NGiot5S1cRvYOR/nYGtPjrws2VEEW9iiMU0H594kFnCKTTlWRQMe9wEj+SKfV6nkbbtnYS4Ft5Vsm1w/GtlXMQ669C0xcY4XG0Ur4W/2g9hF8D0zFASO8VQ41qI6Zei9qNjvw02wuR3POs+dkC52IazRoNpwh7iV0f13dLb9xHtFn03nQkL7ywmpsPQ8Lt2HF4PI0kD3NPQtkRZ6eFIFON2or3D40F3SwXd13/+CN7hkxFWmRjeEQ8b+BhYL9THQfyNWK1zSnzow3FcO4n6Z1tcGu91NsjNaJSDGJmgjd7sQ1VGG
  template:
    metadata:
      name: b2-cnpg-credentials
      namespace: auth
