---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: b2-cnpg-credentials
  namespace: auth
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgB0OSZrmB/fzO22clR8Pt6yzTH5quub2pmIqUjm1ytcFaVqQv+SCj2E9iwoK0XRyEeMAbynxmekAUBpxVCo1imaB8X7CQ+SsG3aNMGR546IKsSJkCx96piLRCiLgvpwxw8LpK62QI6xHppEK5GuRHVwf6WE49vHSTG6fNnHx1VYIhHF/ZogiM1MAW/yusbavNLdzwUCW7STsXlhPJOAkcCl7/fiYtImr0afjM3mRwNcAHjbw0/YrhX2Ws+OyWyD+19CXABkD1phaKLqoC3XwoZ8LhRcQxR7AeQq/e7lp4UXuLq0r/2/J9j74FJQbhc77LWMzXJSyr9K02DWYv5U+NyJthpzjdbcurWjRjxdyCeQHTxwR1QttT7cRAhOAZ+vKsRibvgyWgNdmZfBsgy/29p3KpHOJeuVOmOADoQ4p+/LPCuieuV6e/ledFx5OpiWLzCtIj5hGAnV6CDQYD30+YB8mVCs9psqwPHHcOdKAIdS2P0H+OFnNNw/CLYUz9XXSPz3Cuctak7adkSSNT/ul7iy8ufmdABO6INGqSwTQFiot2RArhmCkgbYMV+EyoCHCjxiZI0FuXpq7pD8p2CzPqfAclrFINyfZR8Fhj9A3TfdMmayUWdsg8bnKEq+Gx5Z7bKV+nNqcN1ShD7UUBl/6dv/aeqi1mpzNGaieH0c7ZSwC81ofTeT/PH+BgOzfnEMpURhGMmuN3rIU7pDzzFc9A2UZFgDwwCHwbp2
    AWS_SECRET_ACCESS_KEY: AgB+bB9vD3izlDdO3k5akDDqTxOYA3fDlpIz0LfmcHRvQFAfE4rNgWX2OeoCFj7lvaT7lQ4HzAiJhxyY1A6s/wHffw2e2jR+A7rJMdfPC8qOQVAPBQwMNG0gB+is3trm75pEATKxbBJ0E+S8t/N1S4T0cNEliE7ft1O75nqMEBgtjRENXwwUlhxWS3ddcrv9lpVAMNozIePZ+f1NtMGoUmpfj8Um2S9eLPqBwrIdxaHflLfXVYYLtRE8Ntn6P1b+eWAf+ApkXLKrEgCj2fa3N2AOenC0biQFtMq58WZaEmZt2eaQ41tU7qjkjvI41yvSiq+1o3uW36qQFoRUy+mj3LeL3yYCEjnT1wZ8qDShrNGsUqqbHFRY2SpiVxhZaUzwvgCmySNGzPVoUROoMdXa4yxAAsZlaDC3RyBwWlKj6qH20ND2jGUeyuJrki3j9SFpaf19Oo7mzZDCQGE5W9/Q4PjOgYqBdxG7Jjg4+A4dF+/vDFgXRoYAn0atJId3BMALE69SoLkC6JjTi/KjWUcKVCOBosOnSy4opEWK+A5xZ0CG/AfZ0Bd/Ev0g6pSTpJJg+cL1viiG4z/NsqJfflI3vWuiA4OpbtmHeeda29I/u17VCKY1ZykI2xswvvM766F2ufNHyItDZJpjj7dx8bfzk0FpQ1X4ihQwkPQEQHmjkHyjMuusg6JUck8MylEuOBYqzbOduhhfGXYg23EUDM56pkZE2vM0Px/vc5I9NXiOJpgX
  template:
    metadata:
      name: b2-cnpg-credentials
      namespace: auth
