---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-credentials
  namespace: auth
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCvgclAvmK7YBn30NK0v6ElkNK3i/OHm5NHC/VyduCJI+rdz+6Sq0prJR4AFLoVV+LU/5k/ql03iEVHrTMgy/mpO7i5ikMGK1FjOmhdfC/bEsWEZYwkDQz+Qd5q54WESTuegD1sZYMlLwDTaOnqENB4CQonmYJxrLRzKLqqkrNTGcNMOs9fFuuixSGx0krCe/Zjjf5vciabzcZGB5PNB52/ESB+c4Jz+cvW0DRo/l6YoZk+n/Bme7SZdnJNkXyZC8rxfpDkFBOQsrO0O1bkJX/gDUdKPBYFKLVTxYZACgjS8YymdQAv6/6thsDhBRxue0jvZWAEUg/me3ph2B0Fuxr+6jliWN42VFxP8zE7vxhhS5sRwdmWK0hTUC+JRosgh4vXmagqX5nKOl9JtuAPp9qwBn4b8spW6tOBVrw+w/jFDn2s/ljddMEJniw3O/HG49yzgrDXI2NT5uyD9uD7D2LNyY6od8BGwK22LBwkUXGU4ghE3lH/VGl4hA7W3M6mzXH959RpV9V8TgH/PSJ32uK15yBzC3A7H7D58LRiRxL+4R5KSxrfK0PHc8zOnAtQt+jHn8Q7pUkmBVcAH4SG6J7iYqnlrlZqzLbqrgO4pdhAM0HnHsVXsP9lVTRuQYKi8VEJcpWk5wkpDjF3glLN/bcKOIWok2GaOsZRGOlAUjN9wAZI8sDX7s3mNPCAso8K3r1i8S8SQ5Lb1KIfUmV8KZpM7lvUbg==
    AWS_SECRET_ACCESS_KEY: AgBSjnUllDeq0zpkAmhZdlllZWmChBZGC6OnRywA93FiptJ2ewPWnLt1EHtxCsA8W/ToPHvxwhpPQId8yL91+7Stnb1DbHnFIhnRCJYDFLr+DlFy+6uwQ4cjWkj7AGBeVY/gj01ri5MEPiWv52ouF3p//GT/ndyHzQ0mwcBRpIntsCJvG+YCH5b5hSu4r5f765CI1rJH49RhA5wUOVlCpptGucmJxP3+3CYtLh1JDN90VeXKFBCc718B9AZ/ZMXecgLctByqbVLOShb7NywoRj4H+e8hycpLH+XjBC2QJM1MrE6oGdlOcPqdbUeAiQIfP1m18HvbyhiZ2+AKDeMgIsYU59Bk/fcn7hc1nY/sJ40DuGF8lmLyJ3GqDHSX0XYql/4mby7iRjpQ221ZOCRXaEeoeCDmFZ/cp58PPlyj2THAI2eE5oQNYrTJFfUPR2F+G90qz5iy2/y+tQHKsfL5i7Ha/W5WIT9INcNscz4T0gH8gV1w6nAgSQahKblPCKr2rtOrwHjiCQQHWaPLiGRcJ6o5ZEkFgaS2qr/jcl5v8ZdkJZ7cJlxQeqcgKzTr5ziwfI9D1APJr4E0yP1PvoK5Udfhuv/QchwLtuVGxBRlx22YPi24SYeDL+x7L5z8q6mf/z8S5cJtY6+ZATjB7b5h/zVRkMDjJlhQLw5P5e/C57CVczeVJDBTRDuvCts4+HdtKDmTzqUiVA+0Sk5hbsiiREk4H+Cc0mKi4BEkfVgA7qi1NaNts8D9qbm0
  template:
    metadata:
      name: rustfs-credentials
      namespace: auth
