---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-credentials
  namespace: auth
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAVwXoeBqM/0hvrxqme0JK5JLFnyNQZgWnf3Ma7fS223QrijnlOKEg/RZ16kdDglD8hPzSnnXNQEIWsNxHKMLd1bqaNiSGzaCt71lA1p2/QPjXaENUAmHefonSOHrAzTn18wm6ayGSR20SFyHLgG0Ym9PX2CGpEurGU7trIDinB/w51Gx0gVw8Io74LXyGSC8GAIJiNrlBU9D9x/h0z/n7U9JwTiDnVBtAirAEuUOBIuvym0ZhcclsUXyehfGAUhTek1vtJgkojlAaFc+EXLqPCAPqnvz1cD/g0Cyi7d4SiPLDomZsvgIk3U3bn4ZkP3Fvo563NC4fW+iK8bmNJscEvJkpEoI357tpGh0qkyzlOj7WTeEbtXPjFEz41FlvfHGuGWlmkP3T4ROZ1Ca8MXHzO2Dzk1guUxwmsE8EoCOXlHItsMJtSvpbLl7WoXq8GpcF0jGOs2KieVPybu6e07tgAlcGUVat+n0MUHVS6AE1TOntMS3OC2pg7zG29UlTEaLkFxcaWMs3fvkqIdPcca3Or3cZgKftt1aufBSAk4+DGUdYCAyhssxYtAV7OyCQpfwSmXSOPefHofHOHt2t6jEXhg5mg2NXj1t8D4rUPnNZQuJK3u7olfEGFaLAR7kwJ8CVMPN6JqDa2vb8/3RTdYcbhzeycfr/SPjmH50UGUeVQKQMrro9hvYAlyheN5++sr+6cRHg/EnvezkG0dzJ1GXTMkzLKFw==
    AWS_SECRET_ACCESS_KEY: AgBqYwMpRNgG57t465F2B1ntViXrwPv3U2s4nfuQFgLBlMo1o8Cz3OSzd8yqq3s3b5UA7pao+NHT/pi7nusmmCObi/TyevVX1kAJGhR3+8wiaquBi8gbZULoDcUCSOQtrQRwgds6r+KLr/u35M5E6t7Ne06X4qiojVu/WljG97nI2Dh+IPg2M0Oghh4zp0RcgddxV0lClE+lng4iSWzkfx3m6VxAhkYWPb6MY6XcZBodOszLvqdZocIXeBDm/ZmGXpXyeUQdC0N37J5femqna2vChHp8IEdiUKX0qu8I1RHw4EBpujaIClBbM0+kfemlUX5UcVAHZCmdJ+aqdzyFD61+A7cChOtcgRG22ZJRXNvXURMjUff0vYW9p8xaafQn654U/1vtzJ8wdSHssrO5p9ChG4WUnLpGymYuPOahBRze5QD/h/DmedUEKY8jbwgpHOQ4GIODTkNv35dBZ02WfGz9LuiM8bZITngXF7gOrNyJdWTfyDRVukSJOcUYIxcXc4RXbElFgtUj8x5gSE595GgwP8lLEGIn0vjoziaAvr5gihz9+KYh2WwxZW8Pwlh37HkVx+Lr+HDEegLjKmy9DR9cRuvEQDbCB1D5bPHqTRE4d/oG/wp62UkCIyfE0VnDQGdL3Q2+kKM6UJwHzTICikmPp/eln6MJYHYTCKlYPmsPEC3rADFgGpDgTAYxorSqw69fsZpiZIZhgkRsMobxZoEXNmOhZUGJdeQYbQEgFJDFMC/LG64Bhmzg
  template:
    metadata:
      name: rustfs-credentials
      namespace: auth
