---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-credentials
  namespace: auth
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBtvxUVgiDOFzTBvVGq15+3aXJLhUve2LomHjUG9UIeLnIVfAdZFFWePVEJmeRuQOZ8QDyuM2nOlQzSCYvYJae6Y//HcyYVPYqKEPSEc98Ik/QQuK8sCegBHyuZDpOcQMxRjFYfvCwo60RkqykRa6z6CrI9GCHTIoAzxshYr2IkUX6+rZ+axKb5eqDTPr9pxk2xkaGul/KEGnY29hjF6spvFY4cFtuynegQU0/KoMQnhiUriKTu/mapub+gg+URfnXN/hOFgU+9kPOPUwcaq4yoTcyPEJrGiQ+w6ECHDsqqPPFPiEpDVOxkKb0psWjxs2tGUI32L0FxKBeMzPkeErGWrmhndQW2gVO0vas+/RT3pnmTl9weMiWRp6cTZx9f5/5HyFVi7yRIIn1dUdM8AFUVnWXlDlsMomLDE/lDqDBm7iHaniIjS1+arcmVzeQ0EXtogDQ7tqksL4qTXjyxd/ayvy9pTbOKQmXvK3bu3jWjYt63VO7V+uxFEL6oWIyOe7DXYd+gRQX54bQ/C6Iv3aWy+KvIlWlLSo1/zBuOFn7TsNgvY3YNPqolsC5JPJUBk1MqhJgIa+fT6yc2ARdKExlVTtUUeBgWbClpMAJwmpbBWkNFE49+LNE+zRbrn5RUtdMh68kYimY+7W7Ils9lszqOQmK3xgTnDuXXTelinCArfTzMKnv/YKx9MstTeggiV+rC+dg8LzdGPCimavfwoML1TiOoiw==
    AWS_SECRET_ACCESS_KEY: AgCLGdPdsOdIwS/kUHf1pPZhpZH37xgVAkd5CzAl2+NlmPU/c10B1zgXJT3qbl95HSyRSlbpBsqdfcNeTuJTeXiT8UMg2Qxx0550rmETshMOHsYwdg4K0dYBdJKNqFJq0ZgnKG+Qa1uxU68bIIuzvLkn3PJAeXpLZGe2+W3SbqJaUPxBXRmnLYDqzqGejqdVoQPh8BPIPzg1TxRQzy9zpd5byJRIDIJiACsZ07xy6dVV1XNcmdQX4zvi9tBR++4NGRMEN2SCYGS5JnO+GIxBETWv/Qg7eFZxiR4vw2r7glyf2OoNCIt8tpR/KsEIalnb61xbDyna7RcCUM2QIgv9yF85HS9n/p6OKFXoeObM7W9QNw8TJz78z/2gbejX2rW+qJhBlW/KPAc2k+uIOtCLGvCwMqVXzpl1XZwmxDkSMfmpL4f3y0ijC1r7OGMv/88fmpi48wBUx2Vo+cca8MHFwahTGEChcRBZhm/Q/fDu9mA/bLikKhBAr7oiFRca4R74iUqlSPz5tm97zDEli9rVjryNjGe0A7hD512KQgmo+hOeKKisWrRKMiQt+bNZ0iNwXD1go4K4wkluHesdqAabiYV//FSMfaxy9ReVkJfGDt+xtxD91xnjoBDGWx8zirXse6ddH+IKIc06RR38bfqJ4MZsFcPR4piI2w+/Sl513EkCnxtqynAsJI9PQp6MpwtaQyd1H4Fr6Jv1NTfzaDzGN6yySrEuVI1xxswY3D4o3MZJRv9EBWKe6V5l
  template:
    metadata:
      name: rustfs-credentials
      namespace: auth
