---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: alertmanager
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /pushover
      recursive: false
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /gatus
      recursive: false
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/o11y/alertmanager
      recursive: false
  targets:
    - name: alertmanager-secret
      namespace: o11y
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          ALERTMANAGER_PUSHOVER_TOKEN: "{{ .ALERTMANAGER_PUSHOVER_TOKEN.Value }}"
          PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY.Value }}"
          CADI_HOME_HEARTBEAT_TOKEN: "{{ .CADI_HOME_HEARTBEAT_TOKEN.Value }}"
          CADI_HOME_HEARTBEAT_URL: "https://{{ .GATUS_CADI_STATUS_HOSTNAME.Value }}/api/v1/endpoints/home_heartbeat/external?success=true"
