apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: applications
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - git:
        repoURL: &repoURL https://github.com/eudaldgr/homelab
        revision: &revision main
        directories:
          - path: k8s/applications/*/overlays/*
  template:
    metadata:
      name: '{{ path[2] }}'
      namespace: argocd
      labels:
        app.kubernetes.io/component: 'static-applications'
        app.kubernetes.io/part-of: applications
    spec:
      project: applications
      source:
        repoURL: *repoURL
        targetRevision: *revision
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path[2] }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
