---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: smtp-relay
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/default/smtp-relay
      recursive: false
  targets:
    - name: smtp-relay-secret
      namespace: default
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          SMTP_RELAY_HOSTNAME: "{{ .SMTP_RELAY_HOSTNAME.Value }}"
          SMTP_RELAY_PASSWORD: "{{ .SMTP_RELAY_PASSWORD.Value }}"
          SMTP_RELAY_SERVER: "{{ .SMTP_RELAY_SERVER.Value }}"
          SMTP_RELAY_USERNAME: "{{ .SMTP_RELAY_USERNAME.Value }}"
