---
services:
  testnet3:
    image: ghcr.io/eudaldgr/fulcrum:latest
    container_name: fulcrum_testnet3_1
    user: "${PUID}:${PGID}"
    command:
      [
        "--bitcoind",
        "bitcoind-core_testnet3_1:18332",
        "--rpccookie",
        "/run/bitcoind/.cookie",
      ]
    ports:
      - "60001:50001"
      # - "60002:50002"
    volumes:
      - ${APP_DATA_DIR}/fulcrum/data/testnet3:/data
      - ${APP_DATA_DIR}/bitcoind-core/data/testnet3:/run/bitcoind:ro
    networks: [bitcoin-net]
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped

  testnet4:
    image: ghcr.io/eudaldgr/fulcrum:latest
    container_name: fulcrum_testnet4_1
    user: "${PUID}:${PGID}"
    command:
      [
        "--bitcoind",
        "bitcoind-core_testnet4_1:48332",
        "--rpccookie",
        "/run/bitcoind/.cookie",
      ]
    ports:
      - "60011:50001"
      # - "60012:50002"
    volumes:
      - ${APP_DATA_DIR}/fulcrum/data/testnet4:/data
      - ${APP_DATA_DIR}/bitcoind-core/data/testnet4:/run/bitcoind:ro
    networks: [bitcoin-net]
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped

  signet:
    image: ghcr.io/eudaldgr/fulcrum:latest
    container_name: fulcrum_signet_1
    user: "${PUID}:${PGID}"
    command:
      [
        "--bitcoind",
        "bitcoind-core_signet_1:38332",
        "--rpccookie",
        "/run/bitcoind/.cookie",
      ]
    ports:
      - "60021:50001"
      # - "60022:50002"
    volumes:
      - ${APP_DATA_DIR}/fulcrum/data/signet:/data
      - ${APP_DATA_DIR}/bitcoind-core/data/signet:/run/bitcoind:ro
    networks: [bitcoin-net]
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped

networks:
  bitcoin-net:
    external: true
    name: bitcoin-net
