apiVersion: v1
kind: Namespace
metadata:
  name: system-upgrade
  labels:
    app.kubernetes.io/name: tuppr
    app.kubernetes.io/part-of: cluster-lifecycle
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
