---
- name: Load kernel modules for k3s
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - br_netfilter
    - overlay
  tags: system

- name: Configure sysctl for k3s
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  loop:
    - name: net.bridge.bridge-nf-call-iptables
      value: "1"
    - name: net.bridge.bridge-nf-call-ip6tables
      value: "1"
    - name: net.ipv4.ip_forward
      value: "1"
    - name: net.ipv6.conf.all.forwarding
      value: "1"
  tags: sysctl

- name: Create k3s directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/rancher/k3s
    - /var/lib/rancher/k3s
  tags: k3s

- name: Copy SELinux policy file for k3s
  ansible.builtin.copy:
    src: k3s_homelab_selinux.te
    dest: /root/k3s_homelab_selinux.te
    owner: root
    group: root
    mode: "0644"
  tags: selinux

- name: Compile SELinux module for k3s
  ansible.builtin.command:
    cmd: >
      checkmodule -M -m -o /root/k3s_homelab_selinux.mod
      /root/k3s_homelab_selinux.te
  args:
    creates: /root/k3s_homelab_selinux.mod
  tags: selinux

- name: Create SELinux policy package for k3s
  ansible.builtin.command:
    cmd: >
      semodule_package -o /root/k3s_homelab_selinux.pp
      -m /root/k3s_homelab_selinux.mod
  args:
    creates: /root/k3s_homelab_selinux.pp
  tags: selinux

- name: Check if k3s SELinux module exists
  ansible.builtin.stat:
    path: /root/k3s_homelab_selinux.pp
  register: selinux_policy_file
  tags: selinux

- name: List installed SELinux modules
  ansible.builtin.command: semodule -l
  register: selinux_modules
  changed_when: false
  tags: selinux

- name: Install SELinux module for k3s
  ansible.builtin.command:
    cmd: semodule -i /root/k3s_homelab_selinux.pp
  changed_when: true
  when:
    - selinux_policy_file.stat.exists
    - "'k3s_homelab_selinux' not in selinux_modules.stdout"
  tags: selinux

- name: Set SELinux boolean for k3s use of Samba
  ansible.builtin.command:
    cmd: setsebool -P virt_use_samba 1
  changed_when: false
  tags: selinux

- name: Set SELinux boolean for k3s use of kernel load modules
  ansible.builtin.command:
    cmd: setsebool -P domain_kernel_load_modules 1
  changed_when: false
  tags: selinux
