name: garage

services:
  chown:
    image: ghcr.io/vegops/chown:latest
    container_name: garage_chown_1
    volumes:
      - ${S3_DATA_DIR}/garage:/chown
    command: "-R 65532:65532 /chown"

  app:
    image: ghcr.io/vegops/garage:2.3.0-r0@sha256:f2acc76349e8d1390bd94c9700071366cded2b600c1f4ef53f8996192a364a47
    container_name: garage_app_1
    user: 65532:65532
    depends_on:
      chown:
        condition: service_completed_successfully
    environment:
      TZ: ${TZ}
      GARAGE_RPC_SECRET: ${GARAGE_RPC_SECRET}
      GARAGE_ADMIN_TOKEN: ${GARAGE_ADMIN_TOKEN}
    healthcheck:
      test: ["CMD", "/usr/bin/garage", "status"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s
    volumes:
      - ${S3_DATA_DIR}/garage/etc:/garage/etc
      - ${S3_DATA_DIR}/garage/var:/garage/var
    ports:
      - 3900:3900
    restart: unless-stopped

  webui:
    image: ghcr.io/vegops/garage-webui:1.1.0-r0@sha256:668e60b8a0de38c21ff918b4e7f63b4d36c22769c0d4d3c7a705217a6f9fc1be
    container_name: garage_webui_1
    depends_on:
      app:
        condition: service_healthy
    environment:
      CONFIG_PATH: /tmp/missing.toml
      API_BASE_URL: http://app:3903
      API_ADMIN_KEY: ${GARAGE_ADMIN_TOKEN}
      S3_REGION: garage
      S3_ENDPOINT_URL: http://app:3900
    ports:
      - 3909:3909
    tmpfs:
      - /tmp
    restart: unless-stopped
