---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4@sha256:6c0948b42c149e36bb3dbc0b64d36c77b2d3c9dccf1b424c4f72af1e57ba0c21
    container_name: arrstack_radarr_1
    user: "${LSCR_UID}:${LSCR_GID}"
    userns_mode: "keep-id:uid=${LSCR_UID},gid=${LSCR_GID}"
    environment:
      - TZ=${TZ}
    volumes:
      - ${MEDIA_DATA_DIR:-/}:/data
      - ${APP_DATA_DIR}/arrstack/radarr:/config
    ports:
      - 7878:7878
    labels:
      # Public Resource Configuration
      - pangolin.proxy-resources.radarr.name=radarr
      - pangolin.proxy-resources.radarr.full-domain=${RADARR_HOSTNAME}
      - pangolin.proxy-resources.radarr.protocol=http
      # Auth: protect all but API
      - pangolin.proxy-resources.radarr.auth.sso-enabled=true
      - pangolin.proxy-resources.radarr.rules[0].action=allow
      - pangolin.proxy-resources.radarr.rules[0].match=path
      - pangolin.proxy-resources.radarr.rules[0].value=/api/*
      # Target Configuration - Override to Host Hairpin
      - pangolin.proxy-resources.radarr.targets[0].method=http
      - pangolin.proxy-resources.radarr.targets[0].hostname=host.containers.internal
      - pangolin.proxy-resources.radarr.targets[0].port=7878
      # Health Check Configuration
      - pangolin.proxy-resources.radarr.targets[0].healthcheck.enabled=true
      - pangolin.proxy-resources.radarr.targets[0].healthcheck.hostname=host.containers.internal
      - pangolin.proxy-resources.radarr.targets[0].healthcheck.port=7878
      - pangolin.proxy-resources.radarr.targets[0].healthcheck.path=/
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.16@sha256:60e5edcac39172294ad22d55d1b08c2c0a9fe658cad2f2c4d742ae017d7874de
    container_name: arrstack_sonarr_1
    user: "${LSCR_UID}:${LSCR_GID}"
    userns_mode: "keep-id:uid=${LSCR_UID},gid=${LSCR_GID}"
    environment:
      - TZ=${TZ}
    volumes:
      - ${MEDIA_DATA_DIR:-/}:/data
      - ${APP_DATA_DIR}/arrstack/sonarr:/config
    ports:
      - 8989:8989
    labels:
      # Public Resource Configuration
      - pangolin.proxy-resources.sonarr.name=sonarr
      - pangolin.proxy-resources.sonarr.full-domain=${SONARR_HOSTNAME}
      - pangolin.proxy-resources.sonarr.protocol=http
      # Auth: protect all but API
      - pangolin.proxy-resources.sonarr.auth.sso-enabled=true
      - pangolin.proxy-resources.sonarr.rules[0].action=allow
      - pangolin.proxy-resources.sonarr.rules[0].match=path
      - pangolin.proxy-resources.sonarr.rules[0].value=/api/*
      # Target Configuration - Override to Host Hairpin
      - pangolin.proxy-resources.sonarr.targets[0].method=http
      - pangolin.proxy-resources.sonarr.targets[0].hostname=host.containers.internal
      - pangolin.proxy-resources.sonarr.targets[0].port=8989
      # Health Check Configuration
      - pangolin.proxy-resources.sonarr.targets[0].healthcheck.enabled=true
      - pangolin.proxy-resources.sonarr.targets[0].healthcheck.hostname=host.containers.internal
      - pangolin.proxy-resources.sonarr.targets[0].healthcheck.port=8989
      - pangolin.proxy-resources.sonarr.targets[0].healthcheck.path=/
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.0@sha256:ede2bb17350cc97a0d3f24389aa91803f655eac29aa022c77a71f4a61cc621e4
    container_name: arrstack_lidarr_1
    user: "${LSCR_UID}:${LSCR_GID}"
    userns_mode: "keep-id:uid=${LSCR_UID},gid=${LSCR_GID}"
    environment:
      - TZ=${TZ}
    volumes:
      - ${MEDIA_DATA_DIR:-/}:/data
      - ${APP_DATA_DIR}/arrstack/lidarr:/config
    ports:
      - 8686:8686
    labels:
      # Public Resource Configuration
      - pangolin.proxy-resources.lidarr.name=lidarr
      - pangolin.proxy-resources.lidarr.full-domain=${LIDARR_HOSTNAME}
      - pangolin.proxy-resources.lidarr.protocol=http
      # Auth: protect all but API
      - pangolin.proxy-resources.lidarr.auth.sso-enabled=true
      - pangolin.proxy-resources.lidarr.rules[0].action=allow
      - pangolin.proxy-resources.lidarr.rules[0].match=path
      - pangolin.proxy-resources.lidarr.rules[0].value=/api/*
      # Target Configuration - Override to Host Hairpin
      - pangolin.proxy-resources.lidarr.targets[0].method=http
      - pangolin.proxy-resources.lidarr.targets[0].hostname=host.containers.internal
      - pangolin.proxy-resources.lidarr.targets[0].port=8686
      # Health Check Configuration
      - pangolin.proxy-resources.lidarr.targets[0].healthcheck.enabled=true
      - pangolin.proxy-resources.lidarr.targets[0].healthcheck.hostname=host.containers.internal
      - pangolin.proxy-resources.lidarr.targets[0].healthcheck.port=8686
      - pangolin.proxy-resources.lidarr.targets[0].healthcheck.path=/
    restart: unless-stopped

  #  bazarr:
  #    image: lscr.io/linuxserver/bazarr:latest
  #    container_name: arrstack_bazarr_1
  #    user: 1000:1000
  #    environment:
  #      - TZ=${TZ}
  #    volumes:
  #      - ${MEDIA_DATA_DIR}/media:/data/media
  #      - ${APP_DATA_DIR}/arrstack/bazarr:/config
  #    ports:
  #      - 6767:6767
  #    restart: unless-stopped

  # readarr:
  #   image: lscr.io/linuxserver/readarr:develop
  #   container_name: arrstack_readarr_1
  #   user: 1000:1000
  #   environment:
  #     - TZ=${TZ}
  #   volumes:
  #     - ${MEDIA_DATA_DIR:-/}:/data
  #     - ${APP_DATA_DIR}/arrstack/readarr:/config
  #   ports:
  #     - 8787:8787
  #   restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.0@sha256:67a8aaedcfd6989f3030b937a6a07007310b1dfc7ee8df16d2cbfa48d1c1158c
    container_name: arrstack_prowlarr_1
    user: "${LSCR_UID}:${LSCR_GID}"
    userns_mode: "keep-id:uid=${LSCR_UID},gid=${LSCR_GID}"
    environment:
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/arrstack/prowlarr:/config
    ports:
      - 9696:9696
    labels:
      # Public Resource Configuration
      - pangolin.proxy-resources.prowlarr.name=prowlarr
      - pangolin.proxy-resources.prowlarr.full-domain=${PROWLARR_HOSTNAME}
      - pangolin.proxy-resources.prowlarr.protocol=http
      # Auth: protect all but API
      - pangolin.proxy-resources.prowlarr.auth.sso-enabled=true
      # Target Configuration - Override to Host Hairpin
      - pangolin.proxy-resources.prowlarr.targets[0].method=http
      - pangolin.proxy-resources.prowlarr.targets[0].hostname=host.containers.internal
      - pangolin.proxy-resources.prowlarr.targets[0].port=9696
      # Health Check Configuration
      - pangolin.proxy-resources.prowlarr.targets[0].healthcheck.enabled=true
      - pangolin.proxy-resources.prowlarr.targets[0].healthcheck.hostname=host.containers.internal
      - pangolin.proxy-resources.prowlarr.targets[0].healthcheck.port=9696
      - pangolin.proxy-resources.prowlarr.targets[0].healthcheck.path=/
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:7.5.2@sha256:2550848d43a453f2c6adf3582f2198ac719f76670691d76de0819053103ef2fb
    container_name: arrstack_recyclarr_1
    # user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/arrstack/recyclarr:/config
    restart: unless-stopped

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:release-5.1.4@sha256:432de4f8094308ebf2ce7fef8b8a1a0d3d654fdce993bbd9bb93ebccd5555c8b
    container_name: arrstack_qbittorrent_1
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      - UMASK=002
      - WEBUI_PORTS=8090/tcp,8090/udp
    mem_limit: 2048M
    volumes:
      - ${MEDIA_DATA_DIR}/torrents:/data/torrents
      - ${APP_DATA_DIR}/arrstack/qbittorrent:/config
    ports:
      - 65211:65211
      - 65211:65211/udp
      - 8090:8090
    labels:
      # Public Resource Configuration
      - pangolin.proxy-resources.qbittorrent.name=qbittorrent
      - pangolin.proxy-resources.qbittorrent.full-domain=${QBITTORRENT_HOSTNAME}
      - pangolin.proxy-resources.qbittorrent.protocol=http
      # Auth: protect all but API
      - pangolin.proxy-resources.qbittorrent.auth.sso-enabled=true
      # Target Configuration - Override to Host Hairpin
      - pangolin.proxy-resources.qbittorrent.targets[0].method=http
      - pangolin.proxy-resources.qbittorrent.targets[0].hostname=host.containers.internal
      - pangolin.proxy-resources.qbittorrent.targets[0].port=8090
      # Health Check Configuration
      - pangolin.proxy-resources.qbittorrent.targets[0].healthcheck.enabled=true
      - pangolin.proxy-resources.qbittorrent.targets[0].healthcheck.hostname=host.containers.internal
      - pangolin.proxy-resources.qbittorrent.targets[0].healthcheck.port=8090
      - pangolin.proxy-resources.qbittorrent.targets[0].healthcheck.path=/
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:1.34.0@sha256:f6a782e44742a02bdb6032d32ebb4e9615e261140f879be897b28cdb40ff800e
    container_name: arrstack_overseerr_1
    user: "${LSCR_UID}:${LSCR_GID}"
    userns_mode: "keep-id:uid=${LSCR_UID},gid=${LSCR_GID}"
    environment:
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/arrstack/overseerr:/config
    ports:
      - 5055:5055
    labels:
      # Public Resource Configuration
      - pangolin.proxy-resources.overseerr.name=overseerr
      - pangolin.proxy-resources.overseerr.full-domain=${OVERSEERR_HOSTNAME}
      - pangolin.proxy-resources.overseerr.protocol=http
      # Target Configuration - Override to Host Hairpin
      - pangolin.proxy-resources.overseerr.targets[0].method=http
      - pangolin.proxy-resources.overseerr.targets[0].hostname=host.containers.internal
      - pangolin.proxy-resources.overseerr.targets[0].port=5055
      # Health Check Configuration
      - pangolin.proxy-resources.overseerr.targets[0].healthcheck.enabled=true
      - pangolin.proxy-resources.overseerr.targets[0].healthcheck.hostname=host.containers.internal
      - pangolin.proxy-resources.overseerr.targets[0].healthcheck.port=5055
      - pangolin.proxy-resources.overseerr.targets[0].healthcheck.path=/
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:2.16.0@sha256:4d764be0f66532f6820a82aa365e530414f50f462410ce0949edd3fc22ccb9d5
    container_name: arrstack_tautulli_1
    user: "${LSCR_UID}:${LSCR_GID}"
    userns_mode: "keep-id:uid=${LSCR_UID},gid=${LSCR_GID}"
    environment:
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/arrstack/tautulli:/config
    ports:
      - 8181:8181
    labels:
      # Public Resource Configuration
      - pangolin.proxy-resources.tautulli.name=tautulli
      - pangolin.proxy-resources.tautulli.full-domain=${TAUTULLI_HOSTNAME}
      - pangolin.proxy-resources.tautulli.protocol=http
      # Auth: protect all but API
      - pangolin.proxy-resources.tautulli.auth.sso-enabled=true
      - pangolin.proxy-resources.tautulli.rules[0].action=allow
      - pangolin.proxy-resources.tautulli.rules[0].match=path
      - pangolin.proxy-resources.tautulli.rules[0].value=/api/*
      # Target Configuration - Override to Host Hairpin
      - pangolin.proxy-resources.tautulli.targets[0].method=http
      - pangolin.proxy-resources.tautulli.targets[0].hostname=host.containers.internal
      - pangolin.proxy-resources.tautulli.targets[0].port=8181
      # Health Check Configuration
      - pangolin.proxy-resources.tautulli.targets[0].healthcheck.enabled=true
      - pangolin.proxy-resources.tautulli.targets[0].healthcheck.hostname=host.containers.internal
      - pangolin.proxy-resources.tautulli.targets[0].healthcheck.port=8181
      - pangolin.proxy-resources.tautulli.targets[0].healthcheck.path=/
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:1.42.2@sha256:7cc7874ad35b105fe1fe4d99ef27be9c5eb2f4115ccf91af5a7283cae0024599
    container_name: arrstack_plex_1
    user: "${LSCR_UID}:${LSCR_GID}"
    userns_mode: "keep-id:uid=${LSCR_UID},gid=${LSCR_GID}"
    environment:
      - TZ=${TZ}
    volumes:
      - ${MEDIA_DATA_DIR}/media:/data/media
      - ${APP_DATA_DIR}/arrstack/plex:/config
    ports:
      - 32400:32400
      # Plex Companion
      - 3005:3005/tcp
      # Roku via Plex Companion
      - 8324:8324/tcp
      # Plex DLNA Server
      - 32469:32469/tcp
      - 1900:1900/udp
      # older Bonjour/Avahi network discovery
      - 5353:5353/udp
      # Network discovery
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    devices:
      - /dev/dri:/dev/dri
    labels:
      # Public Resource Configuration
      - pangolin.proxy-resources.plex.name=plex
      - pangolin.proxy-resources.plex.full-domain=${PLEX_HOSTNAME}
      - pangolin.proxy-resources.plex.protocol=http
      # Target Configuration - Override to Host Hairpin
      - pangolin.proxy-resources.plex.targets[0].method=http
      - pangolin.proxy-resources.plex.targets[0].hostname=host.containers.internal
      - pangolin.proxy-resources.plex.targets[0].port=32400
      # Health Check Configuration
      - pangolin.proxy-resources.plex.targets[0].healthcheck.enabled=true
      - pangolin.proxy-resources.plex.targets[0].healthcheck.hostname=host.containers.internal
      - pangolin.proxy-resources.plex.targets[0].healthcheck.port=32400
      - pangolin.proxy-resources.plex.targets[0].healthcheck.path=/identity
    restart: unless-stopped
