---
- name: Assegurar que els directoris necessaris existeixen
  ansible.builtin.file:
    path: "{{ dir_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/containers/systemd
    - /etc/pangolin
    - /etc/pangolin/traefik
    - /etc/pangolin/letsencrypt
    - /etc/pangolin/traefik/logs
    - /etc/systemd/system
  loop_control:
    loop_var: dir_path
  tags: podman

- name: Copiar Pangolin quadlets
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ quadlet }}.container.j2"
    dest: "/etc/containers/systemd/{{ quadlet }}.container"
    owner: root
    group: root
    mode: "0644"
  register: pangolin_quadlets
  loop:
    - pangolin_app_1
    - pangolin_gerbil_1
    - pangolin_traefik_1
  loop_control:
    loop_var: quadlet
  tags: pangolin

- name: Copiar fitxers de configuració de Pangolin Stack
  ansible.builtin.copy:
    src: "{{ role_path }}/files/pangolin_proxy_1.pod"
    dest: "/etc/containers/systemd/pangolin_proxy_1.pod"
    owner: root
    group: root
    mode: "0644"
  register: pangolin_pod
  tags: pangolin

- name: Copiar fitxers de configuració de Pangolin Stack
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item.name }}.j2"
    dest: "{{ item.dir }}/{{ item.name }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - name: config.yml
      dir: /etc/pangolin
    - name: dynamic_config.yml
      dir: /etc/pangolin/traefik
    - name: traefik_config.yml
      dir: /etc/pangolin/traefik
  register: pangolin_configs
  tags: pangolin

- name: Copiar fitxers de configuració de Pangolin Stack
  ansible.builtin.copy:
    src: "{{ role_path }}/files/pangolin_traefik_1.cil"
    dest: "/etc/pangolin/pangolin_traefik_1.cil"
    owner: root
    group: root
    mode: "0644"
  register: pangolin_traefik_selinux_policy
  tags: [pangolin, selinux]

- name: Check Pangolin Traefik SELinux policy installed
  ansible.builtin.command: semodule -l
  register: selinux_policy_check
  failed_when: false
  changed_when: false
  tags: [pangolin, selinux]

- name: Install Pangolin Traefik SELinux policy # noqa: command-instead-of-shell
  ansible.builtin.shell: |
    semodule -i /etc/pangolin/pangolin_traefik_1.cil /usr/share/udica/templates/base_container.cil
  when: pangolin_traefik_selinux_policy.changed or 'pangolin_traefik_1' not in selinux_policy_check.stdout
  tags: [pangolin, selinux]

- name: Include GeoLite2 database tasks
  ansible.builtin.include_tasks: geolite2.yaml
  tags: [pangolin, geolite2]

- name: Include crowdsec tasks if enabled
  ansible.builtin.include_tasks: crowdsec.yaml
  when: pangolin_crowdsec
  tags: [pangolin, crowdsec]

- name: Reload systemd if Pangolin config changed
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: pangolin_quadlets.changed
    or pangolin_pod.changed
    or pangolin_configs.changed
  tags: pangolin

- name: Pull images for pangolin containers based on configured versions
  ansible.builtin.shell:
    cmd: |
      podman pull $(awk -F'=' '/^Image=/ {print $2}' /etc/containers/systemd/pangolin_*.container)
  changed_when: false
  tags: pangolin

- name: Stop pangolin containers before restart
  ansible.builtin.systemd_service:
    name: "{{ container }}.service"
    state: stopped
  loop:
    - pangolin_traefik_1
    - pangolin_gerbil_1
    - pangolin_app_1
  loop_control:
    loop_var: container
  when: pangolin_quadlets.changed
    or pangolin_pod.changed
    or pangolin_configs.changed
    or pangolin_traefik_selinux_policy.changed
  tags: pangolin

- name: Stop pangolin pod before restart
  ansible.builtin.systemd_service:
    name: pangolin_proxy_1-pod.service
    state: stopped
  when: pangolin_quadlets.changed
    or pangolin_pod.changed
    or pangolin_configs.changed
    or pangolin_traefik_selinux_policy.changed
  tags: pangolin

- name: Reset failed pangolin units before start
  ansible.builtin.command:
    cmd: systemctl reset-failed pangolin_app_1.service pangolin_gerbil_1.service pangolin_traefik_1.service pangolin_proxy_1-pod.service
  changed_when: false
  tags: pangolin

- name: Start and enable pangolin containers
  ansible.builtin.systemd_service:
    name: "{{ container }}.service"
    state: started
    enabled: true
  loop:
    - pangolin_app_1
    - pangolin_gerbil_1
    - pangolin_traefik_1
  loop_control:
    loop_var: container
  tags: pangolin

- name: Register pangolin token
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      journalctl -u pangolin_app_1 -n 300 | \
      awk -F'Token: ' '/Token:/ {print $2}' | \
      tail -n1
  register: pangolin_token_result
  changed_when: false
  retries: 30
  delay: 10
  until: pangolin_token_result.stdout | trim | length > 0
  tags: pangolin

- name: Show pangolin token
  ansible.builtin.debug:
    msg: "Pangolin token: {{ pangolin_token_result.stdout | trim }}"
  tags: pangolin
