---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: prowlarr
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/prowlarr
      recursive: false
  targets:
    - name: prowlarr-secret
      namespace: media
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          PROWLARR__AUTH__APIKEY: "{{ .PROWLARR_API_KEY.Value }}"