---
ansible_become: true
ansible_become_method: sudo

media_host: "{{ secret_media_host }}"
media_path: "{{ secret_media_path }}"

# Komodo Stack settings
komodo_core_1_jwt: "{{ secret_komodo_core_1_jwt }}"
komodo_core_1_webhook_secret: "{{ secret_komodo_core_1_webhook_secret }}"
komodo_mongo_1_passwd: "{{ secret_komodo_mongo_1_passwd }}"

extra_periphery_pub_keys: "{{ secret_extra_periphery_pub_keys }}"