secret_media_host: ENC[AES256_GCM,data:3JJcuEVMJayeDQ==,iv:V7XNI6ay3ulgINXxcobX7O3Daw7yYD52JAsVRf79hew=,tag:ACS4nl7M6QvVg8wHhGFLvw==,type:str]
secret_media_path: ENC[AES256_GCM,data:5xkBNt3AOCiUGRXwYw==,iv:QfKAnKCkCrSNEBOzpov62dlb9SzQs6cZXZQ9WTaMiSo=,tag:ZG/3GhnvpfYDMwys1LBh1Q==,type:str]
secret_komodo_core_1_jwt: ENC[AES256_GCM,data:151G4xOjPavxRbkY2EJhe1kGRFCSFEvFoxVKxUPR2mE=,iv:Rwwei2Ac0IOABTri7pnGeA0q4hTXSV7BIDjDio1eCt0=,tag:FOb/xvtlYNjaJndKAhDT5A==,type:str]
secret_komodo_core_1_webhook_secret: ENC[AES256_GCM,data:SAbP7KxkliLB2bZYFXrKxlZWZKMUQz5xJwBzlVy26QY=,iv:duBrf0c243gPf2lCf4jXNTeOXJt7il1TBguPEv8GWy0=,tag:KacM9kQsktCd+3SEPC8PfA==,type:str]
secret_komodo_mongo_1_passwd: ENC[AES256_GCM,data:2T1lATBc1tHXsEPvkwwvva9SYNWp9yg4+BtH+rOAsxA=,iv:2zCwcmsno66t4Z8YiMlGOoLSjqp/K54hNfmBl1kc13g=,tag:1FryaSawvvuEwW+/cVyZHQ==,type:str]
secret_extra_periphery_pub_keys:
  ds920plus: ENC[AES256_GCM,data:YCE1BpBa/nWJKANUTUlpNDA8Cw9tkHYAm1oY6up33537Qk5tkpztc2H2YMSflvyApPhYumQ3UxHo+SCf,iv:kiDnlGXsioA8hLEh3WiwHI5eJSduSxGfeuOEfZaXPzE=,tag:CP7doqA9moUkEfBWMibY6w==,type:str]
sops:
  age:
    - recipient: age1yfrq96mwj6ah0szswj9a8vg8jmyzwl5g6w5u8fh23yg85saxyunss056hg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRS9QVUVTSkhDdGZQM2FG
        WkN0eGN6aUczdkVINCtnRHRXMmNJU285RlhrCmdjWlNiS0lRd1BuS2o2VVMveEJI
        WG9jSXFMdmJQK21ZaThIU21XbW5HaTgKLS0tIEZFbnNLNHVzWjV1U0JzTE9RQ2sw
        amJ0elNOdFR2YXh1S3R1aXJidXBodjAKNXXUsTzxkCn6yw2MLsw1a9YfQFTVybyj
        3dGfRg7brM0e/HnLbWrnoWhsEbq5TXZAp8r1p/oDh/NGTGGdPKHS1g==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age175lfmhlkmu8qu07dkxsau62v4vfdczejr66xvf9peg733rrth44shlz5zq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWndKVmRHTCtiYXUzYnpl
        ZXBiZVBEOUxldEVjTUNEbmpIekNIb0VGc2dBCnY5OGlSQllBMUZLYzMxTlU4Q3R2
        L0JqU0M3U1J0dW55eHRvN0psc1FqSk0KLS0tIFdYTGswR21LbWlhN0hRWVVXa3ds
        SVBDbVg5MDBXZ3dmMGFYQllHMUlxL1UK0YX8FRl/8lrrawccXtnB8In1ahc/xwYe
        2KpBehj9zOAy8NUpHIS9V42/Xbx+yFhwImZRKCOE2Gj0gvzLp6E84Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T16:00:54Z"
  mac: ENC[AES256_GCM,data:8HdXX+sgps2I1iIx4VZBRKwgfyayI9O5Q4do796ReFYzMpiqpbrz16B7Uyh/t8dbmOSdo6k/aVEaPwJ8slu2H7pph1R+NjYsJNeRCzglke3XpM+bmmnP25aMx+/ZYDbfxjnsQh135JK6BsxRLfmQxY6uyjjXnKJZyKnSdPXdSbw=,iv:+6DbUlG2a9IKdnWMXHKWkgzrB4nzN0b6EwTwfG7lrjk=,tag:/2u62PieCwz+ktddyzoVPQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.1
