apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

resources:
- namespace.yaml
- sealed-secrets.yaml
- storage-locations/
- schedules/
- repository-config.yaml
- maintenance-job-config.yaml

helmCharts:
- name: velero
  repo: https://vmware-tanzu.github.io/helm-charts
  version: 12.0.3
  releaseName: velero
  namespace: velero
  valuesFile: values.yaml
  includeCRDs: true

generatorOptions:
  disableNameSuffixHash: true
