---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-rustfs-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgA+km3IyGNd05AwrToXIMnIUjY8hboc4b/pm6RuwKqot2cCuE40WTjgljwfvNaZWAfffuy288VodSolzKUzo2gF7ojRb8KNTtgbABCRASAJu9xwXKUL8yjx2HHGTOe+bAK9geLTvM9CYSr9rISGD+0qbljR/HhuJuQlGkJPf1HoNMmzux0ik7ivJH42nDbiFJaCy18GwIaMRIIQ3vzjEdlypKvOV9ipST427lQhlp1cP0uIq3nQVUUhpzkEWTZZj9HLMTvF1n+zqFf2r/k32gwagSjxbcB2/sJd0NIIhg9TWjrDXCvF6+4MrzI3VcCh6F6yu3MiWtMTShbCOqwpvIZQjq2Rp40wrK/mnReERluPo1xgV5eO84HGuXSaNpDPRroTNWC79ophgcb5/CsF1HBPNgTnBqDrudeAT2Opk3HHq5lT4dTZnRR/I3lmyUikwGNKGzxiaokks+qYo3t57LX9/bZy8vMquEY7fxLhCrdmNF2by7JFPi+piGHqbojZPJbbSMvzcLJPY0tnt40UFk9JeGHXnjiHK9qV2OeJm/zDUVg8Yu7BdPSQ4xjdFpggT4kO9YMBMKcfYc0c9sExRH3WbMj6S+PaRiaL+ExKfucvgY1+50ffbIAtKF4Ezsq4P1LgaKmVz20gOEukbSmEKCTvvWfSTR8bRoFnGu+5NFc2usjO0zjTFHEM6cvfNIJjzKhhQEsJRuFPc09720aGSwx94rlOtWXZPumZ0naw4PsPc2w/RFFFe59WoFSXpH5AoDwbHyjtgWSY2848or0Kd4MHwCiOO9g9nCs1EprFiYEh5+w5sSLyHar0sTlQw4lF7+IzSbamM67LgYh1qpgr3lMiqmh1NDWKfhcPUUS5P65f5pPSllwpHjsG8KfaGuz3iFuXywKRlBiVq3+cGuHYAbKGe30=
  template:
    metadata:
      name: velero-rustfs-credentials
      namespace: velero
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-b2-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCQ1hjLk4GFOwFxE96Ok4wNPBbCzjb6Z7JaawoYZH2upA4bNhMR2tnnY3P5SA0cwWxVwdsgyph8OPutRx8n1u6Mji+IO3fcDjVI9tNb21xauMThDDtRvNQqB3/6/bEH2LTl/nT7WXBejmLR9CHf9hSK7GYiijKlHAwb99jQSh6t9CcJZbOKtLElu3f68Yy5XjT1lBy7yrGpEkspM5nM92RTWJ1jpWjZTawEZWC9o6o/ImcPLTODlWDz9xL/TExrBNfFJTGx/RJsYmQ0EvamGLpsomw/K7RvatEjA/OY/F3JNERp9q7NRpUbrVoe6YifUKs5+uh1qWVY2zHQjJ7DucskEfjDhi6nE7obR2LrqFO26KtEQTi09mvbVlXKl3Tb+L84uhWQW4tQBiSwjOTW16ZLQ1g8TZ8XExo668mYwtH2RtGTwFHAFlO29SU78YrZIb8sH5hfTH54ciMYS6WE2x5uKws+eeWLWNwPcRypVkP+IPQ0KsSYmOxj13neZ91VS+49Cs1SeddRRLnjhq8LwF+YMzIfRtJzHxKac6JKDz9u9QcVvwNZYfVl/pqIHr2SnYcVV3IThyhdG5p3oKBERc/KDcen7JDyC6pDUtm1qo6uH37fQgaiApEzxLLtlzO2dqyEbshcLjCn5nZpBRDHGAVKL83uOgQMP+GguT35f4kSVld95YS2co60hSyXTtVmlomue5j3ldKD2Z8p8fr/y5yeAmxdFsaQe6tKSOzxORRJFMkAE193w9T7ArAEQpAkJtntCwfbV/NmV9EAbYt1IIwa03b5a2jnUduZNKupdg5EDbxqaH5bo26VQeZSfIB4Sx4A/scL0+dIbGrzYN8=
    repository-password: AgB14+ZDMEupT/njaKovgrOF7pmqoRc37sSqoR6Z9wvAvpF/tubtPY4tG319EIFVB93UW/bxlz7hCRFPrkCaUCg/gSDdXt3fFhZsSZyG9Z3PZuIr+aosi400iKzS2sP5f0XlHGvgsrlLteewvbUpHIYkNu0Yzz2+o1mz1g0hM8PrHfudJpuoizEe+6hqrPj75TILoUBZg1nuX+mrd7ozeu+kVOfy/sWSv+fiHj3QxEoO+GNJS703TVnhHjLkzdUFWXPFblsyA4mEbhkitA7FDtx02rCG2lWSKzdieHaPC1lSoFzrcTe8kf0XD7zUxnFNhMfejBmDOO3VFY1FiSJ+glJ5tOdF/GyJnP2q2XFlWbFDoP+vAl2VTh6ShcdnY2al1BD2A0aNqINCps2OlIurgSxw1rQZVGBL8z6w6/Mr4Hhhkx8CjiH3h4a3Fr1XJkhMELedobIrLKWAB58N9VYzIn6S+2Gy1uo3ZhcWWA89mYaZF/0rsjGEAdRbHB6ULslWHYtuSBgyu5/ItP66fut43E7lo/ajmUfBQMQhl2AzaW/H7wDvt4gy7/aB+a7nFqBGBmiPueT1vnrrPwOuk2tQzVQWMv4QFdOPuZYP6YnngRqNw4HkT2qTOmf8qZNK13N/1PILyGSCg1XE7cSLUkzXkxCKLaw6a3zFHp0Lr+Xaisw1FY3kjxQJDN5y+9gT7I/Oz6o302dvpJGI4YawRUwDGsuEKJ49ziCdjUmtQRWVA2vpBT71QNjdQwKlxbDCt3JI2FmzgAxu0KufNnajoTq1z/aG
  template:
    metadata:
      name: velero-b2-credentials
      namespace: velero
