---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur
  labels:
    app.kubernetes.io/part-of: kopiur
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    # renovate: datasource=docker depName=ghcr.io/home-operations/charts/kopiur
    tag: 0.8.0
  url: oci://ghcr.io/home-operations/charts/kopiur
