---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adguard-configuration
  namespace: external-dns
spec:
  encryptedData:
    password: AgCVawZvoNg30NyBfxbpGMNg/ggo1NdyiLtAC4sImzRE3ZyWKYYATu/lYDvaKxikVgwdx3+v+1tE4vkeDUvSjkbXUjX+lmsi38oNvgJ1/Qpm2ZQPNjh5D/yRT4jiDFeMhBcFFJS6SzVqj14Cu4dAdWmhZk+tCYGrWFP2OKKcGhYRKEoz+MKpCo+eVE8S8POqldeWonwnBxzi1bNYQMWvdchDeYXtpAnnCUw66XmDaHdQfwZMnyaUDuHCsGJDLW9usUYBt0777+B4EFV2cQ7sWZ4oin7O0oy0vJSGtJgpK5gGD/JQnju5j1elrW9rwYMFPYEVxoez/8QHkw8w57L+iYnlLucnX3pKS29lf5WE0iJ8/arrIKXaeN38q0+Ih7Kba8YnOSu8bCEmP+A1touof5PickXd7bGEcBJVpsiLTjXF51C5hT0PDVTWVjCS15tXzutJk2tWW0z0u/p0oW1TVlGEdsX9/lt6K24okq947nDISbcbRRRtU/LEgiu9E+nu8Bj/fmOYpOtNPBD6C5YhlnnBLcqJeEG4EFQcRCApBO4eEAEt5fTVNFUS+eh3KQfqjdpvHH8JFarSs/kfgX5mJ2XbSt8tTpQqn7ad0CSbM40ndtWfuTZBo9WUzGe2x20bRrI7YkfTg1q2fbAnEE1B5pBlwdYDu57sbabzakiflzXapRmdXl+EItlWrxfoqF92CoTJPawXbf0/hZEzZsTKo3Q9gWkYcX8a4HORNaPXJVGZPEQv8SHSvVG8g78F1Y69UJCG8bu8XgGrzH1EsayDdJ55
    user: AgBOSCXKlPDGfEbrUf8TkOCGCFFf5Yw8/vOpKj6Esf17+xqDKEQx2gjA0iJ235NQ/anczuEOrAo8G6XSy2eaxW1UBhdcnykbq/D4x0fzgYA+I6kHP/QXU2vnTQQaY9/F1cDvfHngeqjw+AbI94F5t1I7S3AOnUablK4BryieUFsX8jn8INFW4AgAooJCl7Kl5t51xGTSVViJCyZpOU6IhWAXh4Gpk0j0rdWj3wJuCuME6duPL/G9gDNR/vMnRTJc6XvfcEIeT/E6DhnmPE4w+4Lw9+Xn6Q0RH3O8cwdzMESjP3yca+gOfoOfeMpa4zDLGka0FxYxYhQIGEH50htqpS0Sk9SsICjGII/R/CuLfzCd7x1pX3Q2XoaVPCbZSwYSiwYMgpgktvKtHRi9230PyGcPwwUIGfZuzvjNxvTWFRlQm1fUyywKKyi6qrjTuHsTvkAHIsgS2c46FkjqecIL71j2mRAHq8UIeMTOxFLki+ToMTpYsWXeigW32asAYXpvHUdegMFljW8NG/CRwlF9sWl3Viaoi+xpg4qymsRwwZT/Jz3+ir5tjjQmJIjNwztUwzRF+7ahdd/VoW/Aq9SwlUCCsin+vIcOZ+ofmgqZ9d4Pp7dh+We8rqy8KGnZ598aZFrPi4+st4lRToKJ+GDKTdKEXzlyMK3ldX0KTe0B5JCwzlu1dOM6SdYE5UW7k1n+bp0a0IP9IQ==
  template:
    metadata:
      name: adguard-configuration
      namespace: external-dns
