---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adguard-configuration
  namespace: external-dns
spec:
  encryptedData:
    password: AgB0uHDx8kqOoSe7pNON4v1Z8q7SG1efisK0MMJo5kD/i/AEs1ns6TRPXk8YMlFON8OjbntZ7rj6THX7iguLddLtY/0BTDOFPgdBKmtobORCRO4sHLWX6wPSQqmtvD5eAoPDivtiAqyX7/5jD9nDAmxzRdI4li/Yy6QUmRjDvOeMFXM2ItB3sNpQvfqS74HhOXCZNdnf99lIgUj7+rfKINf+hGHxYiEc0QVwpqRxCYnVx5IO8LqD/ZtSbnGYCgahphTV7c6ERYcl8OSAlBBAfVmExE0xhltvoeRW23DL0C6vkwXvfPThnBELBZxMLKrLK+onckpmlwsFG7+D1r7eN3qWsW7Sv1UzELpGbBGc3CvoNZowEEOTT2ZUXakOzr9FE5kXU1W+VPM5CmY66rF+OxqLiUsq7S6Rk5t8n70AInd6yfeGU07vAr6l2xlZB41I+WPLd80msi6GOuqZiAGEsvzL3h8Io6QWzb7rZA0WtIZh784ppGi4Rgqwz4bae52NE4lmX9TxTy1hNHKvaeDUCQuaIcGpdeCHsF+RTT1CFpzNbt2habcunyVgh89CRXOMzQphyYgpUhh6IWVCy2x14QJcgxArH2Ue30FrZpW2X4Fjk49ndDlO81v6mquDGxI8HpZIdWdjvKmmIuZPAO3uanymcMRH7DAZ3uCTU7/ZxAZ2kiuNBgUhC17xVNUITp+/Ev+lVTeFSxBMRGrv9/zoN5mYVwGjCR3QBmONzbewZ1pwajxmXL4egfYNrytC9pk76iMAuOcYUxtJ6kC07BrGViiz
    user: AgCUpNXMfEPfxuN93g+JomzNIHUQspXbqzA6vFeJmJJcj+Lke618U9+5wdlOIJxbejA16A6v+cL50nDEDmx6iQrqARl3a1VfXJU2wtPX9l9GNMlbK77jOfTL2+l0+7fZDrsxM66cFN1/PpT23B7J39nJp3INTUxp01tuL0kMdPJ2r/dm0uMQ56phwvpnzwxUnzwLcyiz8789zlkFOw584fYs1AVztobZ55MZbBAgvwhE76Lm5ljqGdoVvi83AauQQNru+LckK9m8XVo4CLtqM6xEyCHbrBVSYFTaezraJuYGyz6tBQSiIXFPjwE2ruLAxyddwGmC77Mbi5WsfrB5+I5GlrlndwzDIToxzJksD911xOyNhQctGWw/nD7kkY3MdtDyVUbuzphm9eq+VgQSM2YJgaUcscyqihc/7vrMhrhJcYvHNSYNRILB50JbhGuIaid5/VVYnnEXcb3LkraRvlgmbJQXaXnRetl++2utGet/ywupPgozMdB5iNi+bX/CwzjPRaFmo78EqTPABgHIIuTtWWuh+DB7QpI6Yq5whz77Ijj/YZrFw2oml8lXlQSLTM0V7HAM+Did6SEv/D284Xovwlfau2lhc4OMejGYsW2JfObxf7itSwccAAoe6zbcQyGkojA2yx9BPH4rjd0Zujw/4AkAScAp83loH4f2cNZQ378TF2+277ff4HE7C4UJxTIrj/TNcg==
  template:
    metadata:
      name: adguard-configuration
      namespace: external-dns
