---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgCIkIPKBS25FVpWzRfnp1BsLVyb0F8vjZGebH0N/JsFnqWriD7i7lvwlUAqabTCtVEwjgEtcmBUy5/SmBrNdYt+o8JUOAca125NMUQXCBijitR9KX5sQJMri5fQyr6aaIk/05xNrOm3OM3MyG+iNkrnfxwYQKlRu/w83gz1g7DxLrw2i8VVoZ5hTXBkb+H2Z6dj0BpoyaG4DlJIf6QerbxL/p3r5L8BEn7fuiv8Np/3hNf0YUm+IVUkZqHsAMpbqtZznmxj+kt/3bPsowPUSzSk9pLfcT2eGUe+7hBEjLKi3fDoO1pYqVpYWHtIHeb3qjkv8wXo26U71NEb/f/4sNNhFUoS8NKhlzAbp2BkThkiKt0fq9dskJw8APR119JhvyHqpc54DJwMoGD0aYxzSBtPCO7AoBGrMg6h42w9cKk3QZSCfybfFd0WruQs1xKW/ONjMp0DHMJ2KIZmQGbd3p0bkt4c5b/UZX7J9rupGbCLJNl/D9CsFog0xVDUAsy8G8nG7IOgaogl/QUae3fQtXX1RVdy0wDTda0UU9AXiijMbpqu3ne/P4Vge56qgSFqOif+Pj2P59SZHvVZ1SAOexTQwp0NzP2RvTO5YNbmbFdqPFZN09WhdlYLGOjttAOOOicLTmq2VWO28mxm/kFSH/ZnE/CpdDw7C8VPHB/71/dxP33KoFhC7XWINgrYU+PF6PBBb4ioZdlyCJy71jJiGWTkYheFDYC2k7m3zcBXqN7x9jWa8oiT0wZivsSCHHZtaUa/WrVJdzYSbItXXWmjQasfz9GmHmD1JdG892z/ky+z48y1vuoPu2rF5AbQAAkNy9Q/KPMW4aHQj99efVAamI+qIYH/KD7XiSMF9DTW17hrRxhmJOcWNqkJFFtUU+eqos314KZh4JRutFYDpDj4QzlvLmMoN9hVQuV8z5mHWUeyXGfdEjesSA==
  template:
    metadata:
      name: proxmox-csi-plugin
      namespace: csi-proxmox
