---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgCdBghJxrzjt/F9Iqtxinc/gTtsdr+7H/iEVBUjJPfUP5GMIzIgRSZDrqBdnEiqMX5NgzhxUXZQN79/zK382bBYevFIAgroTC9jjAq7n90POUvwizUTyuHmxsWHSBCJ8z7ky/gFesoMoPF+bkx8n01bD9rB5zno1i9IY78R16VmDmtD11cfQKMa1f7kXqFtZ/H+zRMr3AbjIqWWhp0E8viHWuy+ZwyeG/DzC7c88yq8OMjLn24aaCA9A5DNxB+pondjLRpU6sma+mDUq/KW383O+bSQ/Ra5RGt/qD8sK8I0XPEhJ97Qg8W+w4PP5kq1adAu3S7JZRU66eQyYJ9FWsZDevHk8DWoIrSl72GEoDk/DV9lsoSvI8sFYzY5KWz5OQSDtlYdEUHly8n/O4RB1kHXaT8NaRMbzUlwiZggWDIzmO0hMaAyyUbLQddm/WOK+T9T8c3wupa6rdkCwnOpqeZFithm0rlxyPZbWucpH1zTz9l955yuDI4pfNAM4lvqawEMEsZOBkIzB2GunmCBkyGf457Uao7whG/k4OHUARV7uiTPM90H1mcu+DrrRYWB424Q54PfCxXZTY74kXKZXFwaDQhvulx2+xwNQTHaQop9O763PyiqYbwuQUeXP940c+Nyu8HnKd9JXQNYKoVWiPO2Si78avhyYID8JEsvwDeHBAbq/BKch9I+ViRwg6YImver/gxEFncZHxQqBhmkNXWmPHFyct991VwBbbjM1PjVtM3pcdPv13eBwiuz4ImUDKkJcOPN03j7p7vKWxbvU+6uY3E8BSxuBQXXdPPmSRZCbIsRQULik1yrgp2AhD3RtLMNoVpoWVFE1Vchl5HjE4D3xN2GXAFuLMqIXHEpwmxClgeTTonLrgmz5KFB6VgwCz1EIjPisnmCm88gkLE4hfY9/T8N1vKCwHx5qEel8H6LF2O00S96Vg==
  template:
    metadata:
      name: proxmox-csi-plugin
      namespace: csi-proxmox
