---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgCm6MMhCb4/8DjrMOp+XGx+PHaAMDPuZuNA0UDumYsi/DBOmRcRt3ktil5ItSkgnnsVyue0dYEBaCMRavsRvyppeE5xy6Dc6Ds6yZDhODn+ocIwQBp1K/uTeMDByd4BCtwOrNx8ZhU51SCa8nLe5L0j2GbEAmcf8aZkD0AARqC32ReZUkgk5CPRT4aEV9ROnsuBOjME2TAldcDQhwqDP4p4pAdyLkHaUZ2PjwnUTKQI0YBBWK+TjimdzzwUVBhBggr0NKJcNHBDko6ZARwKEU/JZ+9ZiMigd81IpM6WISNtzGPm021dVGWFP76yi0Tam4DG76I5IIKl45wwzSp7KH3XlGA394/ETwYl7IL7oVtQaJqIHYo4tUelLUmCz0Yu34BKzjucvbeiZteCZl5EZ0TeUroky7m4hPKrjJ53lxjmm5Rc5UoTfxILY1OXLUZsMXNvrT6hD6xxnh+pP0nvZJsRZtH/tVNvzcruE88p7Zie+hv7rLco4JJrzo4rjJz+H/1wOFNuXenn0kDS+Tc9zHuW4TrKqxzZl36IVFSCUupQcj4ScivQefOWnfEju21rWNhXANeZnUkEidRhll4nmTN+sjvFJQED35uaFNJlvtjY8DKMeXjuJ7wprlsbey7s+c5oNWEiiNnSE1OCapRFXjlNTSrGXtmTqz29N6fMxXYE8lMZvxYaIxI8WS5GHyR2DP2GbIevqsIn2Jpic6JpVssrk+vgG5HznFbxJp1CNObDS4nHjEkYG+pAKw/x0lg6KHfIOYBfxj1cNNXy9mbtsKPKsddmAqz0QZFfx7BFKgyeKtaFYz43qUTCTCT5z0/ryIR4v9lPpcMPsmvXOA/0nHPHZI9VSKrDYfvWzHB938KTmU/9EBRf7TjOK6Tpk4r05KcIH1sJf4FJp4TPItEPt7vHJrXMst5ZJjgZgRmeg7Hgle/Ut0Df
  template:
    metadata:
      name: proxmox-csi-plugin
      namespace: csi-proxmox
