---
name: caddy
services:
  app:
    image: ghcr.io/bjw-s-labs/caddy-l4:2.11.7@sha256:b3302c819df78dac2b27f3032d9999add89c23a1259a3422622fcf81610b7dd1
    container_name: caddy-l4
    environment:
      CADDY_ACME_EMAIL: ${CADDY_ACME_EMAIL}
      VPS_LOCAL_HOSTS: >-
        twnl.eudald.gr
        towonel.eudald.gr
        cadi-doco-cd.eudald.gr
        cadi-gatus.eudald.gr
    ports:
      - 80:80
      - 443:443
    volumes:
      - etc:/config
      - var:/data
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    restart: unless-stopped
volumes:
  etc:
  var:
configs:
  caddyfile:
    file: ./Caddyfile
networks:
  default:
    name: edge
    external: true
