---
name: caddy
services:
  app:
    image: ghcr.io/bjw-s-labs/caddy-l4:2.11.6@sha256:39266cdf49942464783ad4bc03ae6aa0e4da62dbe8e8258b12566c886ebd4502
    container_name: caddy-l4
    environment:
      CADDY_ACME_EMAIL: ${CADDY_ACME_EMAIL}
      VPS_LOCAL_HOSTS: >-
        twnl.eudald.gr
        towonel.eudald.gr
        cadi-doco-cd.eudald.gr
        cadi-gatus.eudald.gr
    ports:
      - 80:80
      - 443:443
    volumes:
      - etc:/config
      - var:/data
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    restart: unless-stopped
volumes:
  etc:
  var:
configs:
  caddyfile:
    file: ./Caddyfile
networks:
  default:
    name: edge
    external: true
