---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: ocharted
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/ocharted
      recursive: false
  targets:
    - name: ocharted-secret
      namespace: kube-system
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          auth: "{{ .OCHARTED_USERNAME.Value }}:{{ .OCHARTED_PASSWORD.Value }}"
