---
services:
  sync:
    image: ghcr.io/bakito/adguardhome-sync:alpine-v0.9.0@sha256:fc3accd883cda7d68f027811f34f213c23d8ed38c23f944fc58636456dc74329
    container_name: adguard_sync_1
    environment:
      - CRON=*/1 * * * *
      - RUNONSTART=true
      - ORIGIN_URL=${ORIGIN_URL}
      - ORIGIN_USERNAME=${ORIGIN_USERNAME}
      - ORIGIN_PASSWORD=${ORIGIN_PASSWORD}
      - REPLICA1_URL=${REPLICA1_URL}
      - REPLICA1_USERNAME=${REPLICA1_USERNAME}
      - REPLICA1_PASSWORD=${REPLICA1_PASSWORD}
    restart: unless-stopped
