---
services:
  app:
    image: docker.io/adguard/adguardhome:v0.107.74@sha256:f29c58a91f79387cbbbb042e140814f58e830d457d44af03d662c8df43db9dea
    container_name: adguard_app_1
    environment:
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/config:/opt/adguardhome/conf
      - ${APP_DATA_DIR}/data:/opt/adguardhome/work
    # command: ["--web-addr", "0.0.0.0:${ADGUARD_WEB_PORT}"]
    ports:
      # DNS Ports
      - "53:53/udp"
      - "53:53/tcp"
      # Optional: DHCP Port
      # - "67:67/udp"
      # - "68:68/tcp"
      # - "68:68/udp"
      # Initial Setup Port
      # - "3000:3000/tcp"
      # Web Interface Port
      # If using network_mode: host, AdGuard listens on port 80 by default.
      # You may need to change it to 8053 in AdGuardHome.yaml or via command: ["--web-addr", "0.0.0.0:8053"]
      - "${ADGUARD_WEB_PORT:-3000}:${ADGUARD_WEB_PORT:-3000}/tcp"
      # Optional: HTTPS/DNS-over-HTTPS Port
      # - "443:443/tcp"
      # Optional: DNS-over-TLS Port
      # - "853:853/tcp"
      # Optional: DNS-over-QUIC Port
      # - "784:784/udp"
      # - "853:853/udp"
      # - "8853:8853/udp"
      # Optional: DNSCrypt Port
      # - "5443:5443/tcp"
      # - "5443:5443/udp"
    restart: unless-stopped
    # To see real client IPs in rootless podman, use host networking.
    # WARNING: This requires port 53 to be free on the host (disable systemd-resolved stub).
    networks:
      vlan99:
        ipv4_address: 10.1.99.2

networks:
  vlan99:
    external: true
