---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: b2-cnpg-credentials
  namespace: nextcloud
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgARpxI3UDbWUdo/N5m+w384I1totxfjCvfUGaVAxlHQAaoa5gbopOPfzMq5bL5lzYYzNt+RUbO9jHOmZntPUd6kMBa7TQ48Gm8EoumzAQblUJYyt7PUrF4bX+qRyM3L0La3ZycoxJh4SDu22vCxKdmfetoekcWsMQUM400TEcS68u69WnPAjg43YqJnmUe3fOaEycLMd8cgkq2yCaWKnRkg2JeTp1mJ+ZhXTbalQfmPFMdqNaa/9w04eL6Xesbqu1CHpHdsR6e9+7J+E/SpsPvI2D6oe8brxWePGbv8yOYhH0+HQpUi4SFrDY0/fGT+nL/yV4+vCGg5LlClPXzh4ma4MDl5a9P/NbWb50OEi7suerPgo0r/KAuXsYK05zWIhBe7GlV8OROPA9/keE7PNJbHBwfeDb6hhYg55IM1LqpDzRWV/1k5438LahZuiFT3hh0Wi9oa67olGfAfzVBkYS/yzByBso8gwVIRr5vQLyi7+Rf+FCM2pE/TqazhHLCYIYanwXlkGL8oH4vNZIg5hgPNlFQuvvqrFdXgmRikLoPfSde6dW7vIrAi/7jvD4gPo4i31WBapeHaqDuQz2UiOGgJyYP2eG1YvVQlkHvqZBFkFn0+Gmw2/yXCO9yYARuL3hrMkrIJXuUg5FrEv8m5mMDWd+gXXzniK0lVPZwJ81Ux9EZ/0Rwd4qm5/tge6RrQMjME/5UKteOQTG2N3ujLn3fmT0hBZ/qR/MgX
    AWS_SECRET_ACCESS_KEY: AgBtymFBDTbEKyBrilppKxz1H3uVysCnLdtASHYATYqrWff4EVzcN4+6+lLYCjBf98pXSCPXYByk71sMo0ozvkcXi0OGA4h3n07Q2YxenjZQIyrwIhGS8y3ula6OwTrK4y7kAhcvDzpZe6Z5qE7fAYrLtYmQNBWLt3ik2C8t3GO8ZnBmfsSKUra1S9ydrfnikn/FvluPKHypDOhnQArCBG86/yUV+RbpZ8A8KuUX77DH0AHxND1NGHElTLX/WssrvqhtPElfrTGdK9NCa8Pm3K/aDM/zzSsbBgZCas3j+K/tps5EkpzarAaUrKrOjVLV2bouEtQIYy07Z1vweoGgTBmOkfrhfvYTaI8ztLc+qgGD+CbVZ8IVgMwYcKTAz4cV05rzFfxfyJnA7odypgM83GqBEoS8kV1FqTsczF7ssAocCaXNQKF5dF87FDfcBEibrGPbPdEy3pMXpg/PpIC5sT3J0j+8MiSpYPEWLrXwjJZtaJ1FkfsvvpJvcRThmVQ1xdP6qyAkoIqJKVYFr1f0k6V2F7mVa8KrRPjQYBLwxcyUwk7UN3HXxhBbSEXKGKOZQI7MU3Zo3j5UCGbx1NpTCskQiJJkLzhYhklbh2gXE7ihjFEd41xt0+uAelOA7pqdOeAg2nLFjV00mict1oRfKqT7sTeEM4UmNMO8JrAXnY13FJGPXK7qXdM070AzRTBE52egvWBgCGO8JBku6k12EjwFdKsB70UspkvaRPPbQSEC
  template:
    metadata:
      name: b2-cnpg-credentials
      namespace: nextcloud
