apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: nextcloud-rustfs-store
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  retentionPolicy: 14d
  configuration:
    destinationPath: s3://postgres/web/nextcloud-postgresql
    endpointURL: http://ds920plus.home.eudald.gr:9000
    s3Credentials:
      accessKeyId:
        name: rustfs-credentials
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: rustfs-credentials
        key: AWS_SECRET_ACCESS_KEY
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: nextcloud-b2-store
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://e17n-homelab-cnpg-b2/web/nextcloud-postgresql
    endpointURL: https://s3.eu-central-003.backblazeb2.com
    s3Credentials:
      accessKeyId:
        name: b2-cnpg-credentials
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: b2-cnpg-credentials
        key: AWS_SECRET_ACCESS_KEY
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgresql
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 20Gi
    storageClass: proxmox-csi
  walStorage:
    size: 5Gi
    storageClass: proxmox-csi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 256MB
      huge_pages: "off"
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: nextcloud-rustfs-store
  externalClusters:
    - name: nextcloud-postgresql-rustfs-backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: nextcloud-rustfs-store
    - name: nextcloud-postgresql-b2-backup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: nextcloud-b2-store
  monitoring:
    enablePodMonitor: false
