apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgresql
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud-postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: nextcloud
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17@sha256:31c3b2798f56a0cc3e8331161969a073a19742e9013e1ff46ddfc3f4110a5480
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
  storage:
    size: 20Gi
    storageClass: proxmox-csi
  walStorage:
    size: 5Gi
    storageClass: proxmox-csi
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 256MB
      huge_pages: "off"
  monitoring:
    enablePodMonitor: false
