apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/part-of: nextcloud
spec:
  parentRefs:
    - name: internal
      namespace: gateway
  hostnames:
    - cloud.k8s.eudald.gr
  rules:
    - filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: Strict-Transport-Security
                value: max-age=15552000; includeSubDomains
      backendRefs:
        - name: nextcloud
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud-eurooffice
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud-eurooffice
    app.kubernetes.io/part-of: nextcloud
spec:
  parentRefs:
    - name: internal
      namespace: gateway
  hostnames:
    - office.k8s.eudald.gr
  rules:
    - filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: Strict-Transport-Security
                value: max-age=15552000; includeSubDomains
      backendRefs:
        - name: nextcloud-eurooffice
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud-notify-push
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud-notify-push
    app.kubernetes.io/part-of: nextcloud
spec:
  parentRefs:
    - name: internal
      namespace: gateway
  hostnames:
    - push.k8s.eudald.gr
  rules:
    - filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: Strict-Transport-Security
                value: max-age=15552000; includeSubDomains
      backendRefs:
        - name: nextcloud-notify-push
          port: 7867
