apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
- namespace.yaml
- sealed-secret.yaml
- rustfs-sealed-secret.yaml
- b2-sealed-secret.yaml
- service-account.yaml
- nfs-pv.yaml
- nfs-pvc.yaml
- database.yaml
- database-scheduled-backups.yaml
- http-route.yaml
- collabora-http-route.yaml

helmCharts:
- name: nextcloud
  repo: https://nextcloud.github.io/helm/
  version: 9.2.0 # renovate: datasource=helm depName=nextcloud/nextcloud
  releaseName: nextcloud
  namespace: nextcloud
  valuesFile: values.yaml

patches:
- target:
    kind: Deployment
    name: nextcloud
  patch: |-
    - op: add
      path: /spec/template/spec/automountServiceAccountToken
      value: false
    - op: add
      path: /spec/template/spec/serviceAccountName
      value: nextcloud-app
- target:
    kind: CronJob
    name: nextcloud-cron
  patch: |-
    - op: add
      path: /spec/jobTemplate/spec/template/spec/automountServiceAccountToken
      value: false
    - op: add
      path: /spec/jobTemplate/spec/template/spec/serviceAccountName
      value: nextcloud-app
- target:
    kind: Deployment
    name: nextcloud-collabora
  patch: |-
    - op: add
      path: /spec/template/spec/serviceAccountName
      value: nextcloud-collabora
    - op: add
      path: /spec/template/spec/automountServiceAccountToken
      value: false
