apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
- namespace.yaml
- service-account.yaml
- nfs-pv.yaml
- nfs-bootstrap-job.yaml
- http-route.yaml
- network-policy.yaml
- sealed-secret.yaml

helmCharts:
- name: nextcloud-aio-helm-chart
  repo: https://nextcloud.github.io/all-in-one/
  version: 13.3.1 # renovate: datasource=helm depName=nextcloud-aio-helm-chart registryUrl=https://nextcloud.github.io/all-in-one/
  releaseName: nextcloud-aio
  namespace: nextcloud
  valuesFile: values.yaml

labels:
- pairs:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: nextcloud-aio
    app.kubernetes.io/part-of: nextcloud
  includeSelectors: false

patches:
- path: patches/apache.yaml
- path: patches/database.yaml
- path: patches/eurooffice.yaml
- path: patches/fulltextsearch.yaml
- path: patches/imaginary.yaml
- path: patches/nextcloud.yaml
- path: patches/notify-push.yaml
- path: patches/redis.yaml
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/automountServiceAccountToken
      value: false
    - op: add
      path: /spec/template/spec/serviceAccountName
      value: nextcloud-aio
- target:
    kind: Service
    name: nextcloud-aio-apache
  patch: |-
    - op: replace
      path: /spec/type
      value: ClusterIP
    - op: remove
      path: /spec/externalTrafficPolicy
    - op: remove
      path: /spec/ports/1
- target:
    kind: PersistentVolumeClaim
    name: nextcloud-aio-nextcloud
  patch: |-
    - op: replace
      path: /spec/accessModes
      value:
        - ReadWriteOnce
    - op: replace
      path: /spec/storageClassName
      value: proxmox-csi
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "-2"
- target:
    kind: PersistentVolumeClaim
    name: nextcloud-aio-nextcloud-data
  patch: |-
    - op: replace
      path: /spec/storageClassName
      value: ""
    - op: add
      path: /spec/volumeName
      value: nextcloud-aio-data
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-wave: "-2"
