apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: nextcloud
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: ds920plus.home.eudald.gr
    path: /volume1/k8s
  mountOptions:
    - nfsvers=4.1
    - nconnect=4
    - hard
    - noatime
