---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-credentials
  namespace: nextcloud
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgC4I/IsA4NVOGzu3gsoXEYcz6/1ahupyAwKjy+T/v6kt0rZikPQ0eYqnan1UMaKLwATlRd4cpn5vztUqybV5zEU1cvPz6ZMMEB+jXgYdwbkZaTL4SNQJI1Oc9kTj3deDoQaOaKBn1AjQQEaebLYdYxTlMKKq8rgIe9J3aEV9eOIvmf3ppo/IyNEsA9wnPxKuloEbDllfK6NRyDdqSR///MtL20XX+TlDGALxWcIPmBUKvuWlxJ+FrVpsUCd/NWjNF142jvina4O0GhmTYqqV86WzHkXOCm4D3qlk2D7k6rbSsW2BkY4QDAgywaT8n2XZPtw5HCBuKGA3z7D68Bm2hB6sstfXc2RmMwGt9xRa0sN4aJghUfSZbeA8ZaCp44mleGhKJfzCz3kK9dO4HtmuMliovJC3PdVkUMzy75Az9OHKNQ13n6KDqwCgYmktjqQHhM5UCsRGREMTveyqMkiZkpzI3l0v5Le521FlllgNIAnfpXDt/lh61aPy7oLaqnU1JOm1OM8r0fLBuB0WVp5MEn8p1BEV/Gtv6BHah4fYwYYWDJrZ4YeeZrqndytHSye01gghlGP3cafgR/ElA0bNAXuda8WVKIa4kG+Ew6IlgcjmxgnkP41vkim3xC6WZmKLPZVbd5aV78V1TGYGsr+r5A5pH6XR/m3LgY80yIWmx7cl1F2pfED1fni23Ff4dzsWo40q0vcTQXBCbDXXC5W8Ov4XgSGxg==
    AWS_SECRET_ACCESS_KEY: AgC+KF1RPTdbXdSwKew6xcRefGNaTwnEgevxE8+lM80zNuIvPkjCYtQP5+T3VWxeOti5lXx1FmSkHIFOpND1vU9ck7lkOBSwOUvqSSeuP9XTGavZDHF58aa2wmWmewCvNq2wuKO6BsK9wX7J2v7XmVefWjta8qqEPXNGgpIADgPASU6mk/qEqFNLFBtHK1cKvbS/dYL0bPx9kFR2/zZ3lmcb8CyEykJC4DCkIvasjXA8NgC8wsuWjC+xYdA87XYfQa1xHG0Cc+xdLDfwglsqBZUkiK1c4hEcrZi0AZNcO0ww9LcKJn/TmXZAT/E8mVShpR+yr7R2h7PgDowzBtNLlM3rQCj5RGKjW59QqdYyXa6iIdt78kQhHb9Wzy28PkiqxgVmioV2NFivEtdYJhzSwb1qkV4rBVNjn/R1RFYUz8zgF44YBz2zHASQFbnrkGvNg+4mzczu1xq9KqjHi3ZjjiiqcLKCPxoNs9K8r0K4rcWI1pvbm6ROsIA2OCnIR6sKdgbZIbVLPZc4lPrsKJsPjhiQhBpsobr6AdWLe+rxPolkNtA9pZwGfHDBnK+SushJdFaH+5dcEUeET/n/Ut22PvOYIfq5ZBOy4pGM/wy31dy78VI4pARzz7AjfZsufGCDaLv/bTf/QOEl/dzihR9T5lxDNqZFg3VRY+H8ICH8enUw0LwMCmLMSL+gPi6UIcfMeXjczjVFoDbBdj5HTmiW4EYkzN+SFcvY6FB4pD0vNm6LdEZeyahHQEx3
  template:
    metadata:
      name: rustfs-credentials
      namespace: nextcloud
