apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcloud-app
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/part-of: nextcloud
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcloud-collabora
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: collabora
    app.kubernetes.io/part-of: nextcloud
automountServiceAccountToken: false
