image:
  registry: docker.io
  repository: library/nextcloud
  flavor: apache
  tag: 34.0.1-apache@sha256:6444fc5450302534e850b4d23c05b5f06c7b0d25bd5ece716452061454699c58

replicaCount: 1

podAnnotations:
  backup.velero.io/backup-volumes: nextcloud-main

phpClientHttpsFix:
  enabled: true
  protocol: https

nextcloud:
  host: cloud.k8s.eudald.gr
  username: admin
  existingSecret:
    enabled: true
    secretName: nextcloud-secret
    usernameKey: NEXTCLOUD_ADMIN_USER
    passwordKey: NEXTCLOUD_ADMIN_PASSWORD
  containerPort: 80
  trustedDomains:
    - cloud.k8s.eudald.gr
    - cloud.eudald.gr
  extraEnv:
    - name: TZ
      value: Europe/Madrid
  strategy:
    type: Recreate
  securityContext: {}
  podSecurityContext:
    fsGroup: 33
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile:
      type: RuntimeDefault

nginx:
  enabled: false

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: nextcloud-postgresql-rw
  existingSecret:
    enabled: true
    secretName: nextcloud-postgresql-app
    usernameKey: username
    passwordKey: password
    databaseKey: dbname

mariadb:
  enabled: false

postgresql:
  enabled: false

redis:
  enabled: true
  architecture: standalone
  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    tag: 8.0.3-debian-12-r1
    digest: sha256:ad7fdfaedb25b37b8015c39f019961c3e5a865d8ff5859a491acb4d9d9b85697
  auth:
    enabled: true
    existingSecret: nextcloud-secret
    existingSecretPasswordKey: REDIS_PASSWORD
  global:
    defaultStorageClass: proxmox-csi
  master:
    persistence:
      enabled: true
      size: 2Gi
      storageClass: proxmox-csi
  replica:
    replicaCount: 0
    persistence:
      enabled: false

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  storageClass: proxmox-csi
  size: 10Gi

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1
