DATABASE_PASSWORD: ""
EUROOFFICE_SECRET: ""
FULLTEXTSEARCH_PASSWORD: ""
IMAGINARY_SECRET: ""
NEXTCLOUD_PASSWORD: ""
ONLYOFFICE_SECRET: ""
RECORDING_SECRET: ""
REDIS_PASSWORD: ""
SIGNALING_SECRET: ""
TALK_INTERNAL_SECRET: ""
TURN_SECRET: ""
WHITEBOARD_SECRET: ""

NC_DOMAIN: cloud.eudald.gr
TIMEZONE: Europe/Madrid

CLAMAV_ENABLED: "no"
COLLABORA_ENABLED: "no"
EUROOFFICE_ENABLED: "yes"
FULLTEXTSEARCH_ENABLED: "yes"
IMAGINARY_ENABLED: "yes"
ONLYOFFICE_ENABLED: "no"
TALK_ENABLED: "no"
TALK_RECORDING_ENABLED: "no"
WHITEBOARD_ENABLED: "no"

AIO_LOG_LEVEL: warn
APACHE_MAX_SIZE: "17179869184"
APACHE_PORT: 80
ADDITIONAL_COLLABORA_OPTIONS:
  - --o:security.seccomp=true
COLLABORA_DICTIONARIES: de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru
FULLTEXTSEARCH_JAVA_OPTIONS: -Xms512M -Xmx512M
INSTALL_LATEST_MAJOR: "no"
NEXTCLOUD_ADDITIONAL_APKS: imagemagick
NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS: imagick
NEXTCLOUD_MAX_TIME: 3600
NEXTCLOUD_MEMORY_LIMIT: 512M
NEXTCLOUD_STARTUP_APPS: "deck twofactor_totp tasks calendar contacts notes -spreed"
NEXTCLOUD_TRUSTED_CACERTS_DIR: ""
NEXTCLOUD_UPLOAD_LIMIT: 16G
REMOVE_DISABLED_APPS: "yes"
TALK_PORT: 3478
UPDATE_NEXTCLOUD_APPS: "no"

STORAGE_CLASS: proxmox-csi
STORAGE_CLASS_DATA: proxmox-csi
APACHE_STORAGE_SIZE: 1Gi
CLAMAV_STORAGE_SIZE: 1Gi
DATABASE_STORAGE_SIZE: 20Gi
DATABASE_DUMP_STORAGE_SIZE: 20Gi
ELASTICSEARCH_STORAGE_SIZE: 10Gi
EUROOFFICE_STORAGE_SIZE: 5Gi
NEXTCLOUD_STORAGE_SIZE: 20Gi
NEXTCLOUD_DATA_STORAGE_SIZE: 2Ti
NEXTCLOUD_TRUSTED_CACERTS_STORAGE_SIZE: 1Gi
ONLYOFFICE_STORAGE_SIZE: 1Gi
REDIS_STORAGE_SIZE: 2Gi
TALK_RECORDING_STORAGE_SIZE: 1Gi

NAMESPACE: nextcloud
NAMESPACE_DISABLED: "yes"
NETWORK_POLICY_ENABLED: "no"

ADDITIONAL_TRUSTED_PROXY: 10.244.0.0/16
ADDITIONAL_TRUSTED_DOMAIN: cloud.k8s.eudald.gr
NEXTCLOUD_DEFAULT_QUOTA: unlimited
NEXTCLOUD_MAINTENANCE_WINDOW: "1"

SUBSCRIPTION_KEY: ""
SERVERINFO_TOKEN: ""
APPS_ALLOWLIST: ""
NEXTCLOUD_SKELETON_DIRECTORY: ""
SMTP_HOST: ""
SMTP_SECURE: ""
SMTP_PORT: ""
SMTP_AUTHTYPE: ""
SMTP_NAME: ""
SMTP_PASSWORD: ""
MAIL_FROM_ADDRESS: ""
MAIL_DOMAIN: ""
TALK_MAX_STREAM_BITRATE: "1048576"
TALK_MAX_SCREEN_BITRATE: "2097152"
