---
- name: Install base packages
  community.general.apk:
    name:
      - nfs-utils
      - rpcbind
      - uuidgen
      - iptables
    state: present
    update_cache: true
  tags: packages

- name: Start and enable rpcbind service
  ansible.builtin.service:
    name: rpcbind
    state: started
    enabled: true
  tags: services

- name: Enable iptables modprobe
  ansible.builtin.modprobe:
    name: ip_tables
    state: present
    persistent: present
  tags: system

- name: Generate machine-id if not exists
  ansible.builtin.command:
    cmd: uuidgen > /etc/machine-id
    creates: /etc/machine-id
  tags: system

- name: Copying xdg-runtime-dir script to /etc/local.d
  ansible.builtin.template:
    owner: root
    group: root
    mode: "0755"
    src: "{{ role_path }}/templates/xdg-runtime-dir.start.j2"
    dest: /etc/local.d/xdg-runtime-dir.start
  tags: system

- name: Enable local service
  ansible.builtin.service:
    name: local
    state: started
    enabled: true
  tags: system

# - name: Make root filesystem rshared
#   ansible.builtin.mount:
#     path: /
#     opts: rshared
#     state: mounted
#     fstype: none
#     src: none
#   tags: system

# - name: Create local startup script for shared metrics
#   ansible.builtin.copy:
#     content: |
#       #!/bin/sh
#       mount --make-rshared /
#     dest: /etc/local.d/sharemetrics.start
#     mode: "0755"
#   tags: system

# - name: Enable local service
#   ansible.builtin.service:
#     name: local
#     enabled: true
#   tags: system

- name: Create mount point directory if it doesn't exist
  ansible.builtin.file:
    path: "{{ nfs_mount_point | default('/mnt/nfs') }}"
    # owner: "{{ ansible_user }}"
    # group: "{{ ansible_user }}"
    state: directory
    mode: "0755"
  tags: nfs

- name: Mount NFS share
  ansible.builtin.mount:
    path: "{{ nfs_mount_point | default('/mnt/nfs') }}"
    src: "{{ nfs_server }}:{{ nfs_path }}"
    fstype: nfs
    opts: "{{ nfs_options | default('defaults,rw,hard,intr') }}"
    state: mounted
  when: nfs_server is defined and nfs_path is defined
  tags: nfs

- name: Ensure NFS mount persists across reboots
  ansible.builtin.mount:
    path: "{{ nfs_mount_point | default('/mnt/nfs') }}"
    src: "{{ nfs_server }}:{{ nfs_path }}"
    fstype: nfs
    opts: "{{ nfs_options | default('defaults,rw,hard,intr') }}"
    state: present
  when: nfs_server is defined and nfs_path is defined
  tags: nfs
# - name: Set ownership of NFS mount to rootless user
#   ansible.builtin.file:
#     path: "{{ nfs_mount_point | default('/mnt/nfs') }}"
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     recurse: true
#     state: directory
#   when: nfs_server is defined and nfs_path is defined
#   tags: nfs
