---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: radarr
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/radarr
      recursive: false
  targets:
    - name: radarr-secret
      namespace: media
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          RADARR__AUTH__APIKEY: "{{ .RADARR_API_KEY.Value }}"