---
kind: Kustomization

resources:
  - sealed-secrets.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authentik-blueprints
    files:
      - ./blueprints/groups.yaml
      - ./blueprints/users.yaml
      - ./blueprints/brands.yaml
      - ./blueprints/flows-default-provider-authorization-one-time-consent.yaml
      - ./blueprints/flows-passwordless-authentication.yaml
      - ./blueprints/flows-default-authentication-passwordless.yaml
      - ./blueprints/flows-webauthn-setup.yaml
      - ./blueprints/oauth-scopes.yaml
      - ./blueprints/outposts.yaml
