---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  encryptedData:
    api-token: AgB3QFO34xw5sOPe0l2hroHz0pc47Xxjj3xfiJmudqd7F9Te9hNal4HxCPkFKqYLxa6oJXO2nxSZtKOh4F3p15v++TylkKwJtgz2BpX7UCNszTAL04NbWRhVXrtFleHqmWE+4yCJpWbWIbVEzC3gqkHmOG/5l2GIbUs8LIKJGf1HRZZQMmoD8YQ6Qlbk/qXd7dZ3P0odAlCjEAL9/hZUzFxvoi0vEXj+N2TWAJrtGpUcqz17q865xw3pMxoQfZP8p3dZOIx2RZ7A9HJd+AsSRMY3NJHX2YFL7v4YVA/rjyKPGZCQBMsJojKtO+NlEPuxOJcSb3Oom81SySWERFo0fHq0VnBs2nIdcLCNcxnmYOdFHhNvnqskDI3efShkdkxiWT1L2+Wgfj9q6w7LK1Oovou7Kph+uL9QQ/cetVBcZg5Fu0Sgmqtpakj2oTXNjTpHnHucg9Jk8FH7eTZnyR0yDC6z2wghLKKiAc33kQwvbCkXkqaG6AilSC88/B5c89RX4Cg52+yvM0y4sou6boMo+lcqWZ+kK3a3q3Jm4+m8OeI5wuidI3yZLnZJsl+9cajoGvAmg1e4wIiQgG2ZNM5kyny7nhGTfEmsldMByqHzBRoNkIoHY/LR7FLt5gSWE63cdQiZGfWWS7OMt7E3aUry9rMW06pZFntF5fxZJmsC7CcTVG/quKJxZos8P+r0kwmIp2UNldSA5hnBL3EyO3k3logMFbrHBS+z6yPzdiB6z0inhecL5zC+zHrP
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
