---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCSRz29ePCieO8SfDlB2NwdgVndCyw2Oo1GPzaYYdl9wuqJRuatytBAPyZ0kzdT7PI9USc3ja5PAXwrOXxycrQM75ersQrkWu8UqnLyfhoy0nWktI98pNoSq6cnm+4F0yzBCtKrLoZwxAt+UfI7ikaczXblWAcoYpFJv+zyOTJOkbYd+QK/8lDAm8Zj3o2GYEoUAXQ8CxaJQH893HEY0T6k/iOxYZv3Hm3MvuncmWN0XzwuZGnMeoZt4JRqC5Vy2niGjwAkbtfK7Wt57BUCj+pwXe2nd2/f+ab3aT4bc1j+0cpKFRM1zfsmPz78aZ8ih/ES656x0dmbKC3fa1qA1qazG8y4ITgiv4oz/0Ug0tM6kY8y1rDA566cbmoyixx3LVuqLc3errb+tzujRd2RAgY9CXXllgNNCtrePiTbR5Pkm86tRDZqhsFPmTYx4B//Ygijl0R20QTj33XIl9sHPCYyY3hNrSHOnHBamz0P6/PJz+mhAby/chgkoGouur2cb5MRQ6UVRbNqJ/EV238uLUZtIWkZ+IrDiEgfm09vs5/SumoDGn8RLNTqDwal47EKD2YvBSyGThV/d2+xSNNCL+ArzNoVKBJpWGLSTSeg5jNoCEI0vb6GdE2naka+ESNmaTVCiruBQ/NKXwFlUUqjg7w56xan0m9qy1Ju9AOquYlb8vAl1QalmSBSiUIbGK3HpO0HixA79mLMqeNtnoWMNjSO/ubvRetlEx7mkTZ2IR//C6TbuIS1JZxH
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
