---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgAD2/3Z/o/pMgavjkZE+TF5bhVyJggvvydsqA6y4bxaBQ0rx7JFOlAkSg6qNO3qLBjEPjCvC+6nN+FfBsVv/kXaVUO6f+xR4gm07quTZe9Qoy9lTshI+VQWfgsX0ZyUOMJBt7yhMxfioO+gugToLT9Az1MDPKUhjnrIPUPanFooN7VWeswE0SysfoR+8ngw0y137ud95li7JIHJcTK0EAtB206e88harEHw4JQSk2WB5vIkoTAP64esf43I6R7J+/SxPQXX3EXnJhLmfseTqaMPk4LtYY4YenfyArRDmKJkDoLmNokEIlRxCPH8R6yaclXI/468gn9etxdyFI1HsI352PndYfAzZ+URxI+He7kam8IYLqL1L7owZ7VS2qpkqUdTDU3hR31vk4sly6ZeG50BEqrdKH8C0cJwoW2YnIggoPa7HVb82wPX0UEywlJBy+xgdp8Q6W0GUP39Y9r2QTRhyQG+QKXsDvGAcF7cDubh1aevc66ndd8TLMJ+saIxgSKHMFA0KsuB9vtxHShJ+A9fdsVzDDRb38twcJUO56fdxbNV/snHm98CGdjBLQeZ63MfesktLEWCZRI1EyZM3z8LRwKQQr0w+N7LeI7ozAQc49QCsdINF8db5EB5dFuwuSdiz6/b4yEuimVFg8OAfRqNBw3r2SNpJCpUp8seH1fNjSmcX17HL2zv2n0vBDdNIYPUJsLw+TMdeepCOk0+lxHblSRABOkNQTH+Yu7uDBTb//+xfKhTqYoK/OuQLcCExtP8Dc8XmRa3+AQqQ31BSO5NyTzEXVxliRmju46VgBOXppiO6gShx9dBKLQY9ADLlGS38CywWowt7kOnFL7P8510gdukVh6vBSkinBvxBcR0kvpIlaQIKNMgQZb+RQ==
  template:
    metadata:
      name: vaultwarden-secret
      namespace: vaultwarden
