---
- name: Crear directori pare per a Komodo Stack
  ansible.builtin.file:
    path: "{{ app_data_dir | default('/mnt/nfs') }}/{{ inventory_hostname }}/komodo"
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0755"
  tags: komodo

- name: Crear subdirectoris per a Komodo Stack
  ansible.builtin.file:
    path: "{{ app_data_dir | default('/mnt/nfs') }}/{{ inventory_hostname }}/komodo/{{ item }}"
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0755"
  with_items:
    - data
    - data/core
    - data/mongo
    - data/mongo/config
    - data/mongo/data
    - data/periphery
    - quadlets
  tags: komodo

- name: Copiar fitxers de configuració de Komodo Stack
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ app_data_dir | default('/mnt/nfs') }}/{{ inventory_hostname }}/komodo/quadlets/{{ item }}"
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0644"
  with_items:
    - komodo_core_1.container
    - komodo_mongo_1.container
    - komodo_periphery_1.container
  tags: komodo

- name: Copiar fitxers de configuració de Komodo Stack
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ app_data_dir | default('/mnt/nfs') }}/{{ inventory_hostname }}/komodo/quadlets/{{ item }}"
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0644"
  with_items:
    - komodo.env
    - komodo.network
    - komodo_periphery_1.cil
  tags: komodo

- name: Assegurar que el directori ~/.config/containers/systemd existeix
  ansible.builtin.file:
    path: "/home/{{ rootless_user }}/.config/containers/systemd"
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0755"
  tags: podman

- name: Crear enllaços symlink quadlets de Komodo Stack
  ansible.builtin.file:
    src: "{{ app_data_dir | default('/mnt/nfs') }}/{{ inventory_hostname }}/komodo/quadlets/{{ item }}"
    dest: "/home/{{ rootless_user }}/.config/containers/systemd/{{ item }}"
    state: link
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0644"
  with_items:
    - komodo_core_1.container
    - komodo_mongo_1.container
    - komodo_periphery_1.container
    - komodo.env
    - komodo.network
  tags: komodo

- name: Check periphery SELinux policy installed
  ansible.builtin.command: |
    semodule -l | grep -w komodo_periphery_1
  register: selinux_policy_check
  failed_when: false
  changed_when: false
  tags: komodo, selinux

- name: Install periphery SELinux policy
  ansible.builtin.shell: |
    semodule -i {{ app_data_dir | default('/mnt/nfs') }}/{{ inventory_hostname }}/komodo/quadlets/komodo_periphery_1.cil /usr/share/udica/templates/*
  args:
    creates: /var/lib/selinux/targeted/active/modules/400/komodo_periphery_1
  when: selinux_policy_check.rc != 0
  tags: komodo, selinux

- name: Check existing Komodo secrets
  become: true
  become_method: community.general.machinectl # noqa: schema
  become_user: "{{ rootless_user }}"
  vars:
    ansible_pipelining: true
  containers.podman.podman_secret_info:
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ rootless_uid.stdout | trim }}"
  register: existing_secrets
  tags: komodo

- name: Create missing secrets for Komodo stack
  become: true
  become_method: community.general.machinectl # noqa: schema
  become_user: "{{ rootless_user }}"
  vars:
    ansible_pipelining: true
  containers.podman.podman_secret:
    state: present
    name: "{{ item }}"
    data: "{{ lookup('ansible.builtin.vars', item) }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ rootless_uid.stdout | trim }}"
  loop:
    - komodo_core_1_jwt
    - komodo_core_1_passkey
    - komodo_core_1_webhook_secret
    - komodo_mongo_1_passwd
  when: item not in (existing_secrets.secrets | map(attribute='Spec.Name') | list)
  tags: komodo

- name: Start and enable Komodo containers
  become: true
  become_method: community.general.machinectl # noqa: schema
  become_user: "{{ rootless_user }}"
  vars:
    ansible_pipelining: true
  ansible.builtin.systemd_service:
    name: komodo_periphery_1
    state: started
    enabled: true
    scope: user
    daemon_reload: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ rootless_uid.stdout | trim }}"
  changed_when: false
  tags: komodo
