---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: synology-csi-client-info
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/synology-csi
      recursive: false
  targets:
    - name: synology-csi-client-info
      namespace: synology-csi
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          client-info.yml: |
            clients:
              - host: "ds920plus.home.eudald.gr"
                port: 5551
                https: true
                username: "{{ .SYNOLOGY_USERNAME.Value }}"
                password: "{{ .SYNOLOGY_PASSWORD.Value }}"