secret_pangolin_domain: ENC[AES256_GCM,data:74IEV/NXLo7AfphITLZ6spZb,iv:lBxCkmvpeSr5D0+zNHDHFHhZKufuA+DF1tvrgnLuvi4=,tag:qEWX3xJTvvMjAqXTWoM6Nw==,type:str]
secret_base_domains:
  - ENC[AES256_GCM,data:wwD87ON7DHyv,iv:ZN89Srt12SdFEq4XYDZzvXXYzx/6PXBuY/5cqJRbhPw=,tag:rBM3wfhzVJqMhIyrkwogyg==,type:str]
secret_pangolin_email: ENC[AES256_GCM,data:5XVtzw==,iv:f7+OZsU8eslP5dfmCHGOdKBTeWozLqGDIuQoy7CmUwE=,tag:KqW4MeYRkdR3Az3MeqWi6A==,type:bool]
secret_pangolin_smtp_host: ENC[AES256_GCM,data:rHmwb47ovwZVFLL9gCl/zg==,iv:4ATRo1sQotKkOy4v5v88b5CZIVRC0Hh0yf2VxfXkHxA=,tag:fHW1yKESuyETVm/1k/aidA==,type:str]
secret_pangolin_smtp_port: ENC[AES256_GCM,data:TUbg,iv:jxOmvIO9yEcIz6RyAnfMFmhCRgeQssnIXmkfazD2Ct4=,tag:+nk5apOq6mJs2GXMwC+q5Q==,type:int]
secret_pangolin_smtp_user: ENC[AES256_GCM,data:o8/pb6lJgYLMxmzNtfhMaQ==,iv:RZznnHyw9tQTeV3nzk4BbW1kl9kwkbKoc7nE/MCn3JU=,tag:FYwGcTwiScaF4xFKb/WvuQ==,type:str]
secret_pangolin_smtp_pass: ENC[AES256_GCM,data:CmAdEJUGu9gwNJsJpH3rKV0IitcsMSliVtxXC9peAE22xsjDBLbg/hIuH0GBIMJXZ235YMj+rQd3DiJL+PWf5A==,iv:CmE/5yn/QG+M6efmSNh2jWPjBd0YTzOCmPMammYHq9Y=,tag:+6WVrG1zlMhXTNbiEQGI4Q==,type:str]
secret_pangolin_smtp_secure: ENC[AES256_GCM,data:efIEAg==,iv:YCFLp4BvsUOTXp8zX/O9+3CkcGIkcDvZ/qOW3E4n7/c=,tag:tskrFN8sXUanWKpZC3wcqQ==,type:bool]
secret_pangolin_smtp_no_reply_email: ENC[AES256_GCM,data:UunESFXqEYYc4ES7Ey0vrQw=,iv:RzZ20lsg9aU8AjRr7YqU3woSFpDPGZ7mqn+ASYk5JeQ=,tag:jcuw15zeSRxml2Y2alcs8w==,type:str]
secret_pangolin_traefik_letsencrypt_mail: ENC[AES256_GCM,data:wxGkKrnq9xn1EIcc,iv:3VmxWqXZb+HIE1dgqDa7BsA1U54POKGEBKLGB9ZqlHc=,tag:VqNLJbQBWqFQk6l9hBueww==,type:str]
secret_pangolin_server_secret: ENC[AES256_GCM,data:6rAWziY8AvOeoy7vWju+5r2XoRfQcPIVReEcniyXQXBB3MvdfYtVGnC305U5IvJp/RsQVO2H8xmQU/PiwvejcA==,iv:w3A6yWeixI/RC5cPpsEjuWO6Fc/9emzUVQxoc/UY8YA=,tag:ABUxQZE6SvK2g7p4h9Ci8Q==,type:str]
secret_pangolin_crowdsec_lapi_key: ENC[AES256_GCM,data:DEHRVA9PY8c6Rxu3ROrIpf8S/XRqgsanmQ==,iv:ayxcEYreMEE89Jw1wFfP+pVKm79aDQQAeBB2Rx5fck0=,tag:tIGnvbGRSxRx+EVFOztgAg==,type:str]
sops:
  age:
    - recipient: age1yfrq96mwj6ah0szswj9a8vg8jmyzwl5g6w5u8fh23yg85saxyunss056hg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVVArT1MxUGZ1UGcvRmow
        UEdsc0hldHBpdGRTUHg3cTdQWHUwMVJ1Nmw0CnBNVFI1Wm15K0plaTRtb0V1bW1J
        cDN1SEM3NFBDcSt3enFCb2R3MmxOTEkKLS0tIHBrSityNmVFdjQ2dENFOEkwb3NM
        b0lqeGJqQXd4SWFzLzM2aU8yMmdsTTQK/Pk/mGShE6mR1JSUzo/1n8BhddZk1oFY
        jFBcgqSdniKW6lY6em0zECplBiwaLh4y3LgGIXEq6ug9bGHr6ZF5IQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1vgqjvj49eftfalvhpefvnr4rnrqa4cl28lye4pcsw2638jg0hywqg6l0je
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQ2FtUlUra21HRERRYk1T
        bmJZOTRWU244eWwreENVSm1NcFBZQVhncUhNCjBjZTdrQ0tsa1czYytXMm1RWlZJ
        eTNpZzdRVkIwaGl2dzI2WGRCZU56d1EKLS0tIHpUSWtVTFl4TFhzTkFVNTc4UTF3
        cVNSeWpCaitqMm1FbVdHQ1Y4bXN2b2MKHYnf/Ap0LbZV2m+81IvuU6Kw3ZG54fW/
        zkd8j24glT3SEQ3StEYnHpyZYMFD3yFYVhnO4mcXqArelALxLKoNMA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age175lfmhlkmu8qu07dkxsau62v4vfdczejr66xvf9peg733rrth44shlz5zq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRk5EREJLQmFzM1V1Rlpl
        TGlSUEhyRERsSGgrbzhXZWJqOGZnVWlVL2hzCjlMdUpiSmtMNkkyV0htRHF6VFUr
        Mm1tamF2WHE4cm9MQWNkb3l3ZTRSdXMKLS0tIGVrNE1vaDU3eTJnNktibGsyODNO
        Z2tPaUxtYklrbXRnWlVYM041bWVWUWMKyR3+eQCSuynmqE8HWbfam8M6ptio3WIS
        9rTIqbDTW4cDZc9vh52eyDemba6C/poxO3uDrlht2G8KSQd8H9XYPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-03T12:46:18Z"
  mac: ENC[AES256_GCM,data:h4qGqLzxoDVDPtLLLIqIOp+BhzD023RVI+zHS2kyGNwSS6m1sYHQJsvJlw3j68k6u8dsKE1MqJkRoSvmpl7kCLPMYvek8x8nLdHU+K2lIZQxj52aDnq6U+LvM2NbjoLjfq8rP89+qDs/cxYG3OHC6N/g+3qYhvGexyn1+M3jGhI=,iv:b1950onvHrSj5wVblYDaCZH3p26opUFK0KbiTmn0JEE=,tag:tFxZTbqkGqRbKg+h9KbDTA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
