---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgBoSuO4nVFcMVhWAdytVDTANnyMTlBuQzNDH5pC8dvZCDGrHYTF/wGD0PGhOilcOdcHndrqWhxij4W7zJRXZxR9m/BrQiz7afvUulVDroH8TaD6HK01AQaVaAi4rgnyQBfz2qpxCJ21t4mdSD7IW9WD+fhfn85/HQlp3OrR061ixvIx7KzoXmUI/Rx1jYc9WdbfVl3oQawRxWOxV9oN52/bko88nxR1tBsEEm7o6h1sfX1ogofzdl+KIBlpWdi2lE5BmB/SQyi/VZ/uyUCp31mDU2CWzuVPQ0CZ4b8lzwe0dEAZ/Uto4diK6AFyBhctbSvXQ9HsTXMNvy8hlGHNxqeWCN6Y0I0V0MEKQ6hhjNp/bYatUCLpuEDOHvkk7kGrdRAN4TSqPndsRk9UwomtUXL+7TH21SrvYpD65OpPNrpueHSvdS+g53ppOES41GyoH7QCyTtu9v5k5TaWMEMpX6v/2+ZdpavSYN7SgRwTOHTTkPq7i3LA3QJtg4AZh1K06eEHPrkMOR9RIaUKGoNxoAOMDH4j3M0QgMAwFY2NKds3NvgW5805RSSDALsFimsBTBXdpenDRgq1cOVDu+M1/16pI2scPlYBn27KtHPCoB64DB2iPL4iCYj2iN7UR/KPT2h1DlyycjSD6N6edrwdN/E6MSaLgEvJdD22J4iTkLOeXQcqM1Hi20ArevOhfhAdjTRaTdOMzhHrMDmzM2N1yX7lhRl4uuX7BftTVfNTYJ4GnqtFWAxEoDuvgl4qvE8TDJJsZpwienHOcD/X3g0oQrgj0ZG/heMZkIhFzZG61p3ynKC4fhJCGBgwcUYopv4RUZzZaNTJFBON2h9Qj63Y2dIqSHWA1+oGfZRKkJk4ooI44Rh8s5lHWyz3ZHvju4qFCdkHHoTTOH92+g30+cAsWbUbCv5GjaCLboMuBQTMjiubqwxuBZqZPA==
  template:
    metadata:
      name: proxmox-csi-plugin
      namespace: csi-proxmox
