---
services:
  app:
    image: docker.io/fosrl/newt:1.9.0@sha256:22edec551d81c500a9a3c790a41cd8f7eada3b47ba0a31a187c80d61318e4cc6
    container_name: newt_app_1
    environment:
      - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT}
      - NEWT_ID=${NEWT_ID}
      - NEWT_SECRET=${NEWT_SECRET}
      - DOCKER_SOCKET=/var/run/docker.sock
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:ro
    network_mode: bridge
    restart: unless-stopped
