[[stack]]
name = "newt-host01"
description = "Stack Newt"
deploy = true

[stack.config]
server_id = "host01"
linked_repo = "homelab-host01"
run_directory = "compose/host01/prod/newt"
auto_pull = true
send_alerts = true

compose_cmd_wrapper = """
sops exec-env compose.env '[[COMPOSE_COMMAND]]'"""