---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: cloudflare-issuer
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/cloudflare
      recursive: false
  targets:
    - name: cloudflare-issuer-secret
      namespace: cert-manager
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          CLOUDFLARE_DNS_TOKEN: "{{ .CLOUDFLARE_DNS_TOKEN.Value }}"
