---
- name: Additional manifests for K3s
  when: ansible_host == hostvars[groups['servers'][0]]['ansible_host'] | default(groups['servers'][0])
  block:
    - name: Create manifests directory on first server
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/server/manifests
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy kube-vip manifests
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: /var/lib/rancher/k3s/server/manifests/{{ item }}
        owner: root
        group: root
        mode: "0644"
      loop:
        - vip-rbac.yaml
        - vip.yaml

- name: Clean previous runs of k3s-init
  ansible.builtin.systemd_service:
    name: k3s-init
    state: stopped
  failed_when: false

- name: Clean previous runs of k3s-init # noqa: inline-env-var
  ansible.builtin.command: |
    systemctl reset-failed k3s-init
  failed_when: false
  changed_when: false
  args:
    warn: false # The ansible systemd module does not support reset-failed

- name: Init cluster inside the transient k3s-init service
  ansible.builtin.command: |
    systemd-run -p RestartSec=2 \
      -p Restart=on-failure \
      --unit=k3s-init \
      k3s server --flannel-backend=none --disable-network-policy {{ server_init_args }}
  changed_when: true

- name: Verification
  block:
    - name: Verify that all nodes actually joined (check k3s-init.service if this fails)
      ansible.builtin.command:
        cmd: k3s kubectl get nodes -l "node-role.kubernetes.io/control-plane=true" -o=jsonpath="{.items[*].metadata.name}"
      register: k3s_nodes
      until: k3s_nodes.rc == 0 and (k3s_nodes.stdout.split() | length) == (groups['servers'] | length)
      retries: "{{ retry_count | default(20) }}"
      delay: 10
      changed_when: false
  always:
    - name: Kill the temporary service used for initialization
      ansible.builtin.systemd_service:
        name: k3s-init
        state: stopped
      failed_when: false

- name: Copy K3s config file
  ansible.builtin.template:
    src: k3s.server.config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: "0644"

- name: Copy K3s service file
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: "0644"

- name: Enable and check K3s service
  ansible.builtin.systemd_service:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true

- name: Wait for node-token
  ansible.builtin.wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Read node-token from server
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_node_token

- name: Store Server node-token
  ansible.builtin.set_fact:
    k3s_token: "{{ k3s_node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Create directory .kube
  ansible.builtin.file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="

- name: Copy config file to user home directory
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: true
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="

- name: Configure kubectl cluster to https://{{ kube_vip_lan_ip }}:6443 # noqa: name[template]
  ansible.builtin.command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ kube_vip_lan_ip }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  changed_when: true
# - name: Install additional charts
#   when: inventory_hostname == groups['servers'][0] | default(groups['servers'][0])
#   block:
#     - name: Add helm repo
#       kubernetes.core.helm_repository:
#         name: "{{ item.name }}"
#         repo_url: "{{ item.repo }}"
#       loop:
#         - { name: "cilium", repo: "https://helm.cilium.io/" }
#         - { name: "coredns", repo: "https://coredns.github.io/helm" }

#     - name: Install chart
#       ansible.builtin.command:
#         cmd: "{{ item }}"
#       loop:
#         - "helm install cilium cilium/cilium -n kube-system {{ cilium_values }} --kubeconfig ~{{ ansible_user }}/.kube/config"
#         - "helm install coredns coredns/coredns -n kube-system {{ coredns_values }} --kubeconfig ~{{ ansible_user }}/.kube/config"
#       changed_when: true
