apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard
  namespace: adguard
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: adguard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - dns.eudald.gr
    - dns01.eudald.gr
    - dns02.eudald.gr
  privateKey:
    algorithm: RSA
    rotationPolicy: Always
