---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adguard-admin-secret
  namespace: adguard
spec:
  encryptedData:
    username: AgAf3Nh5mqiFjVw/NjzQUZHbl8p0i8nv8sAJNSkFvvl5/L3ZP48E2btohduGHxpCkxO38G6OXpuE4oufoeI/gIquukbFQUo1VaXVeZfg0h68RXRjw7i2YN6hNgmxU/K02qieutqVLhi/v2P0M1fHxetPpQ1l7qsfhzQUQoajSnD7NeMXIJ2ZHT+w/jMuCU9P6akNEy+QEtGqB9g3CK4ev+8I1pci3EOIpVPKLpJWxPTbwE51OD7jHxOPU2JAL8SzRESZDx9NRrrMzdkEEI/OFiBmbGJCgq0eCT1dhTjwW4CNrccbqbyWeSPPqqak5kgu28saX8Mjmv+S3oz67tE+CFQ/6kVwaySTp34CRkuAnkkdX9i9GNcYKDtBP+rbPMmeFwGdG29MGLM97jlLKBFrehv5uf3oK6RlwDpDoAfOrjoyfc+WXfbJWES9OdikT6f4wyQyixIDxz9J33JgPFewQO5F6zGKNqdxI9j8pUW+oY1FY5xhKkUAGcN352hSAOITSJtLeBfNpyeS2GIL3J0ZZKOPrtx/bShzu+5TW98CNwp+dKnxhGpCHgoWpICiVSzoSDT2TNUTEW3GP3i2YkX73782Z2YFwNRLimjMhVfmxyLMgnUg7mZ8Tj8gCy7pQOgaHXLrfwVgJDfjGB6DtBRmaN0ZzXOgRB5d1CZeAdbDfFpv6FjNjdX2gMdX3S+neDstlHtOakMFwA==
    password: AgBMbDN0Qo15tNIkzab2Ucf+clvaL/m9a7n9lPX+r7jRFfHLe9cAU7r2T7ZqPEYrcc7hG4YG6PX2vUNtz//RGzUzuWNlwg8nUuijx4+BnewX2peQOikQuGgtOfAo4rh2e6ltjjLNJfeAAGrrnX9P8qa+w1OR7tqVyGed0XEjCgVmLJL6u8FOTtM05vAOQFkl3eJVjJUlQZC9j3YPdU16111oLxssQK1/niF2dahaZKwTRiSjvV8opCHAB1DEYJrreygYQp58+aJoCYnAcQXy7Kd80sVU8oZF+95OunwUpc36jbcxLG0q4EXD/BQ7lfqXkVNrsQjGI2WljD6aelolsLFaZ6Bvp2jjnqOhIsJIuJJpI5vJf9U65CU+vqlr4eePPaQeJy/J5RKMZH0N3dBC9CKD2g1J1Cu2SNCxoeDW6n3qLrPD7DTHxIMPVtsmVBD9k+4zzM55gVlzapTJm+ymmyysbA7Lha8uddir3vhZSM1Vox+Vbi3l+dlaoLu8S24RfLyM01RytTReR0ISm3i1x243TuhXNhMtCPjujapMFZmYdkFqwg52WrEJKXW22GMiiBhgE6ijASV+16FNESxSEf9JYWI7pnUZI8m9CdQ8i1ulYjfjS47IUkO87fksj+4k3cX6nCn39TBoNBy3gH4gp2uDBHOvWNWSfG8tcyVDrMmuyKYPF8DU3lUbK+T7fF3/1HvATqbDvN2e1h3nWVz4ifVP7+NXnJVtKlt65dGnckHLe/2GPna5zLm+tV4aqmrjg/f+74ZwXjEmX1JaLUxi3eZK
  template:
    metadata:
      name: adguard-admin-secret
      namespace: adguard
