apiVersion: v1
kind: Service
metadata:
  name: minicpm-vllm
  namespace: minicpm-vllm
  labels:
    app: minicpm-vllm
spec:
  type: ClusterIP
  selector:
    app: minicpm-vllm
  ports:
    - name: http
      port: 80
      targetPort: http
