---
name: caddy-l4

services:
  caddy-l4:
    image: ghcr.io/bjw-s-labs/caddy-l4:2.11.4@sha256:f404cca91837bae9a304cf1efbec7da8bbbaa8e00a9cba3060cde99d6a176d81
    container_name: caddy-l4
    environment:
      CADDY_ACME_EMAIL: ${CADDY_ACME_EMAIL}
      VPS_LOCAL_HOSTS: towonel.eudald.gr
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - data:/data
      - config:/config
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
    restart: unless-stopped

volumes:
  data: {}
  config: {}

configs:
  caddyfile:
    file: ./Caddyfile

networks:
  default:
    name: edge
    external: true
