apiVersion: v1
kind: ConfigMap
metadata:
  name: kromgo-config
  namespace: kromgo
data:
  config.yaml: |
    prometheus: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
    gallery:
      enabled: true
    cache:
      enabled: true
      maxAge: 300
    defaults:
      badge:
        style: flat
    badges:
      - id: targets
        title: Targets
        query: count(up == 1)
        valueExpr: humanizeFloat(result) + " up"
        colorExpr: result > 0.0 ? "green" : "red"
        icon: si:prometheus
      - id: nodes
        title: Nodes
        query: count(kube_node_info)
        valueExpr: humanizeFloat(result)
        colorExpr: result > 0.0 ? "green" : "red"
        icon: mdi:server-outline
      - id: pods
        title: Pods
        query: count(kube_pod_status_phase{phase="Running"})
        valueExpr: humanizeFloat(result) + " running"
        colorExpr: result > 0.0 ? "green" : "red"
        icon: si:kubernetes
      - id: cpu
        title: CPU
        query: round(100 * (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m]))), 0.1)
        valueExpr: humanizeFloat(result) + "%"
        colorExpr: colorScale(result, [60.0, 85.0], ["green", "orange", "red"])
        icon: mdi:cpu-64-bit
      - id: memory
        title: Memory
        query: round(100 * (1 - sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)), 0.1)
        valueExpr: humanizeFloat(result) + "%"
        colorExpr: colorScale(result, [70.0, 90.0], ["green", "orange", "red"])
        icon: mdi:memory
    graphs:
      - id: cpu
        title: Cluster CPU %
        query: 100 * (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m])))
        theme: light
        yMin: 0
        yMax: 100
        valueExpr: humanizeFloat(result) + "%"
      - id: memory
        title: Cluster Memory %
        query: 100 * (1 - sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes))
        theme: light
        yMin: 0
        yMax: 100
        valueExpr: humanizeFloat(result) + "%"
