---
services:
  app:
    image: ghcr.io/searxng/searxng:2025.12.17-896863802@sha256:a39ce90965a1650655c10f6e1b83bf0d1f09caf9af3ea182196e53f158f2bc5d
    container_name: searxng_app_1
    user: "977:977"
    userns_mode: "keep-id:uid=977,gid=977"
    ports:
      - "5147:8080"
    volumes:
      - ${APP_DATA_DIR}/searxng/config:/etc/searxng:rw
      - cache:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      # Public Resource Configuration
      - pangolin.proxy-resources.searxng.name=searxng
      - pangolin.proxy-resources.searxng.full-domain=${SEARXNG_HOSTNAME}
      - pangolin.proxy-resources.searxng.protocol=http
      # Target Configuration - Override to Host Hairpin
      - pangolin.proxy-resources.searxng.targets[0].method=http
      - pangolin.proxy-resources.searxng.targets[0].hostname=host.containers.internal
      - pangolin.proxy-resources.searxng.targets[0].port=5147
      # Health Check Configuration
      - pangolin.proxy-resources.searxng.targets[0].healthcheck.enabled=true
      - pangolin.proxy-resources.searxng.targets[0].healthcheck.hostname=host.containers.internal
      - pangolin.proxy-resources.searxng.targets[0].healthcheck.port=5147
      - pangolin.proxy-resources.searxng.targets[0].healthcheck.path=/healthz
    restart: unless-stopped

  valkey:
    image: docker.io/valkey/valkey:8.1.5-alpine@sha256:70aa61b8e741ee66d8976eab1418d408067df3624c3a3732d91f95fdddd4f0e8
    container_name: searxng_valkey_1
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - valkey:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: unless-stopped

volumes:
  cache:
  valkey:
