apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ersatztv-media
  namespace: ersatztv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  volumeName: ersatztv-media
  storageClassName: ""
