apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ersatztv-config
  namespace: ersatztv
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
