---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  labels:
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/part-of: flux
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    homelab.eudald.gr/description: Flux Operator and Flux controllers
