---
services:
  testnet3:
    image: ghcr.io/eudaldgr/docker-bitcoind-core:latest
    container_name: bitcoind-core_testnet3_1
    user: "${PUID}:${PGID}"
    command: ["-datadir=/data/.bitcoin", "-chain=test"]
    ports:
      # - "8332:8332" # Mainnet RPC
      # - "8333:8333" # Mainnet P2P
      - "18332:18332" # Testnet3 RPC
      - "18333:18333" # Testnet3 P2P
      # - "48332:48332" # Testnet4 P2P
      # - "48333:48333" # Testnet4 RPC
      # - "38332:38332" # Signet RPC
      # - "38333:38333" # Signet P2P
      # - "18443:18443" # Regtest RPC
      # - "18444:18444" # Regtest P2P
    volumes:
      - ${APP_DATA_DIR}/bitcoind-core/data:/data/.bitcoin
    restart: unless-stopped

  testnet4:
    image: ghcr.io/eudaldgr/docker-bitcoind-core:latest
    container_name: bitcoind-core_testnet4_1
    user: "${PUID}:${PGID}"
    command: ["-datadir=/data/.bitcoin", "-chain=testnet4"]
    ports:
      # - "8332:8332" # Mainnet RPC
      # - "8333:8333" # Mainnet P2P
      # - "18332:18332" # Testnet3 RPC
      # - "18333:18333" # Testnet3 P2P
      - "48332:48332" # Testnet4 P2P
      - "48333:48333" # Testnet4 RPC
      # - "38332:38332" # Signet RPC
      # - "38333:38333" # Signet P2P
      # - "18443:18443" # Regtest RPC
      # - "18444:18444" # Regtest P2P
    volumes:
      - ${APP_DATA_DIR}/bitcoind-core/data:/data/.bitcoin
    restart: unless-stopped

  signet:
    image: ghcr.io/eudaldgr/docker-bitcoind-core:latest
    container_name: bitcoind-core_signet_1
    user: "${PUID}:${PGID}"
    command:
      [
        "-datadir=/data/.bitcoin",
        "-chain=signet",
        "-addnode=89.147.108.149:38333",
        "-signetchallenge=00144b4ef981ad360b21e2a758954e5152d8390e6598",
      ]
    ports:
      # - "8332:8332" # Mainnet RPC
      # - "8333:8333" # Mainnet P2P
      # - "18332:18332" # Testnet3 RPC
      # - "18333:18333" # Testnet3 P2P
      # - "48332:48332" # Testnet4 P2P
      # - "48333:48333" # Testnet4 RPC
      - "38332:38332" # Signet RPC
      - "38333:38333" # Signet P2P
      # - "18443:18443" # Regtest RPC
      # - "18444:18444" # Regtest P2P
    volumes:
      - ${APP_DATA_DIR}/bitcoind-core/data:/data/.bitcoin
    restart: unless-stopped
