[[stack]]
name = "bitcoind-core-ds920plus"
description = "Stack Bitcoind Core"
deploy = true

[stack.config]
server_id = "ds920plus"
linked_repo = "homelab-ds920plus"
run_directory = "compose/ds920plus/prod/bitcoind-core"
auto_pull = true
send_alerts = true

compose_cmd_wrapper = """
/opt/sops exec-env compose.env '[[COMPOSE_COMMAND]]'"""