---
- name: Download GeoLite2 databases
  ansible.builtin.get_url:
    url: "https://github.com/GitSquared/node-geolite2-redist/raw/refs/heads/master/redist/{{ item }}.tar.gz"
    dest: "/tmp/{{ item }}.tar.gz"
    mode: "0644"
  loop:
    - GeoLite2-Country
    - GeoLite2-ASN

- name: Extract GeoLite2 databases
  ansible.builtin.unarchive:
    src: "/tmp/{{ item }}.tar.gz"
    dest: /tmp
    remote_src: true
  loop:
    - GeoLite2-Country
    - GeoLite2-ASN

- name: Find extracted GeoLite2 databases
  ansible.builtin.find:
    paths: /tmp
    patterns: "{{ item }}"
    recurse: true
    file_type: file
  loop:
    - GeoLite2-Country.mmdb
    - GeoLite2-ASN.mmdb
  loop_control:
    loop_var: item
  register: geolite2_file

- name: Move GeoLite2 databases to Pangolin config directory
  ansible.builtin.copy:
    src: "{{ item.files[0].path }}"
    dest: "/etc/pangolin/{{ item.item }}"
    owner: root
    group: root
    mode: "0644"
    remote_src: true
  loop: "{{ geolite2_file.results }}"
  loop_control:
    loop_var: item
  when: item.files | length > 0

- name: Clean up GeoLite2 database temporary files
  ansible.builtin.file:
    path: "/tmp/{{ item }}.tar.gz"
    state: absent
  loop:
    - GeoLite2-Country
    - GeoLite2-ASN

- name: Clean up extracted GeoLite2 directories
  ansible.builtin.file:
    path: "{{ item.files[0].path | dirname }}"
    state: absent
  loop: "{{ geolite2_file.results }}"
  loop_control:
    loop_var: item
  when: item.files | length > 0
