---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: searxng-secret
  namespace: searxng
spec:
  encryptedData:
    SEARXNG_SECRET: AgAvh+dXj1wN/SfJXvK49WsPo4uIT2s/DoyEQdbZmO1HG3E0O7NkBKjrQp7H8/djKWkZ+QU9xaQzMluvItgKoHN3oO1jY58xOih8+/Z/j5Mn7wQNZcCumow02sX9ew+l+NXYWHTlI6CbVywGgvR0R1LBHlbIwdfH5TMctiFj5h7EbC28rheWl10DLkM+bKn613imz9feg42xpOEB5gc/Hax/iCbquYDWL3iy4AFOB8mmU4Jsl+3JFsJ80Kg7bVLeMLe63Lk39ZzKBaCAhD2+IoJ2O9y/ty+qCYjTELEYlGGVPAW6cB6hIll2pxPER34YCxpDVllXYJjsZ0yy/tXnyR1lIiuefqBKKlv3Bj4CCc28Hx4g/BpFH2kAy5iJDHNmBlRJbCosVMak+s6lRr9Pel+9eJ+SGoHOsPcnYIYJlnbMbSal+a6xZRCMUhR6kPTSmomQ1RBpxq23hTGydc/cUWJwcn+CCpsX7pS5rg01vGniVPoMtw6djUzR74a5+DcvPIQPbEkKH8xmeClnl/c1Ll8l9S4+TPG1B75Z+lsdmtkB0poWyaKUzX4iv5nY/MIPAGgle6fyNhbEZpS93q94MKzQX7tuyCQlrWq5b58XiuaTXavdw5nCI15oOivRLl8NiOFYrhvLqLfSjptJ89lKERjCZAmIKc2kBFFJ2Od0bSFJeOtPlJWv18Lv/pgOz/O8f9bJCPl33w4wCKEi9unTgLI6Y0i4cj8ov6rFUwo=
  template:
    metadata:
      name: searxng-secret
      namespace: searxng
