---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opnsense-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: 1.21.1
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: opnsense-dns
  interval: 1h
  timeout: 10m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    fullnameOverride: opnsense-dns
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/crutonjohn/external-dns-opnsense-webhook
          tag: main@sha256:92bc3f6cedbc964a15902117f25ef42d87f74742ee9c4ed4900085d3edc56857
        env:
          - name: OPNSENSE_API_KEY
            valueFrom:
              secretKeyRef:
                name: opnsense-dns-secret
                key: OPNSENSE_API_KEY
          - name: OPNSENSE_API_SECRET
            valueFrom:
              secretKeyRef:
                name: opnsense-dns-secret
                key: OPNSENSE_API_SECRET
          - name: OPNSENSE_HOST
            value: https://10.1.90.1
          - name: OPNSENSE_SKIP_TLS_VERIFY
            value: "true"
          - name: LOG_LEVEL
            value: info
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    triggerLoopOnEvent: true
    extraArgs:
      - --gateway-name=envoy-internal
    policy: sync
    registry: noop
    sources:
      - service
      - ingress
      - gateway-httproute
    domainFilters:
      - eudald.gr
    publishInternalServices: true
    podAnnotations:
      secret.reloader.stakater.com/reload: opnsense-dns-secret
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 192Mi
