---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: opnsense-dns
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/opnsense
      recursive: false
  targets:
    - name: opnsense-dns-secret
      namespace: network
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          OPNSENSE_API_KEY: "{{ .OPNSENSE_API_KEY.Value }}"
          OPNSENSE_API_SECRET: "{{ .OPNSENSE_API_SECRET.Value }}"