apiVersion: v1
kind: ConfigMap
metadata:
  name: bedrockconnect-config
  labels:
    app.kubernetes.io/name: bedrockconnect
    app.kubernetes.io/part-of: games
data:
  custom_servers.json: |
    [
      {
        "name": "PixelStack",
        "address": "pangolin.eudald.gr",
        "port": 19132
      }
    ]
