apiVersion: v1
kind: Service
metadata:
  name: bedrockconnect
  labels:
    app.kubernetes.io/name: bedrockconnect
    app.kubernetes.io/part-of: games
  annotations:
    lbipam.cilium.io/ips: "10.1.20.154,10.1.42.154"
    external-dns.alpha.kubernetes.io/hostname: "geo.hivebedrock.network,hivebedrock.network,play.inpvp.net,mco.lbsg.net,play.galaxite.net,play.enchanted.gg"
    external-dns.alpha.kubernetes.io/target: "10.1.20.154"
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: bedrockconnect
  ports:
    - name: bedrock
      port: 19132
      targetPort: bedrock
      protocol: UDP
