---
- name: Prepare container hosts nodes
  hosts: container_hosts
  gather_facts: false
  become: true
  roles:
    - nfs
    - prepare-podman

- name: Prepare komodo core node
  hosts: komodo_core
  gather_facts: false
  become: true
  roles:
    - komodo-core

- name: Prepare komodo periphery nodes
  hosts: komodo_periphery
  gather_facts: false
  become: true
  roles:
    - komodo-periphery

- name: Sync periphery pubkeys into core
  hosts: komodo_core
  gather_facts: false
  become: true
  tasks:
    - name: Include periphery keys bundle tasks
      ansible.builtin.import_tasks: roles/komodo-core/tasks/periphery_keys.yaml

- name: Show Komodo public keys
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show Komodo keys
      ansible.builtin.debug:
        msg: >-
          {% for host in groups['komodo_core'] %}
          core-{{ host }}: {{ hostvars[host].komodo_core_public_key
            | regex_replace('-----BEGIN PUBLIC KEY-----\n','')
            | regex_replace('\n-----END PUBLIC KEY-----\n','')
            | trim }}{% endfor %}
