---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: snmp-exporter
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/o11y/snmp-exporter
      recursive: false
  targets:
    - name: snmp-exporter-secret
      namespace: o11y
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          SNMP_USERNAME: "{{ .SNMP_USERNAME.Value }}"
          SNMP_AUTH_PASSWORD: "{{ .SNMP_AUTH_PASSWORD.Value }}"
          SNMP_PRIV_PASSWORD: "{{ .SNMP_PRIV_PASSWORD.Value }}"
