trashGuideUrl: https://github.com/TRaSH-Guides/Guides
recyclarrConfigUrl: https://github.com/recyclarr/config-templates
recyclarrRevision: 4ae377bb704fc7fd69a544ad04e91357e0b09f62
localCustomFormatsPath: /configarr/etc/cfs
localConfigTemplatesPath: /configarr/etc/templates
telemetry: false

radarr:
  movies:
    base_url: http://radarr.media.svc.cluster.local
    api_key: !env RADARR_API_KEY
    include:
      - template: radarr

sonarr:
  series:
    base_url: http://sonarr.media.svc.cluster.local
    api_key: !env SONARR_API_KEY
    include:
      - template: sonarr