apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero

resources:
  - ../../base
  - sealed-secrets.yaml
  - storage-locations/
  - schedules/
  - repository-config.yaml
  - backuprepository-policy.yaml
  - auto-cleanup-jobs-policy.yaml

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 11.3.2
    releaseName: velero
    namespace: velero
    valuesFile: values.yaml
    includeCRDs: true

generatorOptions:
  disableNameSuffixHash: true
