---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-rustfs-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCdXf65xsl2c8bMG87LLn9P3gkw9/AXoxIgKPvWgt+eXLudoXZiOf2WRpKyawjIz/v4Ii72EVVtmxNuO6gntBtMnDEdPf6CLr7sc/bXUE2N7VGH0drJrLbWdIpbqsT1OXEPWqGzF4NNKIJ2sWQmC/gJywq9hN7h/X3X6dF0CZr/HWwYtysKu6TbKkbTUGi0TQ536yLlKfVR3u3Z3/UFy7b73P/DcNQjqrv51Kc8IiOIDZ3S/7aAvSf+dwzDQEksEwOz+sLqN5aXa0EMFdZDc/9CvXXIy1zTvlBmqf+8WJe3aAezvh2DFVFPvuZ7vU0jDXK5Ow2MCZO04Acoe2ESUwxoD9TECT1ZAATT8Ydy13m7JLY8+mHeXGfBcGLarA/ZtriyDWejNnxh9ZxTRYZMKdXPo9jhZJ/8xjlYWgREsl7OcF6vXWMVywfdviw42PImaKZItzP/sEuhD5BmTmxCdeST967ChitqNs/CHBVrTv9puVa/cmdex4WzoC1Qt2XH7fdxRXMXjrDYkb4WFbDZca8TVbYQBVlSkF58UBlaGInJaolTFRGeFuCaWi2hF8oK6jlVrltCk4wbkvqbSMNRseMMJTTGBGx3NaTuhjing+BkAjGS+5QYxZVCePVgGOTcWc7FhAcSxMPtfF2+B+gsns/UWZIfBodBO2+S/qsXlHabgekSZfpJHAJXoym+UwGGx6eRDfcw6mNxHaB3Ygxs7XuxWjMQ6TlFAMT9DjMXFgXp593mZ0luZWKRv2lo0wymGLasqpGXUryEBQgeIR/Tw5j0PL3Btew5Q37HQWlHH3MxgfRmbge+gXj4p8SHrgCiWGdjQs43fkMZWhofdg/2+h5JC0rFW4lZIlJR7BBfsA/oOBA6uAmZEUFSP4wOic6UCEoSY08BIGqKfrAz886wtPfBCiM=
  template:
    metadata:
      name: velero-rustfs-credentials
      namespace: velero
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-b2-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCBEvQdHWJ4evhHCTJjh14+n0NEYRpthnI5foMERBW7XKffKuXvctRyCGlX7iIgVoYmUVp8njw+x++BLMDqwSwlQx6ffgXEfZzVH3R4rqaf4OHmrIB5wLKPxJcbJE7pauEc91NEtEhRyK3WGun/qpl6UYP3NDM7PYGh9SoiM6Ah+o8eC5/tLHE1o9o9UOnoA0goVOENgK7yZolWbm3FxMVf+G2OEnCC7pIivg2fSvhp/J/Ed5Sz2aXYB6TWdd5UpkybBQJxkyaMhX6dpgchYrLe6esr1VPUJvTi8vyneAcPB+QruL1aW98tl3b8WSS3rEQm58kgV51RuLXLo2QMHbkXQ5TJs2XkOgyjVYF7MNSkV3t2aLnuMEbaJ/W5jBMVurqc0SbiE3/uxQ/wkVHc6rC+FmaJCUNPjscYMnbmTkmXlXDNM+IpJ+jF7fFXvr2bBQrRB9ZnZouoLsC4h2vAVzu7oOapIng3UH9M4zXBWsb6WHQyc3vLnuFSpTzFx9l+RxT11on6Tk7mdAEbVck1DaXDOeKGL1qhx+d5xMkdCZnlap4b2mEBhaZU9nfiQg4PTIF9GBA5FrQwe63OAtRRecHRYrf26g/HYloRs5ip+VLQZPB5cLY3m9FkxAQSmFHAlhlG9V3edpWwQqENkzgLCoOwWOfKHGQX/oa69LZaQNGQK30vxkt+yKvGjWt559sCDpZAMZ5HthpVyI5dTBb5+kUUxk2xkw6W3NP5KfBSXtAzdY7rLTIF83jXGqGj5bmTwfGCrn0k/J2S7lnib/GTYcMROwndNqe0lkdqIEjqbumQCqt6DGBnfWios/ZpLFR41pU5rFAYRb7qBGNmXaQ=
    repository-password: AgBfPpWIc8TWqX1JJkxtnasT21QqQ5jWZ/jyX4BJOZA/LJfmuERXA20dNjS2akLDYYVv6UBYpUb6Ociqh9X2mtIJRgOfQhFFEgooalycUWHTJwNTxBK0Dm70G86+JY6VjLeC11/Lj0MJlUJTOsh72IGi6MwpXPNZWtpYizfCcuE6xUvjzI5HffYL3Pd5r/Q2R2UTf+j6Ahe+KGdJZp20K7sDIyuXxX+pcPBwo+BaTeYyy6T5KBt7M3MFVHUuBHG1oF7niDLuDoRV3lS6XfIUOj9rGL2TKStpfbqRyIskp2iizVqlAOxhX8MNGIv08Jhz+RIi0LnGxuksD+0AOH0rnpEECi0M0tj9DarMVKHi7m9xbGUzXvHrDnp8BhgaHx7pWV2L1q64yRa9P+d4mn9v2T4qi0f6ileQaPN3/OLGxL5kV7pJwcGOoEj5A4yj+xiiulkRXT2ZE3SNQghvKIi3gQVaGOrdghY670JBfjXAUUW2mYzkhomaQgTWCgihul7vQX3ARDkWnUJT1gvtahYzAJaUjKf6MDwoJ42CN+BztVVjHqVzS7b/n0vonq5YJgLUMfttaucQRGNs/FvFH1GQQwA+ESUg6tlhbJYQjeabwAr65+fuEgMfpS1eswtZrSeGJC9oG97VE6dLa9e/YsEaO++IJYBaP6n2MEgTRA+21afnLDCrFwLmPZfkGWSQhlKihFfsoP8IrrZRz0NO243Gi3oJZWxGMFGmNMQl02TqN2i4hE905VZZeOY7MYRnDXPj1I6pwoNFXu7FaJPvutNU0aks
  template:
    metadata:
      name: velero-b2-credentials
      namespace: velero
