---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-rustfs-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: REPLACE_WITH_KUBESEAL_ENCRYPTED_VALUE
  template:
    metadata:
      name: velero-rustfs-credentials
      namespace: velero
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-b2-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: REPLACE_WITH_KUBESEAL_ENCRYPTED_B2_CLOUD_VALUE
    repository-password: REPLACE_WITH_KUBESEAL_ENCRYPTED_B2_REPOSITORY_PASSWORD_VALUE
  template:
    metadata:
      name: velero-b2-credentials
      namespace: velero
