apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: newt

resources:
- namespace.yaml
- sealed-secrets.yaml

# configMapGenerator:
# - name: newt-blueprint
#   files:
#   - blueprint.yaml=blueprints/public-resources.yaml

helmCharts:
- name: newt
  repo: https://charts.fossorial.io
  version: 1.5.0
  releaseName: newt
  namespace: newt
  includeCRDs: true
  valuesFile: values.yaml

generatorOptions:
  disableNameSuffixHash: true
