---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: pocket-id
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/auth/pocket-id
      recursive: false
  targets:
    - name: pocket-id-secret
      namespace: auth
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY.Value }}"
