---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: admins
spec:
  name: admins
  friendlyName: Admins
  users:
    usernames:
      - eudaldgr
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: family
spec:
  name: family
  friendlyName: Family
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: relatives
spec:
  name: relatives
  friendlyName: Relatives
