name: speedtest

services:
  chown:
    image: ghcr.io/vegops/chown:latest
    container_name: speedtest_chown_1
    volumes:
      - ${APP_DATA_DIR}/data:/chown
    command: "-R 65532:65532 /chown"

  tracker:
    image: lscr.io/linuxserver/speedtest-tracker:1.14.5@sha256:4c698dc3a5d989c8d92512600d303f23ff2e6e789c89674adb083372ac67fe2c
    container_name: speedtest_tracker_1
    depends_on:
      chown:
        condition: service_completed_successfully
    ports:
      - 8080:80
      - 8443:443
    environment:
      - PUID=65532
      - PGID=65532
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=sqlite

      - APP_TIMEZONE=${TZ}
      - DISPLAY_TIMEZONE=${TZ}
      - SPEEDTEST_SCHEDULE=0 * * * *
    volumes:
      - ${APP_DATA_DIR}/data/etc:/config
      - ${APP_DATA_DIR}/data/keys:/config/keys
    restart: unless-stopped
