---
name: crowdsec
services:
  crowdsec:
    image: ghcr.io/crowdsecurity/crowdsec:v1.8.1@sha256:0f2523fa61ef507f15d953045cface490cc880670c62f2755ced17524107f71a
    container_name: crowdsec
    environment:
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/sshd crowdsecurity/iptables"
      PARSERS: "crowdsecurity/geoip-enrich"
      GID: "1000"
    volumes:
      - /var/log:/var/log:ro
      - /run/systemd/journal:/run/systemd/journal:ro
      - etc:/etc/crowdsec
      - var:/var/lib/crowdsec/data
      - ./scenarios:/etc/crowdsec/scenarios/custom:ro
      - ./whitelists:/etc/crowdsec/parsers/s02-enrich/custom:ro
      - ./acquis.d:/etc/crowdsec/acquis.d/custom:ro
      - ./config/config.yaml.local:/etc/crowdsec/config.yaml.local:ro
    ports:
      - "127.0.0.1:8088:8080"
    healthcheck:
      test:
        - "CMD"
        - "cscli"
        - "lapi"
        - "status"
      interval: 30s
      timeout: 5s
      start_period: 60s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "1.0"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
volumes:
  etc:
  var:
networks:
  default:
    name: edge
    external: true
