---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: vaultwarden
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/vaultwarden
      recursive: false
  targets:
    - name: vaultwarden-secret
      namespace: vaultwarden
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          ADMIN_TOKEN: "{{ .ADMIN_TOKEN.Value }}"