apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gramps-web
  namespace: gramps-web
spec:
  parentRefs:
    - name: internal
      namespace: gateway
  hostnames:
    - gramps.k8s.eudald.gr
  rules:
    - backendRefs:
        - name: gramps-web
          port: 5000
