apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gramps-web

resources:
- namespace.yaml
- sealed-secret.yaml
- valkey-deployment.yaml
- valkey-svc.yaml
- statefulset.yaml
- svc.yaml
- http-route.yaml
