apiVersion: apps/v1
kind: Deployment
metadata:
  name: gramps-web-valkey
  namespace: gramps-web
  labels:
    app: gramps-web-valkey
    app.kubernetes.io/name: gramps-web-valkey
    app.kubernetes.io/part-of: applications
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gramps-web-valkey
  template:
    metadata:
      labels:
        app: gramps-web-valkey
    spec:
      automountServiceAccountToken: false
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: valkey
          image: docker.io/valkey/valkey:9-alpine@sha256:de31910896150d5e754a07d57d227cfdde4e258ddd0d1aa4607f2d2f95843715
          ports:
            - name: valkey
              containerPort: 6379
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            tcpSocket:
              port: valkey
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: valkey
            initialDelaySeconds: 10
            periodSeconds: 15
