name: bentopdf

services:
  app:
    image: ghcr.io/vegops/bentopdf:latest
    container_name: bentopdf_app_1
    ports:
      - 3183:8080
    labels:
      # Public Resource Configuration
      - pangolin.public-resources.bentopdf.name=bentopdf
      - pangolin.public-resources.bentopdf.full-domain=${BENTOPDF_HOSTNAME}
      - pangolin.public-resources.bentopdf.protocol=http
      # Target Configuration
      - pangolin.public-resources.bentopdf.targets[0].method=http
      - pangolin.public-resources.bentopdf.targets[0].hostname=127.0.0.1
      - pangolin.public-resources.bentopdf.targets[0].port=3183
      # Health Check Configuration
      - pangolin.public-resources.bentopdf.targets[0].healthcheck.enabled=true
      - pangolin.public-resources.bentopdf.targets[0].healthcheck.hostname=127.0.0.1
      - pangolin.public-resources.bentopdf.targets[0].healthcheck.port=3183
      - pangolin.public-resources.bentopdf.targets[0].healthcheck.path=/
    restart: unless-stopped
