---
- name: Prepare k3s cluster
  hosts: cluster
  gather_facts: false
  become: true
  environment:
    K8S_AUTH_KUBECONFIG: "{{ kubeconfig_path }}"
  roles:
    - k3s
    - cilium
    - kube-vip

- name: Deploy ArgoCD
  hosts: servers[0]
  gather_facts: false
  become: true
  environment:
    K8S_AUTH_KUBECONFIG: "{{ kubeconfig_path }}"
  roles:
    - argocd

- name: Display cluster information
  hosts: servers[0]
  gather_facts: false
  become: true
  tasks:
    - name: Wait for all nodes to be ready
      ansible.builtin.command: >
        kubectl get nodes
      register: cluster_nodes
      changed_when: false
      retries: 10
      delay: 10
      until: cluster_nodes.rc == 0

    - name: Display cluster nodes
      ansible.builtin.debug:
        msg: "{{ cluster_nodes.stdout_lines }}"
