---
- name: Remove k3s data and configuration
  hosts: cluster
  gather_facts: false
  become: true
  tasks:
    - name: Stop and disable k3s service
      ansible.builtin.systemd:
        name: k3s
        state: stopped
        enabled: false

    - name: Remove k3s data and config directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/rancher/k3s
        - /etc/rancher/k3s
        - /etc/rancher/node

    - name: Create empty k3s data and config directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: root
        group: root
      loop:
        - /var/lib/rancher/k3s
        - /etc/rancher/k3s
        - /etc/rancher/node
