---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: lidarr
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/downloads/lidarr
      recursive: false
  targets:
    - name: lidarr-secret
      namespace: downloads
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          LIDARR__AUTH__APIKEY: "{{ .LIDARR_API_KEY.Value }}"
    # Envoy apiKeyAuth format: <client id>: <api key>
    - name: lidarr-apikey
      namespace: downloads
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          lidarr: "{{ .LIDARR_API_KEY.Value }}"
