---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: rook-ceph-dashboard
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/rook-ceph
      recursive: false
  targets:
    - name: rook-ceph-dashboard-password # rook-ceph expects this name
      namespace: rook-ceph
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          password: "{{ .ROOK_DASHBOARD_PASSWORD.Value }}"