name: tailscale

services:
  app:
    image: docker.io/tailscale/tailscale:v1.98.8@sha256:d54b2e6a9c09f0e5ec52e82b9ad4af3d446b54a7c08075e92f11c39dd410105f
    container_name: tailscale_app_1
    environment:
      - TZ=${TZ}
      - TS_NO_LOGS_NO_SUPPORT=true # https://tailscale.com/kb/1011/log-mesh-traffic?tab=linux#opt-out-of-client-logging
    command: >
      sh -c '
        tailscaled --tun=userspace-networking &
        TS_PID=$!
        sleep 5
        tailscale up --reset
        tailscale web --listen=0.0.0.0:8240 &
        wait $TS_PID
      '
    volumes:
      - ${APP_DATA_DIR}/tailscale/var:/var/lib/tailscale
    network_mode: host
    restart: unless-stopped
