---
- name: Create rootless group
  ansible.builtin.group:
    name: "{{ rootless_user }}"
    system: true
  tags: user

- name: Create rootless user
  ansible.builtin.user:
    name: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    groups: systemd-journal
    shell: /bin/bash
    home: "/home/{{ rootless_user }}"
    system: true
    state: present
  tags: user

- name: Add ansible_user to the rootless group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ rootless_user }}"
    append: true
    state: present
  tags: user

- name: Get UID of {{ rootless_user }}
  ansible.builtin.command:
    argv: ["/usr/bin/id", "-u", "{{ rootless_user }}"]
  register: rootless_uid
  changed_when: false
  tags: user

- name: Setting subuid and subgid
  ansible.builtin.blockinfile:
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0644"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Default"
    content: |
      {{ rootless_user }}:300000:65536
  with_items:
    - /etc/subuid
    - /etc/subgid
  tags: user

- name: Create /etc/containers/nodocker file
  ansible.builtin.file:
    path: /etc/containers/nodocker
    state: touch
    owner: root
    group: root
    mode: "0644"
  tags: podman

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /var/lib/containers/user/{{ rootless_user }}/storage
    state: directory
    mode: "0700"
  tags: podman

- name: Ensure correct permissions on /var/lib/containers
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0711"
  loop:
    - /var/lib/containers
    - /var/lib/containers/user
  tags: podman

- name: Ensure correct ownership and permissions on /var/lib/containers/user/{{ rootless_user }}
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0700"
  with_items:
    - /var/lib/containers/user/{{ rootless_user }}
    - /var/lib/containers/user/{{ rootless_user }}/storage
  tags: podman

- name: Afegir/actualitzar mappings SELinux
  community.general.sefcontext:
    target: "{{ item.target }}"
    setype: "{{ item.setype }}"
    state: present
    reload: true
  loop:
    - target: "/var/lib/containers/user/[^/]+/storage/overlay(/.*)?"
      setype: "container_ro_file_t"
    - target: "/var/lib/containers/user/[^/]+/storage/overlay2(/.*)?"
      setype: "container_ro_file_t"
    - target: "/var/lib/containers/user/[^/]+/storage/overlay2-images(/.*)?"
      setype: "container_ro_file_t"
    - target: "/var/lib/containers/user/[^/]+/storage/overlay2-layers(/.*)?"
      setype: "container_ro_file_t"
    - target: "/var/lib/containers/user/[^/]+/storage/overlay-layers(/.*)?"
      setype: "container_ro_file_t"
    - target: "/var/lib/containers/user/[^/]+/storage/overlay-images(/.*)?"
      setype: "container_ro_file_t"
    - target: "/var/lib/containers/user/[^/]+/storage/volumes/[^/]*/.*"
      setype: "container_file_t"
  tags: selinux

- name: Restorecon recursiu i forçat sobre /var/lib/containers/user
  ansible.builtin.command: |
    restorecon -RvF /var/lib/containers/user
  changed_when: false
  tags: selinux

- name: Check if APP_DATA_DIR directory exists
  ansible.builtin.stat:
    path: "{{ app_data_dir }}"
  register: app_data_dir_stat
  tags: podman

- name: Create APP_DATA_DIR directory if it doesn't exist
  ansible.builtin.command: |
    transactional-update --continue run bash -c '
      mkdir -p "{{ app_data_dir }}" &&
      chown root:root "{{ app_data_dir }}" &&
      chmod 0755 "{{ app_data_dir }}"'
  register: create_app_data_dir
  when: not app_data_dir_stat.stat.exists
  changed_when: create_app_data_dir.rc == 0
  failed_when: create_app_data_dir.rc != 0
  tags: podman

- name: Unconditionally reboot the machine with all defaults
  ansible.builtin.reboot:
    connect_timeout: 5
    reboot_command: "{{ custom_reboot_command | default(omit) }}"
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: create_app_data_dir is changed # noqa: no-handler
  tags: reboot

- name: Mount NFS share
  ansible.builtin.mount:
    src: "{{ nfs_server }}:{{ nfs_path }}"
    path: "{{ app_data_dir }}"
    fstype: nfs
    opts: "{{ nfs_options }}"
    state: mounted
  when:
    - nfs_server is defined
    - nfs_path is defined
  register: nfs_mount
  tags: nfs

- name: Change ownership of NFS mount point
  ansible.builtin.file:
    path: "{{ app_data_dir }}"
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0755"
    recurse: true
  when:
    - nfs_server is defined
    - nfs_path is defined
    - nfs_mount is succeeded
  tags: nfs

- name: Create directory for secrets on NFS share
  ansible.builtin.file:
    path: "{{ app_data_dir }}/secrets"
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0700"
  when:
    - nfs_server is defined
    - nfs_path is defined
    - nfs_mount is succeeded
  tags:
    - nfs
    - podman

- name: Symlink secrets directory to podman storage
  ansible.builtin.file:
    src: "{{ app_data_dir }}/secrets"
    dest: "/var/lib/containers/user/{{ rootless_user }}/storage/secrets"
    state: link
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0700"
    force: true
  when:
    - nfs_server is defined
    - nfs_path is defined
    - nfs_mount is succeeded
  tags:
    - nfs
    - podman

- name: Create directory for environment.d
  ansible.builtin.file:
    path: "/home/{{ rootless_user }}/.config/environment.d"
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0700"
  tags:
    - user
    - podman

- name: Append .environment.d config for user -> {{ rootless_user }}
  ansible.builtin.blockinfile:
    path: "/home/{{ rootless_user }}/.config/environment.d/50-homelab.conf"
    block: |
      XDG_CONFIG_HOME=$HOME/.config
      XDG_RUNTIME_DIR=/run/user/{{ rootless_uid.stdout | trim }}
      DOCKER_HOST=unix:///run/user/{{ rootless_uid.stdout | trim }}/podman/podman.sock
      PODMAN_COMPOSE_WARNING_LOGS=0
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Podman config"
    create: true
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0644"
  tags:
    - user
    - podman

# - name: Append .bashrc for user -> {{ rootless_user }}
#   ansible.builtin.blockinfile:
#     path: "/home/{{ rootless_user }}/.bashrc"
#     block: |
#       export XDG_CONFIG_HOME=$HOME/.config
#       export XDG_RUNTIME_DIR=/run/user/$(id -u)
#       export DOCKER_HOST=unix:///run/user/$(id -u)/podman/podman.sock
#       export PODMAN_COMPOSE_WARNING_LOGS=0
#     marker: "# {mark} ANSIBLE MANAGED BLOCK - Podman config"
#     create: true
#     owner: "{{ rootless_user }}"
#     group: "{{ rootless_user }}"
#     mode: "0644"
#   tags:
#     - user
#     - podman

- name: Create containers storage.conf
  ansible.builtin.blockinfile:
    path: "/home/{{ rootless_user }}/.config/containers/storage.conf"
    block: |
      [storage]
      driver = "overlay"
      rootless_storage_path = "/var/lib/containers/user/{{ rootless_user }}/storage"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Storage config"
    create: true
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0644"
  tags:
    - user
    - podman

- name: Enable Linger for user -> {{ rootless_user }}
  ansible.builtin.command:
    argv: [/usr/bin/loginctl, enable-linger, "{{ rootless_user }}"]
    creates: "/var/lib/systemd/linger/{{ rootless_user }}"
  tags: system

- name: Ensure directory exists -> /run/user/{{ rootless_uid.stdout | trim }}
  ansible.builtin.file:
    path: "/run/user/{{ rootless_uid.stdout | trim }}"
    state: directory
    owner: "{{ rootless_user }}"
    group: "{{ rootless_user }}"
    mode: "0700"
  tags:
    - user
    - podman

- name: Start and enable podman.socket for user -> {{ rootless_user }}
  become: true
  become_method: community.general.machinectl # noqa: schema
  become_user: "{{ rootless_user }}"
  vars:
    ansible_pipelining: true
  ansible.builtin.systemd_service:
    name: podman.socket
    state: started
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ rootless_uid.stdout | trim }}"
  changed_when: false
  tags:
    - user
    - podman

- name: Setup age encryption for rootless user
  become: true
  become_method: community.general.machinectl # noqa: schema
  become_user: "{{ rootless_user }}"
  vars:
    ansible_pipelining: true
  tags:
    - age
    - sops
  block:
    - name: Create age secret directory
      ansible.builtin.file:
        path: "/home/{{ rootless_user }}/.config/sops/age"
        state: directory
        owner: "{{ rootless_user }}"
        group: "{{ rootless_user }}"
        mode: "0700"

    - name: Check if age key already exists
      ansible.builtin.stat:
        path: "/home/{{ rootless_user }}/.config/sops/age/keys.txt"
      register: age_key_file

    - name: Generate age key for rootless user -> {{ rootless_user }}
      ansible.builtin.command:
        argv:
          - /usr/bin/age-keygen
          - -o
          - /home/{{ rootless_user }}/.config/sops/age/keys.txt
      args:
        creates: "/home/{{ rootless_user }}/.config/sops/age/keys.txt"
      when: not age_key_file.stat.exists

    - name: Catch public age key and show it
      ansible.builtin.command:
        argv:
          - /usr/bin/age-keygen
          - -y
          - /home/{{ rootless_user }}/.config/sops/age/keys.txt
      register: age_public_key
      changed_when: false

    - name: Display public age key for rootless user -> {{ rootless_user }}
      ansible.builtin.debug:
        msg: >-
          Public age key for user '{{ rootless_user }}':
          {{ age_public_key.stdout }}
