[[stack]]
name = "speedtest-host01"
description = "Stack Speedtest"
deploy = true
tags = ["host01", "prod"]

[stack.config]
server_id = "host01"
linked_repo = "homelab-host01"
run_directory = "compose/host01/prod/speedtest"
auto_pull = true
send_alerts = true

compose_cmd_wrapper = """
sops exec-env compose.env '[[COMPOSE_COMMAND]]'"""
