apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-share-plex
spec:
  capacity:
    storage: 20Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ds920plus.home.eudald.gr
    path: /volume1/data
  mountOptions:
    - nfsvers=4.1
