---
services:
  app:
    image: ghcr.io/alam00000/bentopdf-simple:v2.1.0@sha256:f7544d2c59aec118b1346ff79e4837b3cb216c889073f2857e079389957308bc
    container_name: bentopdf_app_1
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - 3183:8080
    labels:
      # Public Resource Configuration
      - pangolin.proxy-resources.bentopdf.name=bentopdf
      - pangolin.proxy-resources.bentopdf.full-domain=${BENTOPDF_HOSTNAME}
      - pangolin.proxy-resources.bentopdf.protocol=http
      # Target Configuration - Override to Host Hairpin
      - pangolin.proxy-resources.bentopdf.targets[0].method=http
      - pangolin.proxy-resources.bentopdf.targets[0].hostname=host.containers.internal
      - pangolin.proxy-resources.bentopdf.targets[0].port=3183
      # Health Check Configuration
      - pangolin.proxy-resources.bentopdf.targets[0].healthcheck.enabled=true
      - pangolin.proxy-resources.bentopdf.targets[0].healthcheck.hostname=host.containers.internal
      - pangolin.proxy-resources.bentopdf.targets[0].healthcheck.port=3183
      - pangolin.proxy-resources.bentopdf.targets[0].healthcheck.path=/
    restart: unless-stopped
