---
apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: grafana-admin-password
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical-system
  syncOptions:
    refreshInterval: 5m
  sources:
    - projectSlug: homelab
      environmentSlug: prod
      secretPath: /kubernetes/o11y/grafana
      recursive: false
  targets:
    - name: grafana-admin-password-secret
      namespace: o11y
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          GF_SECURITY_ADMIN_PASSWORD: "{{ .GF_SECURITY_ADMIN_PASSWORD.Value }}"