---
working_dir: ./compose/ds920plus
auto_discovery:
  enabled: true
  depth: 1
  delete: true
force_recreate: false
reconciliation:
  enabled: true
  interval: 3600
environment:
  APP_DATA_DIR: /volume2/docker
  S3_DATA_DIR: /volume1/s3
  PUID: "1027"
  PGID: "100"
  TZ: Europe/Madrid
external_secrets:
  GARAGE_RPC_SECRET: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/compose/ds920plus/s3/garage/GARAGE_RPC_SECRET
  GARAGE_ADMIN_TOKEN: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/compose/ds920plus/s3/garage/GARAGE_ADMIN_TOKEN
  RUSTFS_HOSTNAME: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/compose/ds920plus/s3/rustfs/RUSTFS_HOSTNAME
  RUSTFS_ACCESS_KEY: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/compose/ds920plus/s3/rustfs/RUSTFS_ACCESS_KEY
  RUSTFS_SECRET_KEY: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/compose/ds920plus/s3/rustfs/RUSTFS_SECRET_KEY
  PANGOLIN_ENDPOINT: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/compose/ds920plus/newt/PANGOLIN_ENDPOINT
  NEWT_ID: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/compose/ds920plus/newt/NEWT_ID
  NEWT_SECRET: 89d5ec5c-6201-4007-acc8-3f4748228396:prod:/compose/ds920plus/newt/NEWT_SECRET
---
name: doco-cd-updater
working_dir: ./compose/ds920plus/doco-cd
compose_files:
  - compose.updater.yaml
force_recreate: true
reconciliation:
  enabled: true
  interval: 3600
