#!/bin/sh

dw()
{
    if [ -z "$(ls -A "$COREBOOT_BUILD_DIR" 2>/dev/null)" ]; then
        git clone --branch "$COREBOOT_TAG" "$_url" "$COREBOOT_BUILD_DIR"

        cd "$COREBOOT_BUILD_DIR"
        #gpg --receive-keys "574C E6F6 855C FDEB 7D36  8E9D 1979 6C2B 3E4F 7DF7"
        #git verify-tag "$COREBOOT_TAG"
        #git submodule update --init --recursive --remote

        git clone "https://review.coreboot.org/blobs"           3rdparty/blobs
        git clone "https://review.coreboot.org/intel-microcode" 3rdparty/intel-microcode
    elif [ -d "$COREBOOT_BUILD_DIR/.git" ]; then
        if [ "$($_chk)" = "$COREBOOT_TAG" ]; then
            printf '%s\n' "Already on tag $COREBOOT_TAG"
            return 0
        fi

        cd "$COREBOOT_BUILD_DIR"                          && git fetch --all --tags --prune

        [ -z "$(ls -A "$COREBOOT_BUILD_DIR/3rdparty/blobs" 2>/dev/null)" ] &&
            git clone "https://review.coreboot.org/blobs"           3rdparty/blobs

        [ -z "$(ls -A "$COREBOOT_BUILD_DIR/3rdparty/intel-microcode" 2>/dev/null)" ] &&
            git clone "https://review.coreboot.org/intel-microcode" 3rdparty/intel-microcode

        cd "$COREBOOT_BUILD_DIR/3rdparty/blobs"           && git fetch --all --tags --prune
        cd "$COREBOOT_BUILD_DIR/3rdparty/intel-microcode" && git fetch --all --tags --prune

        cd "$COREBOOT_BUILD_DIR"
        git checkout "$_tag"
        git submodule update --recursive --remote
    else
        printf '%s\n' "Error: $COREBOOT_BUILD_DIR is not a git repository and is not empty."
        exit 1
    fi
}

px()
{
    # Update iPXE payload to a more recent version, default version not suitable
    cd "$COREBOOT_BUILD_DIR"

    sed 's/2023.8/2024.12/' payloads/external/iPXE/Kconfig > _
    mv _ payloads/external/iPXE/Kconfig

    sed 's/^STABLE_COMMIT_ID=.*/STABLE_COMMIT_ID=8b8a50a85d4763da6d353719d6022d01c7a09751/' payloads/external/iPXE/Makefile > _
    mv _ payloads/external/iPXE/Makefile

    # Apply 85161: soc/intel: Assert if `pmc_/gpe0_dwX` values are not unique | https://review.coreboot.org/c/coreboot/+/85161
    # wget -O 85161-pmc-gpe0.patch https://github.com/coreboot/coreboot/commit/640a41f3ee938b794b140218921e0fd63b1d9235.patch
    # patch -p1 < 85161-pmc-gpe0.patch

    # Apply 86164: soc/intel: Allow zero values for PMC GPE0 DW registers | https://review.coreboot.org/c/coreboot/+/86164
    # wget -O 86164-pmc-gpe0.patch https://github.com/coreboot/coreboot/commit/bfb04753867defde6b0b9557dbfd263feda99fcd.patch
    # patch -p1 < 86164-pmc-gpe0.patch

    # Revert 85161: soc/intel: Assert if `pmc_/gpe0_dwX` values are not unique | https://review.coreboot.org/c/coreboot/+/85161
    # wget -O 85161-pmc-gpe0.patch https://github.com/coreboot/coreboot/commit/640a41f3ee938b794b140218921e0fd63b1d9235.patch
    # patch -p1 -R --force < 85161-pmc-gpe0.patch
    # git revert 640a41f3ee938b794b140218921e0fd63b1d9235
}

ex()
{
    mkdir -p "$COREBOOT_BUILD_DIR/3rdparty/blobs/mainboard/$MAINBOARD/$MODEL"

    (
        cd "$COREBOOT_BUILD_DIR/util/ifdtool"
        make -j"$(nproc)"
        make install DESTDIR="$COREBOOT_BUILD_DIR/3rdparty/blobs/mainboard/$MAINBOARD/$MODEL" PREFIX=""
    )

    if [ ! -f "$COREBOOT_BUILD_DIR/3rdparty/blobs/mainboard/$MAINBOARD/$MODEL/gbe.bin" ]; then
        cd "$COREBOOT_BUILD_DIR/3rdparty/blobs/mainboard/$MAINBOARD/$MODEL"

        cp -v "$COREBOOT_STOCK_BIOS_DIR/$COREBOOT_STOCK_BIOS_ROM" .

        ./bin/ifdtool "${PLATFORM:+-p$PLATFORM}" -u "$COREBOOT_STOCK_BIOS_ROM"
        ./bin/ifdtool "${PLATFORM:+-p$PLATFORM}" -x "$COREBOOT_STOCK_BIOS_ROM"

        mv flashregion_0_flashdescriptor.bin descriptor.bin
        mv flashregion_2_intel_me.bin        me.bin
        mv flashregion_3_gbe.bin             gbe.bin

        rm -f flashregion_1_bios.bin
    fi
}

me()
{
    [ -z "$(ls -A "$COREBOOT_BUILD_DIR/util/me_cleaner/.git" 2>/dev/null)" ] &&
        rm -rf "$COREBOOT_BUILD_DIR/util/me_cleaner"

    if [ -z "$(ls -A "$COREBOOT_BUILD_DIR/util/me_cleaner" 2>/dev/null)" ]; then
        git clone https://github.com/corna/me_cleaner.git "$COREBOOT_BUILD_DIR/util/me_cleaner"
    elif [ -d "$COREBOOT_BUILD_DIR/util/me_cleaner/.git" ]; then
        cd "$COREBOOT_BUILD_DIR/util/me_cleaner"
        git fetch --all --tags --prune
    fi

    cd "$COREBOOT_BUILD_DIR/util/me_cleaner"
    if [ "$(git rev-parse --abbrev-ref HEAD)" != "pr-282" ]; then
        # NOOO! PR 384 adds support for the Intel ME up to 16.0 firmware
        # PR 282 adds support for the Intel ME up to 12.0 firmware
        git fetch origin pull/282/head:pr-282
        git checkout pr-282
    fi

    cd "$COREBOOT_BUILD_DIR/3rdparty/blobs/mainboard/$MAINBOARD/$MODEL"
    if [ ! -f "me_cleaner.done" ]; then
            #--extract-descriptor descriptor.bin \
            #--extract-me me.bin \
        python3 "$COREBOOT_BUILD_DIR/util/me_cleaner/me_cleaner.py" \
            --descriptor \
            --soft-disable-only \
            --output output.rom \
            "$COREBOOT_STOCK_BIOS_ROM" && \
            mv output.rom "$COREBOOT_STOCK_BIOS_ROM" && \
            touch me_cleaner.done
    fi
}

mk()
{
    cd "$COREBOOT_BUILD_DIR"

    if [ "$COREBOOT_DISTRO" = "coreboot" ]; then
        cp -v "$COREBOOT_CONFIG_DIR/bootsplash.jpg" "$COREBOOT_BUILD_DIR/bootsplash.jpg"
    fi

    cp -v "$COREBOOT_CONFIG_DIR/$_cnf"          "$COREBOOT_BUILD_DIR/configs/defconfig"

    if [ -f "$COREBOOT_BUILD_DIR/3rdparty/blobs/mainboard/$MAINBOARD/$MODEL/descriptor.bin" ]; then
        printf '\n%s' "CONFIG_HAVE_IFD_BIN=y" >> "$COREBOOT_BUILD_DIR/configs/defconfig"
    fi

    if [ -f "$COREBOOT_BUILD_DIR/3rdparty/blobs/mainboard/$MAINBOARD/$MODEL/me.bin" ]; then
        printf '\n%s' "CONFIG_HAVE_ME_BIN=y" >> "$COREBOOT_BUILD_DIR/configs/defconfig"
    fi

    if [ -f "$COREBOOT_BUILD_DIR/3rdparty/blobs/mainboard/$MAINBOARD/$MODEL/gbe.bin" ]; then
        printf '\n%s' "CONFIG_HAVE_GBE_BIN=y" >> "$COREBOOT_BUILD_DIR/configs/defconfig"
    fi

    # if [ "$COREBOOT_DISTRO" = "coreboot" ] && [ "$COREBOOT_TAG" = "25.03" ]; then
    #     printf '\n%s' "CONFIG_EDK2_TAG_OR_REV=\"origin/uefipayload_2502\"" >> "$COREBOOT_BUILD_DIR/configs/defconfig"
    # fi

    make defconfig

    if [ "$COREBOOT_CONFIG" = "manual" ]; then
        make nconfig || exit
        make savedefconfig
    fi

    # payloads/external/edk2/workspace/mrchromebox/UefiPayloadPkg/UefiPayloadPkg.fdf
    # DEFINE FD_SIZE     = 0x9A4000
    # DEFINE NUM_BLOCKS  = 0x9A4

    # sed -i '23i\\nDEFINE FD_SIZE     = 0x9A4000\nDEFINE NUM_BLOCKS  = 0x9A4' "UefiPayloadPkg/UefiPayloadPkg.fdf"
#     sed -i 's|git submodule update --init --checkout|git submodule update --init --checkout; \\\
# \t\t\t\t\tsed -i '\''23i\\\\nDEFINE FD_SIZE     = 0x9A4000\\nDEFINE NUM_BLOCKS  = 0x9A4'\'' "UefiPayloadPkg/UefiPayloadPkg.fdf"|' payloads/external/edk2/Makefile

    V="$_DEBUG" make CPUS="$(nproc)"
}

sm()
{
    dd if="$COREBOOT_BUILD_DIR/build/coreboot.rom" of="$COREBOOT_OUTPUT_DIR/$_nme-$MAINBOARD-$MODEL-jbios1.rom" bs=16M count=1
    dd if="$COREBOOT_BUILD_DIR/build/coreboot.rom" of="$COREBOOT_OUTPUT_DIR/$_nme-$MAINBOARD-$MODEL-jbios2.rom" bs=8M  skip=2

    mv "$COREBOOT_BUILD_DIR/build/coreboot.rom" "$COREBOOT_OUTPUT_DIR/$_nme-$MAINBOARD-$MODEL-full.rom"

    sha256sum "$COREBOOT_OUTPUT_DIR/$_nme-$MAINBOARD-$MODEL-full.rom"   > "$COREBOOT_OUTPUT_DIR/$_nme-$MAINBOARD-$MODEL-full.rom.sha256"
    sha256sum "$COREBOOT_OUTPUT_DIR/$_nme-$MAINBOARD-$MODEL-jbios1.rom" > "$COREBOOT_OUTPUT_DIR/$_nme-$MAINBOARD-$MODEL-jbios1.rom.sha256"
    sha256sum "$COREBOOT_OUTPUT_DIR/$_nme-$MAINBOARD-$MODEL-jbios2.rom" > "$COREBOOT_OUTPUT_DIR/$_nme-$MAINBOARD-$MODEL-jbios2.rom.sha256"
}

# int main()
{
    # enable exit on error and disable globbing
    set -ef

    # false positive
    # shellcheck disable=2015
    [ "$_DEBUG" = 1 ] && set -x || :

    if [ "$COREBOOT_DISTRO" = "coreboot" ]; then
        _url="https://review.coreboot.org/coreboot"
        _tag="tags/$COREBOOT_TAG"
        _chk="git -C $COREBOOT_BUILD_DIR describe --tags --abbrev=0"
        _cnf="defconfig.$COREBOOT_DISTRO.seabios"
        _nme="$COREBOOT_DISTRO"
    elif [ "$COREBOOT_DISTRO" = "dasharo" ]; then
        _url="https://github.com/Dasharo/coreboot.git"
        _tag="$COREBOOT_TAG"
        _chk="git -C $COREBOOT_BUILD_DIR rev-parse --abbrev-ref HEAD"
        _cnf="defconfig.$COREBOOT_DISTRO.edk2"
        _nme="$COREBOOT_DISTRO"
    elif [ "$COREBOOT_DISTRO" = "libreboot" ]; then
        # _url="https://github.com/Dasharo/coreboot.git"
        # _tag="$COREBOOT_TAG"
        # _chk="git -C $COREBOOT_BUILD_DIR rev-parse --abbrev-ref HEAD"
        # _cnf="defconfig.$COREBOOT_DISTRO.edk2"
        # _nme="$COREBOOT_DISTRO"
        printf '%s\n' "Error: Libreboot is not supported yet."
        exit 1
    else
        printf '%s\n' "Error: Unsupported coreboot distro '$COREBOOT_DISTRO'."
        exit 1
    fi

    dw
    px
    ex
    me
    mk
    sm
}